### ISSUE TITLE
Add an assert to check that the control group exists

### ISSUE THREAD

**Issue by t-tte** [uber/causalml#101]
The S-Learner will run even if the default control group name ('0') is not in the treatment array, leading to seemingly paradoxical results in which eg units in the control group are predicted to have a negative treatment effect under the control condition. The other learners may have this same problem too.

To prevent the above behaviour, we should add an assert to catch situations in which the default or user-specified control group name is not in the treatment array.

**Comment by peterfoley** [comment]
[The R-Learner](https://github.com/uber/causalml/blob/e235f1b4385290c5e28de6d1170148fa69ba5bfe/causalml/inference/meta/rlearner.py#L81) and a few other places use [`causalml.inference.meta.check_control_in_treatment`](https://github.com/uber/causalml/blob/e235f1b4385290c5e28de6d1170148fa69ba5bfe/causalml/inference/meta/utils.py#L4) for validation.

It doesn't seem like `check_control_in_treatment` would drop in directly, but I'd be happy to take a stab at generalizing it and adding the checks to the S-Learner.

Along with checking that the control group name is present in the treatment array, should we also require that the treatment array has non-control cases?

**Comment by t-tte** [comment]
Good point about the check_control_in_treatment function, @peterfoley! It'd be great if you could take a stab at generalizing it. I also agree that it would make sense to check that the treatment array has non-control cases.
