### ISSUE TITLE
Remove the need for big_number in causaltree.pyx

### ISSUE THREAD

**Issue by peterfoley** [uber/causalml#106]
Creating an issue to organize discussion that started in #105 (@jeongyoonlee, @TomaszZamacinski).

Summary of the issue is that sklearn's `DecisionTreeRegressor.fit()` raises` ValueError` if `min_impurity_split<0` and the `TreeBuilder`'s stop if `impurity<min_impurity_split`. Causal tree impurities can be negative, so sklearn's restriction doesn't help and the current workaround adds a large constant `big_number` to try to keep `impurity>0`.

`big_number` has to be large enough to ensure `impurity>0` in a large number of cases, but large values of `big_number` reduce numeric precision. It would be preferable to dodge sklearn's checks so that we can set `min_impurity_split` to negative infinity and ensure it has no impact on the tree construction.

While the `min_impurity_split` argument to `DecisionTreeRegressor` is deprecated and will be removed, I'm not sure whether it will be removed from the `TreeBuilder` classes, or whether it will just be fixed at 0 by `DecisionTreeRegressor` and not accessible to users.

**Comment by peterfoley** [comment]
It seems like we could dodge the checks by bypassing `DecisionTreeRegressor` and calling `DepthFirstTreeBuilder`, `BestSplitter` and `Tree` directly, roughly like this:

```py
# in CausalTreeRegressor
def fit(...):
  self.tree = Tree(...)
  splitter = BestSplitter(criterion = CausalMSE(...), ...)
  builder = DepthFirstTreeBuilder(splitter, ..., min_impurity_split=float("-inf"))
  builder.build(self.tree, ...)
  return self

def predict(self, X):
  return self.tree.predict(X).reshape((-1, 1))
```
where most of the current `DecisionTreeRegressor` arguments are instead passed directly to `DepthFirstTreeBuilder`'s constructor or `build` method. 

It's sort of reimplementing a fair bit of `DecisionTreeRegressor`/`BaseDecisionTree` just to dodge the argument check, but the actual meat of what we need from there is relatively small.

**Comment by jeongyoonlee** [comment]
Thanks @peterfoley! 

I like your suggestion. I think that logically `CausalTreeRegressor` is at the same level as `DecisionTreeRegressor` and it makes sense to use lower level APIs. It will allow us to further customize `CausalTreeRegressor` - like using separate data sets for tree construction and inference as proposed in the original Causal Tree paper.

@peterfoley, could you take a stab at it?

**Comment by peterfoley** [comment]
@jeongyoonlee I'll start on a PR this week -- just got back from holiday travels.
