### ISSUE TITLE
the uplift random forest is based on which paper?

### ISSUE THREAD

**Issue by DSXiangLi** [uber/causalml#114]

**Comment by jeongyoonlee** [comment]
`UpliftRandomForestClassifier` is based on [Ensemble methods for uplift modeling by Sołtys (2015)](https://link.springer.com/article/10.1007/s10618-014-0383-9) and its base learner, `UpliftTreeClassifier` is based on Decision trees for uplift modeling with single and multiple treatments by [Rzepakowski and Jaroszewicz (2012)](https://link.springer.com/article/10.1007/s10115-011-0434-0).

More references for other methods are available at the [API documentation site](https://causalml.readthedocs.io/en/latest/methodology.html).
