### ISSUE TITLE
Uplift Curves when random is negative with normalization 

### ISSUE THREAD

**Issue by ppstacy** [uber/causalml#119]
When generating the uplift curve plots (gain, lift and gini) if normalized by the random which is negative, the shape of other plots will be flipped. 

For example here with normalization:
![Image Pasted at 2019-12-6 14-57](https://user-images.githubusercontent.com/19823328/71838467-bbe2e880-306d-11ea-8cd6-ca6fbddf4033.png)

without normalization:
![Image Pasted at 2019-12-6 14-58](https://user-images.githubusercontent.com/19823328/71838486-c8ffd780-306d-11ea-8a86-9020964607f7.png)

**Comment by jeongyoonlee** [comment]
@ppstacy could you provide a test case with sample data to reproduce the bug?

**Comment by ppstacy** [comment]
```import numpy as np
import pandas as pd
from causalml.metrics import *


y = np.random.normal(-0.5, 2, 1000)
x1 = np.random.normal(-10, 10, 1000)
x2 = np.random.normal(0, 10, 1000)
x3 = np.random.normal(10, 10 , 1000)
w = np.random.randint(2, size=1000)

df = pd.DataFrame([y, w, x1, x2, x3]).T
df.columns = ['y', 'w', 'model1', 'model2', 'model3']

plot_gain(df, outcome_col='y', treatment_col='w',
              normalize=False, random_seed=42, n=100, figsize=(8, 8))

plot_gain(df, outcome_col='y', treatment_col='w',
              normalize=True, random_seed=42, n=100, figsize=(8, 8))
```
Here is the snip of the test case which not the exactly what we did in the project, but it can show that with and without normalization the sign of the plots changed which should be consistent.

Without normalization:
![image](https://user-images.githubusercontent.com/19823328/71919750-43962900-313a-11ea-899e-f862575f43c3.png)

With normalization:
![image](https://user-images.githubusercontent.com/19823328/71919773-4db82780-313a-11ea-9702-e67578057fdd.png)
