### ISSUE TITLE
Add CEVAE synthetic data generation process

### ISSUE THREAD

**Issue by ppstacy** [uber/causalml#120]
As a start of  the migration/add a wrapper of  `CEVAE` under `CausalML`, we can add the synthetic data generation process in CEVAE paper. (Causal Effect Inference with Deep Latent-Variable Models,  http://papers.nips.cc/paper/7223-causal-effect-inference-with-deep-latent-variable-models.pdf)

I noticed that we already have the implementation code under [pyro repo](https://github.com/pyro-ppl/pyro/blob/dev/examples/contrib/cevae/synthetic.py), maybe we can migrate it here to CausalML under [dataset](https://github.com/uber/causalml/tree/master/causalml/dataset)

**Comment by fritzo** [comment]
@ppstacy the code is very simple:

<details>

```py
def generate_data(args):
    """
    This implements the generative process of [1], but using larger feature and
    latent spaces ([1] assumes ``feature_dim=1`` and ``latent_dim=5``).
    """
    z = dist.Bernoulli(0.5).sample([args.num_data])
    x = dist.Normal(z, 5 * z + 3 * (1 - z)).sample([args.feature_dim]).t()
    t = dist.Bernoulli(0.75 * z + 0.25 * (1 - z)).sample()
    y = dist.Bernoulli(logits=3 * (z + 2 * (2 * t - 2))).sample()

    # Compute true ite for evaluation (via Monte Carlo approximation).
    t0_t1 = torch.tensor([[0.], [1.]])
    y_t0, y_t1 = dist.Bernoulli(logits=3 * (z + 2 * (2 * t0_t1 - 2))).mean
    true_ite = y_t1 - y_t0
    return x, t, y, true_ite
```

</details>

I think I'll need help understanding the requirements of causalml/datasets/*.py. Would anyone on the team be available to pair code this?
