### ISSUE TITLE
 AttributeError: 'UpliftTreeClassifier' object has no attribute 'treatment_group'

### ISSUE THREAD

**Issue by MelanieU** [uber/causalml#136]
**Describe the bug**
I'm testing the UpliftTreeClassifier with the dataset generated by dataset.classification and I get the following error when running:
```
uplift_tree = tree.growDecisionTreeFrom(df_res[x_name], df_res['treatment_group_key'].values, df_res['conversion'].values, 'KL', max_depth=10,
                             min_samples_leaf=100, depth=1,
                             min_samples_treatment=10, n_reg=100,
                             parentNodeSummary=None)
```
```

AttributeError: 'UpliftTreeClassifier' object has no attribute 'treatment_group'
```

**Comment by peterfoley** [comment]
The usual way to fit `UpliftTreeClassifier` would be to use the higher-level `fit()` method, which populates the model's `treatment_group` attribute before calling `growDecisionTreeFrom`.  Look at cell `In [4]:` in [the uplift tree visualization notebook](https://github.com/uber/causalml/blob/master/examples/uplift_tree_visualization.ipynb) for an example.

If you want to mess with lower-level internals and call `growDecisionTreeFrom()` directly, look at the `fit()` [source](https://github.com/uber/causalml/blob/c6c02297b589c4430c108ba8a0958e0e0a351a89/causalml/inference/tree/models.py#L158) to see what it expects.
