### ISSUE TITLE
Enable continuous target

### ISSUE THREAD

**Issue by shaddyab** [uber/causalml#143]
Are there any plans to add support for continuous target (sale, revenue, etc.)
Will this also include Qini index calculation?

**Comment by jeongyoonlee** [comment]
Hi @shaddyab, thanks for your question.

Currently, all meta-learners and the new NN learner under `inference.meta` and `inference.nn` suuport continuous outcomes, while `UpliftRandomForest` in `inference.tree` supports only binary outcomes. 

Qini index calculation (`metrics.get_qini()` is independent from inference methods and available regardless outcome types.
