### ISSUE TITLE
NearestNeighborMatch (match_by_group) does not give a 1 to 1 Matching

### ISSUE THREAD

**Issue by kenrick-goh** [uber/causalml#153]
When I am running this code, the match results throws out the dataframe for treatment and control group data

The control number is larger than the treatment numbers. 

I would understand if the control numbers is smaller than the treatment as some of the treatment data may not be match. However, it is reversed and I am stumped.

**Comment by yungmsh** [comment]
Hey @kendrick-goh, what version of causalml were you using? Also, would you be able to share the dataset you are using? Feel free to anonymize the data if there is sensitive information.
