### ISSUE TITLE
GridSearch and score

### ISSUE THREAD

**Issue by clfeutry** [uber/causalml#158]
Are you going to implement a GridSearch method ?
I've tried to implement a Gridsearch method over the parameters for the UpliftRandomForestClassifier. What score would you recommand me using ?

**Comment by t-tte** [comment]
For now there are no plans to implement parameter search methods for UpliftRandomForestClassifier as a part of Causal ML. The question about recommended parameter values is an excellent one but unfortunately cannot be answered yet: our testing shows that "it depends". The safest approach for you is to evaluate multiple values with data in which you know the ground truth. This could be either data from a randomised experiment or data that is simulated.
