### ISSUE TITLE
Issue with kl_divergence function in UpliftTreeClassifier in inference\tree\models.py

### ISSUE THREAD

**Issue by clfeutry** [uber/causalml#167]
It occurs to me that the following definition of the kl divergence can return NAN:
`def kl_divergence(pk, qk):
        '''
        Calculate KL Divergence for binary classification.

        sum(np.array(pk) * np.log(np.array(pk) / np.array(qk)))

        Args
        ----
        pk : float
            The probability of 1 in one distribution.
        qk : float
            The probability of 1 in the other distribution.

        Returns
        -------
        S : float
            The KL divergence.
        '''
        if qk < 0.1**6:
            qk = 0.1**6
        elif qk > 1-0.1**6:
            qk = 1-0.1**6
        S = pk * np.log(pk / qk) + (1-pk) * np.log((1-pk) / (1-qk))
        return S
`
If pk=0 or pk=1 numpy log function does not manage 0*log(0). In Cover and Thomas, _Elements of Information Theory_ the KL is defined for pk=0 or 1 using  : 0*log(0/qk) =0 (even if qk=0 which cannot be the case here qk >=0.1**6)
My suggestion is the following: (suppress the terms 0*log(0/qk) by putting 0 instead)

`    def kl_divergence(pk, qk):
        '''
        Calculate KL Divergence for binary classification.

        sum(np.array(pk) * np.log(np.array(pk) / np.array(qk)))

        Args
        ----
        pk : float
            The probability of 1 in one distribution.
        qk : float
            The probability of 1 in the other distribution.

        Returns
        -------
        S : float
            The KL divergence.
        '''
        if qk < 0.1**6:
            qk = 0.1**6
        elif qk > 1-0.1**6:
            qk = 1-0.1**6
        if pk==0:
            S=(1-pk) * np.log((1-pk) / (1-qk))
        elif pk==1:
            S = pk * np.log(pk / qk)
        else:
            S = pk * np.log(pk / qk) + (1-pk) * np.log((1-pk) / (1-qk))
        return S`

**Comment by jeongyoonlee** [comment]
Thanks, @clfeutry for submitting the issue. It is fixed in PR #169. Looking forward to your contribution. :)

**Comment by clfeutry** [comment]
You're welcome. I'm glad to contribute :)
