### ISSUE TITLE
Use Case: Churn Prevention Campaigns

### ISSUE THREAD

**Issue by jroessler** [uber/causalml#168]
**Is your feature request related to a problem? Please describe.**
In your Docs you are mentioning Campaign Targeting Optimization and Personalized Engagement as typical use cases. But what about Churn Prevention Campaigns where the goal is to use the treatment/treatments to reduce customer churn? I'm working with a dataset where the dependent variable is whether a customer canceled the contract (1) or not (0). Thus, the dependent variable is twisted. Further, I am using your Tree based algorithms. 

**Describe the solution you'd like**
A separate section in the Docs with focus on Churn Prevention.

**Describe alternatives you've considered**
Is the solution as simple as twisting the dependent variable? Should I change the value of a dependent variable with `dependent variable = 1 - dependent variable` and use the new dependent variable for training? For example, if the dependent variable is 1 (customer canceled the contract), I can change it to `1 - 1 = 0`.

**Comment by huigangchen** [comment]
Hi @jroessler I think you are right. If you want to estimate the effect of the Churn Prevention Campaign where the goal is to reduce the cancellation, it makes sense to encode the cancellation at 1 and the estimated effect will be negative.
