### ISSUE TITLE
Transformed Variable Outcome Methodology Clarification in Documentation

### ISSUE THREAD

**Issue by ThatShelbs** [uber/causalml#171]
**Is your feature request related to a problem? Please describe.**

Exhausted all cited research, documentation, and also tried inspecting the code yet I am still struggling to understand if causalML meta-learners (S,X,T,R) use transformed outcome methods in-order to decompose to regression problems. The [Pylift meta-learner explicitly calls this step out in documentation](https://tech.wayfair.com/data-science/2018/10/pylift-a-fast-python-package-for-uplift-modeling/). 

**Describe the solution you'd like**
A clear description if any of the base meta-learners use transformed outcome methods and/or transformed covariate methods. If not then a description of how the problem might be decomposed to standard regression problems if I pass a binary treatment vector and a binary outcome vector. 

**Misc**
The [R Uplift package documentation](https://cran.r-project.org/web/packages/uplift/uplift.pdf) also has a detailed explanation on how it incorporates the transformed outcome method under Response Variable Transform for Uplift Modeling (rvtu). It also is clear if it is using undersample, oversample, or weights to deal with class imbalance.

**Comment by huigangchen** [comment]
Hi @ThatShelbs, the meta-learners do not use the transformed outcome as what Pylift uses. The implementation follows methods describe in [this](https://www.pnas.org/content/116/10/4156) and [this](https://arxiv.org/pdf/1712.04912). For example, T-learner may use scikit-learn algorithm to fit the treatment model and the control model separately, and the ITE is simply the difference between the treatment prediction and the control prediction.
