### ISSUE TITLE
Allow exposure of training evaluation results for xgboost models

### ISSUE THREAD

**Issue by JesseKolb** [uber/causalml#173]
## Overview
After calling `fit_predict` on a `BaseSRegressor` with the learner set to `xgboost.XGBRegressor()`, a `models` attribute containing a dictionary of models is created.  For a given model I would like to understand the model evaluation metrics during training.  

The [`evals_result` method ](https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRegressor.evals_result) returns these results, but in order for it to exist, the `eval_set` arg has to be passed to the fit function for xgboost.  As far as I can tell, because there is no way to pass this function when fitting the `BaseSRegressor` there is no way to obtain the evaluation metrics from training for the models.

## Proposed solutions
High-level view of solutions I can think of:

1. Allow custom args to `fit_predict` or `__init__` to cascade down to the `fit` function. Cons: user could pass args which are not used; warn user they're not used
2. Allow these xgboost-specific args. Cons: feels too custom
3. Expose evaluation metrics in some other way, not using the `fit` method
4. Don't use xgboost; use a package whose evaluation metrics are exposed when using `Causalml`.  I'm not opposed to this if this is possible as it could be the easiest solution.

## Similar issue
There is another feature request for grid search: https://github.com/uber/causalml/issues/158

**Comment by ppstacy** [comment]
Hi @JesseKolb thanks for proposing all the solutions above. As a start, I want to share this first. Currently in `Causalml` for all the meta-learner methods, if we turn on the logging at `INFO` level it will return some basic evaluation metrics of the base learner (which is xgboost for your case) for treatment and control group separately.  Below is the screenshot, do you think if this is sufficient?  Let me know, thanks!

```
import logging
logger = logging.getLogger('Causalml')
logging.basicConfig(level=logging.INFO)
```
![image](https://user-images.githubusercontent.com/19823328/85620137-34d3fd80-b618-11ea-9ca5-73131f81785c.png)
