### ISSUE TITLE
`UpliftTreeClassifier` docstring and input default parameters don't match.

### ISSUE THREAD

**Issue by bukosabino** [uber/causalml#176]
Hi Uber, 

Congratulations on your work with this awesome library.

I was checking the `UpliftTreeClassifier` input default parameters, and some of them don't match (code/docstring):

```python
max_features=10,
max_depth=3,
n_reg=10
```

https://github.com/uber/causalml/blob/ff9607b41af5944418d504bd14ccdb9cc5b69e37/causalml/inference/tree/models.py#L138

Please, update code or docstrings.

Best,
Dario

**Comment by ppstacy** [comment]
Hi @bukosabino thanks for capturing this! Apologies for the delay, we fixed this issue. Please continue using `Causaml` and let us know. Welcome for your future contribution as well, thanks!
