### ISSUE TITLE
Fail to predict cate

### ISSUE THREAD

**Issue by Jami1141** [uber/causalml#178]
I have an error running my multiple treatment classification problem:
If I use following code, I have cate results:
1)
learner = BaseSClassifier(XGBClassifier(), control_name='control')
learner.fit(X=X, treatment=treatment, y=y)
cate = learner.predict(X=X, treatment=treatment, y=y)

2)
But If I do following:
learner = BaseSClassifier(XGBClassifier(), control_name='control')
cate = learner.fit_predict(X=X, treatment=treatment, y=y)
print(cate)

I have following error:
NameError: name 'return_components' is not defined

If I use first 1) case, then when I want to calculate confidence interval of cate as following:
alpha = 0.05
learner = BaseSClassifier(XGBClassifier(), ate_alpha=alpha, control_name='control')
learner.fit(X=X, treatment=treatment, y=y)
cate, cate_lb, cate_ub = learner.predict(X=X, treatment=treatment, y=y, return_ci=True,
                               n_bootstraps=100, bootstrap_size=3000)

I have the same error as : NameError: name 'return_components' is not defined

I don't have error when I use your random data and use regression instead of classification. So I guess problem is because I use learner_s = BaseSRegressor(XGBRegressor(), control_name='control')
cate_s = learner_s.fit_predict(X=X, treatment=treatment, y=y, return_ci=False).

What should I do?

**Comment by yungmsh** [comment]
@Jami1141 thanks for calling this out - I was able to reproduce the bug on my end as well and we will fix this issue in the upcoming release. (cc @jeongyoonlee)

**Comment by ppstacy** [comment]
Thanks @Jami1141  for reporting the bug and using causalml. We already fixed this issue and merged it into master. It will be included in the next release. Meanwhile, you can use the latest master branch. Thanks!
