### ISSUE TITLE
Using UpliftRandomForestClassifier

### ISSUE THREAD

**Issue by Jami1141** [uber/causalml#179]
I am trying UpliftRandomForestClassifier to obtain CATE for multi treatment cases and binary outcome.
I see that for UpliftRandomForestClassifier you already have some examples. If I use binary treatment using UpliftRandomForestClassifier, then can I just keep control as 0 treatment and treatment_a to 1?
Then how control is treated? It is seen as a treatment?
I am asking this question to know If I want to use binary treatment using UpliftRandomForestClassifier, then will it be possible to use it for binary treatment as well?
The problem in this case is that cate only is calculated for treatment_a. At least what I see:
Put the predictions to a DataFrame for a neater presentation

result = pd.DataFrame(y_pred,
columns=uplift_model.classes_)
print(result)

  treatment_a  

0 0.0065
1 0.0042
2 0.0397
3 0.0158
4 0.0076
... ...
2216 0.0089
2217 0.0004
2218 0.0067
2219 0.0161
2220 0.0077

But I need to have cate for all treatments (control (0) and treatment (1)), which menas to have cate for each individual.

**Comment by jeongyoonlee** [comment]
Control is not regarded as a treatment. You don't get CATE for control because the treatment effect of a treatment is measured against the control. i.e. E[Y | X, A=treatment] - E[Y | X, A=control]. 

For a multi-treatment case, you need to pass the name of the control group to `UpliftRandomForestClassifier()`, and the treatment group along with the feature matrix and output vector to `fit()` as follows:
```python
uplift_model = UpliftRandomForestClassifier(control_name='control')
uplift_model.fit(df_train[x_names].values,
                 treatment=df_train['treatment_group_key'].values,
                 y=df_train['conversion'].values)
```

**Comment by Jami1141** [comment]
Thanks for your reply. So, I should make a new column as control? my
treatment column is included on 0,1,2 which 0 is control ones. Should I
separate control ones?

Thanks in advance
