### ISSUE TITLE
Estimating CATE for test and train data

### ISSUE THREAD

**Issue by Jami1141** [uber/causalml#182]
I have a question regarding CARE estimation.
I am using following code to estimate CATE. Is it true to estimate CATE for train and test data as I did:
<img width="608" alt="qu3" src="https://user-images.githubusercontent.com/62301816/83275543-90ed6280-a1cf-11ea-8fc9-db088dbc3c67.png">
I do it like this to be able to evaluate CATE estimations as you did as following:
<img width="692" alt="qu4" src="https://user-images.githubusercontent.com/62301816/83275967-34d70e00-a1d0-11ea-830b-242901d8c066.png">

I see that your evaluation works only for regression cases. How should I evaluate my cate values for classification case with multiple treatment?

**Comment by yungmsh** [comment]
@Jami1141 We don't have a function to perform validation summaries for classification problems yet, but note that this is for synthetic data only (to compute errors and MSE, you need the source of truth, which is unattainable in real life). So if you're trying to evaluate the performance of non-synthetic classification data, I'd use something like AUUC on holdout group for validation.
