### ISSUE TITLE
How UpliftRandomForestClassifier deals with imbalanced outcome?

### ISSUE THREAD

**Issue by Jami1141** [uber/causalml#185]
I want to use UpliftRandomForestClassifier for my problem. 
My data is highly imbalanced.
How do you deal with imbalancment? In RandomForest model we have a parameter called: class_weight. With this parameter we can control imbalancement for example using: Class_weigh ='balanced'.
But apparently, in Uplift model this is not the case.

Please first explain how UpliftRandomForestClassifier estimate CATE and then please explain how you deal with imbalanced data in this case.

Thanks in advance

**Comment by jeongyoonlee** [comment]
1. CATE calculation in `UpliftRandomForestClassifier`
`UpliftRandomForestClassifer` is a collection of `UpliftDecisionTreeClassifier`. It creates multiple `UpliftDecisionTreeClassifer` with random subsets of features and samples, and takes the average across the outputs of `UpliftDecisionTreeClassifier`s.

CATE in `UpliftDecisionTreeClassifer` is calculated as the average outcome difference in a leaf in the decision tree. i.e. It first finds which leaf (or end node) the sample ends up in the tree given feature values, then calculates the ATE of the node.

2. Imbalanced outcome
Currently, we don't adjust for the imbalanced outcome while we do treat the imbalanced treatment via normalization as defined in [Rzepakowski et al. 2012](https://link.springer.com/article/10.1007/s10115-011-0434-0).

Hope it helps.
