### ISSUE TITLE
Index out of Bound in growDecisionTreeFrom

### ISSUE THREAD

**Issue by jroessler** [uber/causalml#186]
**Describe the bug**
I'm getting an **index out of bound exception** in _models.py_ in the _growDecisionTreeFrom_ method in the following loop:

```
for col in list(np.random.choice(a=range(columnCount), size=max_features, replace=False)):
      columnValues = X[col]
```

**To Reproduce**

The shape of X in my case is: [26,42]. Thus, the current X has 26 samples and 42 columns/features. The `col` value in the loop can be between 0 and 42 due to the np.random.choice method with `range(columnCount) = 42`. Thus, it could happen that the col value is bigger than 26 which causes an index out of bound in `columnValues = X[col]` because 27 > X.shape[0] = 26. 

I used the following parameters:
"n_estimators": 100,
"max_depth": 5,
"min_samples_leaf": 50,
"evaluationFunction": "ED",
"min_samples_treatment": 5,
"n_reg": 10,
"control_name": "control"
The rest is set to default

**Expected behavior**
No Index out of Bound

**Possible Solution**
I'm not sure whether the slicing of X is correct. Shouldn't it be: `X[:,col]` in order to get all samples with only a specific number of columns?

**Screenshots**
Debug Output:
![Bildschirmfoto 2020-06-05 um 09 39 03](https://user-images.githubusercontent.com/23525054/83850077-a94e0780-a710-11ea-9223-de45ddf6b90b.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.6
 - Versions of Major Dependencies `pandas==1.0.2`, `scikit-learn==0.21.3`, `cython==0.29.14`

**Other Information:**

I just realized that if I change the _min_samples_leaf_ paramter from 5 to 50, the indexOutOfBound Exception is not happening anymore ..

**Comment by jeongyoonlee** [comment]
Thanks for reporting the issue, @jroessler. This issue was fixed in #125 and merged into `master` 5 months ago. Please update causalml and try it again.
