### ISSUE TITLE
could causalml supports centos?i can not pip install causalml successfully

### ISSUE THREAD

**Issue by ziyuwzf** [uber/causalml#198]
Compiling causalml/inference/tree/causaltree.pyx because it depends on /usr/local/python3/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
Cythonizing causalml/inference/tree/causaltree.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            if sample_weight != NULL:
                # the weights of 1 and 1 + eps are used for treatment and control respectively
                is_treated = (sample_weight[i] - 1.0) * one_over_eps

            # assume that there is only one output (k = 0)
            y_ik = self.y[i, 0]
                        ^
------------------------------------------------------------

causalml/inference/tree/causaltree.pyx:63:25: Invalid index type '(SIZE_t, long)'

Error compiling Cython file:
------------------------------------------------------------
...
            if sample_weight != NULL:
                # the weights of 1 and 1 + eps are used for treatment and control respectively
                is_treated = (sample_weight[i] - 1.0) * one_over_eps

            # assume that there is only one output (k = 0)
            y_ik = self.y[i, 0]
                        ^
------------------------------------------------------------

causalml/inference/tree/causaltree.pyx:108:25: Invalid index type '(SIZE_t, long)'

Error compiling Cython file:
------------------------------------------------------------
...
            if sample_weight != NULL:
                # the weights of 1 and 1 + eps are used for control and treatment respectively
                is_treated = (sample_weight[i] - 1.0) * one_over_eps

            # assume that there is only one output (k = 0)
            y_ik = self.y[i, 0]
                        ^
------------------------------------------------------------

causalml/inference/tree/causaltree.pyx:171:25: Invalid index type '(SIZE_t, long)'
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    ext_modules=cythonize(extensions),
  File "/usr/local/python3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/usr/local/python3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: causalml/inference/tree/causaltree.pyx

**Comment by jeongyoonlee** [comment]
Thanks @ziyuwzf for reporting the issue. Could please you share the versions of `Cython`, `scikit-learn`, and `numpy` installed on your system?

**Comment by ziyuwzf** [comment]
> Thanks @ziyuwzf for reporting the issue. Could please you share the versions of `Cython`, `scikit-learn`, and `numpy` installed on your system?

>>> import Cython
>>> import sklearn
>>> import numpy as np
>>> print(Cython.__version__)
0.22
>>> print(Cython.__version__,sklearn.__version__,np.__version__)
0.22 0.20.2 1.14.5
>>>

**Comment by jeongyoonlee** [comment]
Hi @ziyuwzf, thanks for sharing the information. The versions of `Cython`, `scikit-learn`, and `numpy` are older than ones required for `causalml`. Please update those packages as specified in `requirements.txt` before building or installing `causalml` as follows:
```bash
$ pip install -r requirements.txt
```

**Comment by jeongyoonlee** [comment]
I will
