### ISSUE TITLE
visualize feature importance and interactions in uplift random forest 

### ISSUE THREAD

**Issue by deeplaunch** [uber/causalml#203]
**Is your feature request related to a problem? Please describe.**
although the current version has great support to visualize a single uplift tree, there's no way to visualize the feature importance/interaction of uplift forest. this limits the ability to quickly understand what covariates drive the heterogeneous effects.

**Describe the solution you'd like**
would it be possible to create a visualisation using shapley values similar to others (e.g. slearner), which is shown in the [example](https://github.com/uber/causalml/blob/master/examples/feature_interpretations_example.ipynb)?

**Comment by yungmsh** [comment]
Addressed by https://github.com/uber/causalml/pull/220
