### ISSUE TITLE
evaluate model using AUCC 

### ISSUE THREAD

**Issue by lovejingru** [uber/causalml#207]
hello, a paper from Uber <Improve User Retention with Causal Learning> proposed a new evaluation metric called AUCC. This metric takes the "actual cost" into account to evaluate the ROI (return on investment).
Dose the causalml package has similar evaluate methods, or do you have plan to implement the AUCC? 
Thanks

**Comment by jeongyoonlee** [comment]
Thanks for your question, @lovejingru. Currently `causalml` doesn't implement AUCC (area under the cost curve). We will talk to the authors of the paper to see if we can add their algorithms as well as new metrics to `causalml` - AUCC will make sense when we have estimators that take into account costs.
