### ISSUE TITLE
X learner 'ElasticNetPropensityModel' error

### ISSUE THREAD

**Issue by clfeutry** [uber/causalml#208]
**Describe the bug**
In xleaner.py (inference/meta/xlearner.py) the line 693 return an error :

TypeError: 'ElasticNetPropensityModel' object is not subscriptable

when calling xlearner.predict(...)

here the lines 692-694:

`for group in self.t_groups:
                p_model = self.propensity_model[group]['all training']
                p[group] = p_model.predict(X)`

**To Reproduce**

I initialize the xlearner with the following functions from sklearn as arg:
control_outcome_learner=RandomForestClassifier(),                                                       treatment_outcome_learner=RandomForestClassifier(),                                                       control_effect_learner=KNeighborsRegressor(),                                                       treatment_effect_learner=KNeighborsRegressor()

**Findings**

changing the line 693 to 
`p_model = self.propensity_model[group]`
did it for me, but I'm sure this need further investigation.

**Comment by jeongyoonlee** [comment]
Thanks @clfeutry for reporting the bug. @ppstacy fixed it in #209, which has been merged into master. It will be included in the next release. Meanwhile, you can use the latest master. Thanks.
