### ISSUE TITLE
example for feature selection

### ISSUE THREAD

**Issue by reneix** [uber/causalml#211]
Is there any example code for feature selection? I'm using UpliftRandomForestClassifier
I saw this , but still not sure how to do filter works...
Feature Selection Methods for Uplift Modeling , https://arxiv.org/pdf/2005.03447.pdf
thx

**Comment by paullo0106** [comment]
Had a chance to catch up with @yungmsh , will create an example notebook based on their previous work

**Comment by yungmsh** [comment]
Thanks @paullo0106 !
