### ISSUE TITLE
BaseSlearner.estimate_ate doesn't work

### ISSUE THREAD

**Issue by dgeidman** [uber/causalml#215]
**Description**
The method BaseSClassifier.fit_predict() throws a TypeError because of an unexpected argument ('return_components') to fit()

**To Reproduce**
```python
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from causalml.dataset.classification import make_uplift_classification
from causalml.inference.meta.slearner import BaseSClassifier


np.random.seed(42)

df, x_names = make_uplift_classification(n_samples=1000, 
                                         treatment_name=['treatment', 'control'], 
                                         y_name='converted', random_seed=42)

df['treatment_group_key'] = np.where(df['treatment_group_key'] == 'control', 0, 1)

df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

uplift_model = BaseSClassifier(learner=XGBClassifier())

prediction = uplift_model.fit_predict(X=df_train[x_names].values,
                                      treatment=df_train['treatment_group_key'].values,
                                      y=df_train['converted'].values)
```

**Expected behavior**
Getting the predictions with no errors

**Environment:**
 - Linux
 - Python 3.6.10
 - pandas==1.0.3, sklearn==0.22.1, cython==0.29.15, XGboost==1.1.1

**Additional context**
I discovered this behavior when trying to call BaseSClassifier.estimate_ate().
The issue can be easily fixed by changing the predict method signature and returned types to match those of the other learners:

*Before:*
```python
def predict(self, X, treatment=None, y=None, verbose=True):
  """ function body
  """
    return te
```

*After:*
```python
def predict(self, X, treatment=None, y=None, verbose=True, return_components=False):
  """ function body
  """
    if not return_components:
            return te
        else:
            return te, yhat_cs, yhat_ts
```

**Comment by dgeidman** [comment]
Issue #178 seems related

**Comment by ppstacy** [comment]
Thanks @dgeidman for reporting the bug and using `causalml`.  We already fixed this issue and merged it into master. It will be included in the next release. Meanwhile, you can use the latest master. Thanks!
