### ISSUE TITLE
MLPT

### ISSUE THREAD

**Issue by Tanmay-Kulkarni101** [uber/causalml#216]
**Error on Running MLPT Regressor**
I get the following error
``
 AttributeError: 'MLPRegressor' object has no attribute '_best_coefs'
``

**To Reproduce**
I get this error when I run it with the following parameters:
``
MLPRegressor(early_stopping=True, hidden_layer_sizes=(10, 10),
             learning_rate_init=0.1)
``

**Expected behavior**
It should give me the value of the average treatment effect.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version: [3.8]

**Additional context**
It does not appear for python 3.6 and 3.7. Plus, the issue seems to be flaky, that is, it does not appear on a consistent basis. I got this error, when I was running tests on [dowhy](https://github.com/Microsoft/dowhy).

The full error dump can be found [here](https://dev.azure.com/ms/dowhy/_build/results?buildId=89522&view=logs&j=1ebc38c8-fade-5a89-24da-f796855a97f6&t=7e545587-1914-5048-c05b-92ed6ea139f6&l=2028)

**Comment by ppstacy** [comment]
Hi @Tanmay-Kulkarni101, thanks for using `causalml` and report this bug. `MLPTRegressor` is just our `BaseTRegressor` with `MLPRegressor` as the learner to estimate control and treatment outcomes that use sklearn's API.

I wasn't able to reproduce the bug with the below sklearn version. I think `causalml`'s `MLPTRegressor` is working fine here. Do you mind checking the sklearn version that you are using?

![image](https://user-images.githubusercontent.com/19823328/87984320-ab84df00-ca8e-11ea-9bef-4a4f1894e904.png)

**Comment by Tanmay-Kulkarni101** [comment]
It is a flaky issue. I am not too sure why the error occurs. I'll get back on how to reproduce the problem. I'm closing the issue for now.
