### ISSUE TITLE
ImportError: cannot import name 'factorial'

### ISSUE THREAD

**Issue by caizd1994** [uber/causalml#219]
from causalml.inference.meta import BaseSRegressor, BaseTRegressor, BaseXRegressor, BaseRRegressor
----> 7 from scipy.misc import factorial

ImportError: cannot import name 'factorial

requirement.txt ask scipy==1.4.0
but where scipy >= 1.3 
factorial is not in misc

**Expected behavior**
update the package

**Comment by ppstacy** [comment]
Hi @caizd1994, thanks for using `causalml` and reporting this. In our most recent requiremnt.txt we are using `scipy==1.14.1` because of the tensorflow requirement. I wasn't able to reproduce this bug, as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/19823328/88228929-c426fd80-cc24-11ea-932c-c75173e5ffdf.png)

Could you try to remove any cached or previous installation of causalml and install it again?

```
# from somewhere not in the causalml source directory
$ pip uninstall causalml 
$ pip install --no-cache-dir -U causalml
```

Please let me know if it helps.

**Comment by caizd1994** [comment]
when 

from causalml.inference.meta import BaseXRegressor

show this error


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-bc8da3399a8e> in <module>
----> 1 from causalml.inference.meta import BaseXRegressor

/conda/envs/notebook/lib/python3.6/site-packages/causalml/inference/meta/__init__.py in <module>
----> 1 from .slearner import LRSRegressor, BaseSLearner, BaseSRegressor, BaseSClassifier
      2 from .tlearner import XGBTRegressor, MLPTRegressor, BaseTLearner, BaseTRegressor, BaseTClassifier
      3 from .xlearner import BaseXLearner, BaseXRegressor, BaseXClassifier
      4 from .rlearner import BaseRLearner, BaseRRegressor, BaseRClassifier, XGBRRegressor
      5 from .tmle import TMLELearner

/conda/envs/notebook/lib/python3.6/site-packages/causalml/inference/meta/slearner.py in <module>
      4 from scipy.stats import norm
      5 from sklearn.dummy import DummyRegressor
----> 6 import statsmodels.api as sm
      7 from copy import deepcopy
      8 

/conda/envs/notebook/lib/python3.6/site-packages/statsmodels/api.py in <module>
     14 from . import robust
     15 from .robust.robust_linear_model import RLM
---> 16 from .discrete.discrete_model import (Poisson, Logit, Probit,
     17                                       MNLogit, NegativeBinomial,
     18                                       GeneralizedPoisson,

/conda/envs/notebook/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py in <module>
     43 
     44 from statsmodels.base.l1_slsqp import fit_l1_slsqp
---> 45 from statsmodels.distributions import genpoisson_p
     46 
     47 try:

/conda/envs/notebook/lib/python3.6/site-packages/statsmodels/distributions/__init__.py in <module>
      1 from .empirical_distribution import ECDF, monotone_fn_inverter, StepFunction
----> 2 from .edgeworth import ExpandedNormal
      3 from .discrete import genpoisson_p, zipoisson, zigenpoisson, zinegbin

/conda/envs/notebook/lib/python3.6/site-packages/statsmodels/distributions/edgeworth.py in <module>
      5 import numpy as np
      6 from numpy.polynomial.hermite_e import HermiteE
----> 7 from scipy.misc import factorial
      8 from scipy.stats import rv_continuous
      9 import scipy.special as special

ImportError: cannot import name 'factorial'
![image](https://user-images.githubusercontent.com/34201050/88251232-bdf45800-ccdc-11ea-8e42-524815f25110.png)

**Comment by ppstacy** [comment]
Hi, it seems this problem actually coming from `statsmodels`. I also saw similar issue [here](https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial) been discussed.  What's the `statsmodels` version you are using? Could you upgrade to `statsmodels>=0.9.0`? Thanks!

**Comment by ppstacy** [comment]
Hi @caizd1994, just want to check-in to see if you still have this issue? Thanks!

**Comment by manojbalaji1** [comment]
force upgrade of statsmodels fixes this issue
