### ISSUE TITLE
pip install causalml error

### ISSUE THREAD

**Issue by ziyuwzf** [uber/causalml#221]
ERROR: Command errored out with exit status 1:
     command: /usr/local/python3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f1ygkzh8/causalml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f1ygkzh8/causalml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p4o3_q4e
         cwd: /tmp/pip-install-f1ygkzh8/causalml/
    Complete output (53 lines):

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                if sample_weight != NULL:
                    # the weights of 1 and 1 + eps are used for treatment and control respectively
                    is_treated = (sample_weight[i] - 1.0) * one_over_eps

                # assume that there is only one output (k = 0)
                y_ik = self.y[i, 0]
                            ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:63:25: Invalid index type '(SIZE_t, long)'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                if sample_weight != NULL:
                    # the weights of 1 and 1 + eps are used for treatment and control respectively
                    is_treated = (sample_weight[i] - 1.0) * one_over_eps

                # assume that there is only one output (k = 0)
                y_ik = self.y[i, 0]
                            ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:108:25: Invalid index type '(SIZE_t, long)'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                if sample_weight != NULL:
                    # the weights of 1 and 1 + eps are used for control and treatment respectively
                    is_treated = (sample_weight[i] - 1.0) * one_over_eps

                # assume that there is only one output (k = 0)
                y_ik = self.y[i, 0]
                            ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:171:25: Invalid index type '(SIZE_t, long)'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f1ygkzh8/causalml/setup.py", line 56, in <module>
        ext_modules=cythonize(extensions),
      File "/usr/local/python3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
        cythonize_one(*args[1:])
      File "/usr/local/python3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: causalml/inference/tree/causaltree.pyx
    Compiling causalml/inference/tree/causaltree.pyx because it depends on /usr/local/python3/lib/python3.6/site-packages/Cython/Includes/numpy/__init__.pxd.
    Cythonizing causalml/inference/tree/causaltree.pyx
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ppstacy** [comment]
Hi @ziyuwzf thanks for reporting this. I saw there is an [issue](https://github.com/uber/causalml/issues/198) opened by you before here. Have you tried the solution provided there?

> Hi @ziyuwzf, thanks for sharing the information. The versions of Cython, scikit-learn, and numpy are older than ones required for causalml. Please update those packages as specified in requirements.txt before building or installing causalml as follows:
> 
> $ pip install -r requirements.txt
> I will close the issue for now. If you encounter another error, please open a new issue. Thanks for using causalml and reporting the issue. Hope it helps. :)

**Comment by jeongyoonlee** [comment]
@ziyuwzf, as mentioned in #198, could you make sure you have the required versions of `cython`, `scikit-learn`, and `numpy` installed?
