### ISSUE TITLE
Save the model and serializing?

### ISSUE THREAD

**Issue by mwijaya3** [uber/causalml#225]
Hello all,

Thanks for the awesome package! I tried to search the issues and see no mention of how we can save the model or better yet serializing and deserializing the model.

I am using [joblib](https://scikit-learn.org/stable/modules/model_persistence.html) to dump and load the model at the moment. Is that the correct approach here?

Thanks in advance!

**Comment by ppstacy** [comment]
Hi @mwijaya3 thanks for using `causalml`. I am using `joblib`  as well to save the model which is working perfectly for me. I think this approach works, I will close this issue for now. Please try it and let us know if you find any issues later. Thanks!

`joblib.dump(learner, model_path)`

**Comment by mwijaya3** [comment]
That's what I did as well. Thanks for the info @ppstacy.
