### ISSUE TITLE
Import errors: either 'no module's when installing from source, or "no attribute '__reduce_cython__'"

### ISSUE THREAD

**Issue by limorigu** [uber/causalml#226]
Many thanks for your work on this great project!

**Describe the bug**
I am trying to run your example notebook, and keep hitting import errors, regardless of continuous uninstall/install attempts. 

1) When installing form pip (even pip install --no-cache-dir -U causalml, as per #206), I end up running into

`AttributeError: type object 'causalml.inference.tree.causaltree.array' has no attribute '__reduce_cython__'`

as a response to 

`from causalml.inference.tree import CausalTreeRegressor` (as part of importing synthetic_data, actually)

2) when installing from source (as in README.md), I get errors of the type 

`ModuleNotFoundError: No module named 'causalml.inference.tree.causaltree'`

just like #206, when trying to do the same thing as above. 

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.6 
 - Python Version: 3.7.7
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): 
[`pandas== 1.0.3 `, `scikit-learn==0.23.2`, `cython==0.29.17 `]

Any advice would be greatly appreciated!

**Comment by limorigu** [comment]
I found #148, and indeed 

`python setup.py build_ext --inplace` from within the cloned repo folder did the job for me. I'm going to leave this open in case you think that should not be the expected behaviour -- but I did get it to work, in case other find themselves in a similar situation. 

Thanks!

**Comment by ppstacy** [comment]
Glad that you made it to work @limorigu. I will close this issue and please let us know if find anything else later. Thanks!
