### ISSUE TITLE
Problems with uplift tree visualization

### ISSUE THREAD

**Issue by Julia0207** [uber/causalml#230]
Hi,
 
thank you for the  useful examples. We had a special focus on **causalml/examples/uplift_tree_visualization.ipynb** and have a question regarding the last step, the tree visualization itself: 

After running 
**_Image(graph.create_png())_** 
we obtain the error message 
_“Graphviz executables not found”._ 
For that reason, we installed Graphviz 2.38 and mentioned the corresponding path in this statement:
**_import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin'_**
 
Now, we no longer obtain the error, but **we also do not see any plot.** In the python console it is just printed 
**### <IPython.core.display.Image object>.** 

Could you be so kind and tell us how we receive the plot (tree visualization)? 
 
Thank you very much and kind regards,
Julia, Anja and Inna

**Additional context**

**Comment by paullo0106** [comment]
Thanks for reaching out, @Julia0207 . I'm not too familiar with windows env, to be honest. Would some solutions in [this thread](https://stackoverflow.com/questions/35145509/why-is-ipython-display-image-not-showing-in-output) solve this?

**Comment by Julia0207** [comment]
Thank you very much!
