### ISSUE TITLE
Question about multi-treatment case

### ISSUE THREAD

**Issue by Shiutang-Li** [uber/causalml#235]
Hi team,

I was trying to run the X regressor with multiple treatments ('control', 'treatment_1', 'treatment_2'),
for 1000 rows.

learner_x = BaseXRegressor(learner=XGBRegressor(), control_name='control')
cate_x = learner_x.fit_predict(X=train[features], 
                               treatment=train['Treatment'], 
                               y=train['Target'],
                               return_components=True)

this is what I get:

>>cate_x[0][0]
array([-0.95575759,  0.99718887])

>>cate_x[1]
{'treatment_1': array([ 0.4385327 ,  0.1466563 , -0.38068253, ...,  0.24878561,
         0.04967707,  0.11624676], dtype=float32),
 'treatment_2': array([ 1.5608771 , -3.0802345 , -0.9914857 , ...,  0.05995879,
         0.18257728,  0.12813029], dtype=float32)}

>>cate_x[2]
{'treatment_1': array([-1.4990023 , -0.62844324, -2.9571688 , ...,  0.7084354 ,
        -0.02728522, -0.15055919], dtype=float32),
 'treatment_2': array([ 0.13210219, -0.68444014, -1.9061897 , ..., -0.38923156,
         0.19961098,  0.1978384 ], dtype=float32)}

**My question:**
1. What does cate_x[0][0] mean? Is the first element of cate_x[0][0] indicates the CATE for treatment_1, and the second element of  cate_x[0][0] indicates the CATE for treatment_2 ?

2. What does cate_x[1] & cate_x[2] mean ? I'm quite confused by this format here.

Thanks for helping out! I was looking thru the API doc in https://causalml.readthedocs.io/en/latest/causalml.html but still didn't get what the output means exactly.

**Comment by ppstacy** [comment]
Hi @Shiutang-Li thanks for using `CausalML`!  

Here I noticed that you used `return_components=True` in`fit_predict()` function, by doing this we will return the interim predicted outcome for treatment and control separately. It might be better to return the nested tuple results the following way so you will be more clear about the outputs. 

`te, dhat_cs, dhat_ts =  learner_x.fit_predict(X=train[features], treatment=train['Treatment'], y=train['Target'], return_components=True)`

`te`:  predictions of treatment effects for treatment_1 and treatment_2
`dhat_cs`: outcome predicitons for control of treatment_1 and treatment_2
`dhat_ts`: outcome predicitons for treatment of treatment_1 and treatment_2

X Learner uses `dhat_cs` and `dhat_ts` to calculate CATE,  you can reference the exact formulas [here](https://causalml.readthedocs.io/en/latest/methodology.html) for more details. Please let me know if this makes sense to you or if you have any questions. Thanks!

**Comment by Shiutang-Li** [comment]
Thanks @ppstacy  for your detailed explanations : )

**Comment by saiwing-yeung** [comment]
Hi @ppstacy, thank you too for the explanation. I have a follow up question. How is returned results ordered? Is it dependent on the label of the treatments? For example in the OP's case, based on `treatment_1` and `treatment_2`? And, say for some reason, `treatment_1` and `treatment_2` are instead coded as `treatment_b` and `treatment_a` and then we refitted, then the returned results will automatically reordered according to the new name?

**Comment by ppstacy** [comment]
Hi @saiwing-yeung yes, the returned results will be based on your input name of the different treatment labels. In terms of the order we sort it after get the labels as you can see in the following code:
```
        self.t_groups = np.unique(treatment[treatment != self.control_name])
        self.t_groups.sort()
        self._classes = {group: i for i, group in enumerate(self.t_groups)}
```
So you can use the `._classes` to get it as shown in this [example notebook](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb) line 73

**Comment by saiwing-yeung** [comment]
Awesome, thank you for the info!
