### ISSUE TITLE
Continuous Response Variable: P-values

### ISSUE THREAD

**Issue by soodimilanlouei** [uber/causalml#244]
I'm training a random forest model, where the response variable is continuous. When I look at one tree from the forest, the p-values are always NaN. Why is that?

**Comment by paullo0106** [comment]
Thanks for reaching out, are you using `UpliftRandomForestClassifier`? Currently, uplift tree only supports classfication, it's on the road map to cover regression use case in the future.

**Comment by soodimilanlouei** [comment]
Thanks for the response.
Yes, I'm using `UpliftRandomForestClassifier`. 
When I use `UpliftTreeClassifier` for the continuous response variable, it raises an error (the tree is empty).
However, interestingly, when I run `UpliftRandomForestClassifier`, it trains the model and I can plot the gain and lift graphs as well. I also can visualize one of the trees in the forest; however, p-values are always NaN. So, I assume I should not trust these results, right?
![image](https://user-images.githubusercontent.com/12864506/98297393-5360e280-1f82-11eb-9984-5a14d37166c0.png)

**Comment by paullo0106** [comment]
Correct, this is not from the accurate Regression tree implementation.

**Comment by soodimilanlouei** [comment]
In this [example](https://github.com/uber/causalml/blob/master/examples/feature_selection.ipynb), shouldn't the base learners for R-Learner be `RandomForestClassifier `instead of `RandomForestRegressor `since the response variable is binary (Conversion)?

**Comment by paullo0106** [comment]
I think you're right, thanks for flagging that! Will make changes to feature_selection.ipynb

**Comment by soodimilanlouei** [comment]
Another question that I have is regarding the arguments of  `BaseXClassifier` function. In this [link](https://github.com/uber/causalml/blob/6122f0b84f7dad938961e66d50222057f8c801da/causalml/inference/meta/xlearner.py#L559), it says that:

_"outcome_learner (optional): a model to estimate outcomes in both the control and treatment groups. Should be a regressor."_
_"effect_learner (optional): a model to estimate treatment effects in both the control and treatment groups. Should be a classifier."_

Shouldn't this be the other way around? outcome_learner to be a classifier and effect_learner to be a regressor?

**Comment by paullo0106** [comment]
Your points make sense to me that the docstring for parameters of `BaseXClassifier` needs some correction, [predict_proba()](https://github.com/uber/causalml/blob/6122f0b84f7dad938961e66d50222057f8c801da/causalml/inference/meta/xlearner.py#L670) invocation is for classfiers. @ppstacy @jeongyoonlee, or others, can you confirm that for an **X-Learner classifier**, the outcome learner (_M1 and M2_) is classifier and the effect learner (_M3 and M4_) is regressor?
 
<img width="341" alt="Screen Shot 2020-11-14 at 4 05 35 PM" src="https://user-images.githubusercontent.com/4966393/99159649-41bebf80-2693-11eb-9bbb-948514da8461.png">

**Comment by jeongyoonlee** [comment]
Thanks @soodimilanlouei and @paullo0106. Yes, in `BaseXClassifier`, `outcome_learner` should be a **classifier** while `effect_learner` should be a **regressor**. Please feel free to submit a PR. Thanks again!

**Comment by paullo0106** [comment]
the arguments documentation part was fixed in PR #251
