### ISSUE TITLE
Transformed Outcome methods

### ISSUE THREAD

**Issue by shaddyab** [uber/causalml#246]
Are there any plans to include Transformed Outcome algorithms in this package?

**Comment by ppstacy** [comment]
Hi @shaddyab thanks for using `CausalML` and bring this topic up. I don't think we have any plans right now. But we are open to anything for Causal Inference related algorithms. Do you already have something in mind or do you have any related papers or links to share with us? Thanks!

**Comment by shaddyab** [comment]
I know that the Transformed Outcome is already implemented in the [pylift](https://pylift.readthedocs.io/en/latest/introduction.html) python package.I was wondering if it will also be included here with some adjusted modifications.

I also found this paper that presents a comparison between different algorithms with emphasize on revenue uplift
[Response transformation and profit decomposition for revenue uplift modeling](https://www.sciencedirect.com/science/article/abs/pii/S0377221719309415)

**Comment by ppstacy** [comment]
Thanks @shaddyab for sharing those!

Maybe I am wrong, but currently the `predict()` function in CausalML returns the predictions of treatment effects which are continuous values for both classification (pylift) and regression problem (revenue uplift). So I don't think we need to transform the outcome. 

@jeongyoonlee @huigangchen @t-tte how do you guys think about it? Any outcome transfer method we should consider adding into the package?

**Comment by shaddyab** [comment]
@ppstacy , I agree that the current CausalML package already estimates the ATE; however, I thought it would be a useful  additional to this package, especially that the transformed outcome is an unbiased estimate of the treatment effect. Hence, it can be used as a target variable for model training (i.e., A single meta learner is needed).

**Comment by t-tte** [comment]
As far as I understand the distinction between transformed outcome methods and others, our [uplift tree methods](https://github.com/uber/causalml/tree/master/causalml/inference/tree) fall under the category. But let me know if you have some other definition in mind.

More generally, if there are specific algorithms out there that have promising results in experiments, we're of course always interested in learning about them.
