### ISSUE TITLE
X-Learner: Propensity scores for experimental data

### ISSUE THREAD

**Issue by shaddyab** [uber/causalml#255]
If I have results form experimental/historical uplift test where 70% of the population was **randomly** assigned to the treatment group and 30% **randomly** assigned to the control group and I am using a X-Learner do I still need to run a model (e.g., ElasticNetPropensityModel) to calculate the propensity scores or is it sufficient to provide an array with 0.7 as the propensity scores for all the provided samples?

Once the model is built using the 0.7 propensity score of the previous experimental data, what value should be provided to the x-learner to predict the ITE for a new campaign where the random propensity to treatment was not assigned yet? Is setting the propensity score to 0.5 to get a weighted average of the treatment effect a valid option?

**Comment by ppstacy** [comment]
Hi @shaddyab, base on my experience with experimental data I think it should be good to use 0.5 as the propensity score. Because users have an equal chance to be assigned into control or treatment no matter the test size.

**Comment by shaddyab** [comment]
@ppstacy, Thank you for taking the time to answer my question. I will experiment with this configuration.

**Comment by t-tte** [comment]
Given the original title of the question, I'd like to add that the R-learner relies more heavily on the propensity score, and it's a good practice to estimate the score even with data from a randomized experiment (see the discussion [here](https://github.com/uber/causalml/issues/70)).
