### ISSUE TITLE
Issue about ElasticNetPropensityModel

### ISSUE THREAD

**Issue by yling1105** [uber/causalml#261]
**Describe the bug**

I have two questions:
When I try to use fit_predict() to produce the propensity score array, it raised an error that:
_TypeError: clip() argument after * must be an iterable, not int_
The clipbounds is defined as (1e-3, 1 - 1e-3) in the class. Is there any problem with this?

**To Reproduce**

X: (2392, 8) np.matrix
t: (2392, ) np.array
pm = ElasticNetPropensityModel(5, random_state=1105)
ps = pm.fit_predict(X, t)

**Screenshots**
<img width="972" alt="Screen Shot 2020-11-19 at 10 41 49 AM" src="https://user-images.githubusercontent.com/41468691/99696076-e6564e00-2a53-11eb-8a6b-501fea279407.png">

**Environment (please complete the following information):**
 - OS: Ubantu
 - Python Version: 3.7.7

**Comment by shaddyab** [comment]
It appears to me that you provided the clip_bounds arg as an integer (i.e., 5) rather than a tuple.

**Comment by yling1105** [comment]
> It appears to me that you provided the clip_bounds arg as an integer (i.e., 5) rather than a tuple.

Thanks a lot for replying to me. After removing the arguments, it works. I referred to the tutorial:
<img width="457" alt="Screen Shot 2020-11-19 at 10 52 11 AM" src="https://user-images.githubusercontent.com/41468691/99697840-b6a84580-2a55-11eb-84ac-bc0a0672f247.png">
I wonder if there is no n_fold any more? Since if I put n_fold in the function, there is an error that:
TypeError: __init__() got an unexpected keyword argument 'n_fold'

**Comment by shaddyab** [comment]
Which version are you using?

**Comment by yling1105** [comment]
> Which version are you using?

causalml 0.9.0

**Comment by paullo0106** [comment]
Thanks for bringing this up, this seems to have something to do with changes in [one of the latest commits](https://github.com/uber/causalml/commit/c99ebc5d05a41c8384feaf7e3c144b2b1b65f826#diff-031f9743b66108fa0e8499556f97ae5755c443a0a31af89c89fa1c52a89d08bb). Requires a bit more check, @waltherg any suggestions here?

**Comment by paullo0106** [comment]
the above pull request should address this issue
