### ISSUE TITLE
do you have casual tree model?

### ISSUE THREAD

**Issue by cysjtu** [uber/causalml#263]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ppstacy** [comment]
Hi @cysjtu,

We do have the casual tree model under the tree API of inference [here](https://github.com/uber/causalml/tree/master/causalml/inference/tree). Please take a look. We also have an example notebook [here](https://github.com/uber/causalml/blob/master/examples/uplift_trees_with_synthetic_data.ipynb). Please take a look and let us know if you have any follow up questions. Thanks!

**Comment by Chengyingsjtu** [comment]
@ppstacy Can you create tree visualization for causal tree models like uplift tree models? Thanks!

**Comment by jeongyoonlee** [comment]
Closing this one and created a new issue #424 for @Chengyingsjtu's comment
