### ISSUE TITLE
Shapley and Partial Dependence Plots for Causal RF

### ISSUE THREAD

**Issue by soodimilanlouei** [uber/causalml#265]
Is there any way to plot the shap values for Causal RF class?
What about partial dependence plots?

**Comment by jeongyoonlee** [comment]
Yes. You can check out the causal tree example notebook, [`/examples/causal_trees_interpretation.ipynb`](https://github.com/uber/causalml/blob/master/examples/causal_trees_interpretation.ipynb), for shap value visualization for Causal Trees/RF.
