### ISSUE TITLE
UpliftRandomForrestClassifier exit codes of the joblib workers are {SIGKILL(-9)}

### ISSUE THREAD

**Issue by manojbalaji1** [uber/causalml#267]
**Describe the bug**
UpliftRandomForrestClassifier parallelized jobs gets killed by OS 

**To Reproduce**
Create a df with 2M rows and 400 columns,
initialize UpliftRandomForrestClassifier object set n_jobs=8 (since i am using a 8 vcpu, 64gb RAM machine)
UpliftRandomForrestClassifier object.fit on df

**Expected behavior**
/opt/conda/lib/python3.6/site-packages/joblib/externals/loky/backend/semaphore_tracker.py:74: UserWarning: semaphore_tracker: process died unexpectedly, relaunching.  Some semaphores might leak.
  warnings.warn('semaphore_tracker: process died unexpectedly, '
---------------------------------------------------------------------------
TerminatedWorkerError                     Traceback (most recent call last)
<ipython-input-46-d8463148ee1a> in <module>
      1 uplift_rf.fit(X_train.values, 
      2                  treatment=treatment[:X_train.shape[0]],
----> 3                  y=y_train.values)

/opt/conda/lib/python3.6/site-packages/causalml/inference/tree/models.py in fit(self, X, treatment, y)
   1272         self.uplift_forest = (
   1273             Parallel(n_jobs=self.n_jobs)
-> 1274             (delayed(self.bootstrap)(X, treatment, y, tree) for tree in self.uplift_forest)
   1275         )
   1276 

/opt/conda/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time

/opt/conda/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

/opt/conda/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

/opt/conda/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/opt/conda/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}

**Screenshots**

**Environment (please complete the following information):**
 - OS: centos
 - Python Version: 3.6
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): everything is same except scipy 1.4.0 version

**Additional context**

**Comment by paullo0106** [comment]
Looks like an out of memory error ([a similar case](https://stackoverflow.com/questions/20231491/random-forest-classifier-segmentation-fault)), would you mind trying:

- Reduce # of columns by using the [built-in Filter method](https://github.com/uber/causalml/blob/master/examples/feature_selection.ipynb) to select only top features
- Start with a smaller # of trees (maybe `n_estimators=3`) or only 1/3 of the rows

**Comment by manojbalaji1** [comment]
@paullo0106 I will definitely try this, but I think it's a known issue of Joblib.
Meanwhile,  one of the reason I saw the issue the first time is because n_jobs was not part of docstring, due to which I missed  giving a value for it and n_jobs=-1 has some issues of memory leakage in joblib. I have added this to docstring in this PR: https://github.com/uber/causalml/pull/266
 
can you please merge it so that people don't miss it the next time!!

**Comment by paullo0106** [comment]
Merged the PR, thanks for looking into it and contributing! I didn't know much about this issue in *Joblib*, do you have more info to share? Feel free to let us know if you have any proposed changes to address it
