### ISSUE TITLE
plot_shap_values having only one color

### ISSUE THREAD

**Issue by Shiutang-Li** [uber/causalml#268]
**Describe the bug**

In feature_interpretations_example.ipynb,
https://github.com/uber/causalml/blob/master/examples/feature_interpretations_example.ipynb
plot_shap_values() generates only one color.

However, for the feature plot in the SHAP package,
(https://github.com/slundberg/shap)
shap.summary_plot(shap_values, X) contains both red, blue, purple colored dots. These colors can help us identify the variable trends (a plot without colors is almost useless).

I check out the source codes but still don't get it why there's such error. Thanks for helping figure this out !

**To Reproduce**
**Expected behavior**
**Screenshots**
**Environment (please complete the following information):**
**Additional context**

N/A

**Comment by paullo0106** [comment]
Thanks for flagging this, @Shiutang-Li. This has been fixed in PR #269, examples in the mentioned notebook and [README](https://github.com/uber/causalml#meta-learner-feature-importances) are updated accordingly, too. Let me know if it works for you now.
