### ISSUE TITLE
Feature selection pd.qcut n_bins duplicate issue

### ISSUE THREAD

**Issue by manojbalaji1** [uber/causalml#270]
I just wanted to check what was the reason behind settings duplicate='raise' in filter using KL? One of the variable which was given as input had raised error due to duplicates in pd.qcuts, it is not a categorical variable

**Comment by manojbalaji1** [comment]
I can change it to drop duplicate edges as instead of raise, drop fixes this or rank the values then do qcut @paullo0106 what do you say?

**Comment by manojbalaji1** [comment]
@paullo0106 I tested with duplicates='drop', which seems to work for me and seems to solve the problem. If you are ok I will do the changes.

**Comment by paullo0106** [comment]
Thanks @manojbalaji1 , I haven't had a chance to take a closer look. Can you submit a PR and we can potentially have more input from other contributors?  Thank you
