### ISSUE TITLE
AUUC gives incorrect results when multiple models are scored

### ISSUE THREAD

**Issue by vaclavbelak** [uber/causalml#272]
**Describe the bug**
For some datasets, if the `auuc_score` is applied to results from multiple models, it returns wrong score for every second model.

**To Reproduce**
```
import pandas as pd
import numpy as np
from causalml.metrics import auuc_score

data = pd.read_csv('data/cumlift_bug.csv')

assert np.all([np.all(data['model1'] == data['model2']),
                        np.all(data['model2'] == data['model3']),
                        np.all(data['model3'] == data['model4'])])

auuc_score(criteo_test, outcome_col='conversion', treatment_col='treatment', treatment_effect_col=None)
```
Results into:
```
model1    1.214920
model2    1.208911
model3    1.214655
model4    1.208999
Random    0.470493
```

**Expected behavior**
The same AUUC for all models is expected here, since the predictions are all the same:

```
model1    1.214920
model2    1.214920
model3    1.214920
model4    1.214920
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9254281/102075741-fec54880-3e06-11eb-8fe7-18e9581558c3.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Python Version: 3.6
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==1.1.2`, `scikit-learn==0.23.2`, `cython==0.29.21`]

**Additional context**
See the attached archive with the data and a notebook reproducing the issue. At the end of the notebook, I include a modification to the `get_cumlift` which seems to resolve the problem.

[cumlift_bug.zip](https://github.com/uber/causalml/files/5688426/cumlift_bug.zip)

**Comment by vaclavbelak** [comment]
I have a fix in a separate branch, happy to share it in whatever way you prefer.

**Comment by jeongyoonlee** [comment]
Thanks for filing the issue, @vaclavbelak. Please submit a PR from your branch so that we can review and merge it.

**Comment by vaclavbelak** [comment]
@jeongyoonlee Sure, will be happy to do that, but I get 403 when trying to push my branch. Do I need some permissions to do so?

**Comment by jeongyoonlee** [comment]
You need to fork the repo, update it, then submit a cross repo PR. Please check out the instruction [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).
