### ISSUE TITLE
Unreproducible UpliftRandomForestClassifier

### ISSUE THREAD

**Issue by RuslanTs** [uber/causalml#275]
**Describe the bug**
UpliftRandomForestClassifier doesn't give the same results when runs with the same data and the same params (seed fixed). Because random seed in bootstrap is not fixed - it has to be the different realization of bootstrap.

**To Reproduce**
Run UpliftRandomForestClassifier several times with the same params and compare predicts

**Expected behavior**
Getting the same predicts

**Comment by paullo0106** [comment]
Reopening this, @RuslanTs might revisit fix in #274 later so we can merge the PR

**Comment by paullo0106** [comment]
@maurever thanks for reaching out and sharing your use case with H2O! Please stay tuned to @jeongyoonlee 's recent commit to #401

**Comment by jeongyoonlee** [comment]
Fixed in #422.
