### ISSUE TITLE
More digits in tree visualization prediction possible?

### ISSUE THREAD

**Issue by Julia0207** [uber/causalml#278]
Hi,

we work with the tree visualization of causalml. We train the uplift tree by **UpliftTreeClassifier()**, fit it using **uplift_model.fit()** and visualize the uplift tree by **uplift_tree_plot()**.
Is it possible to have more digits in the mean prediction of the treatment group (control group) within the visualization ?

Thanks and kind-regards,
Julia

**Comment by paullo0106** [comment]
Thanks for reaching out, Julia. Did you mean to increase the second decimal place for mean treatment and control displayed on the leaf nodes?

![image](https://user-images.githubusercontent.com/4966393/103969189-3f6c6500-511a-11eb-8a99-eaaf36de8cc1.png)

**Comment by Julia0207** [comment]
Yes, that is what I mean. :-)

**Comment by paullo0106** [comment]
@Julia0207 

The decimal point can be changed in `uplift_tree_plot()` function [here](https://github.com/uber/causalml/blob/master/causalml/inference/tree/plot.py#L84), for example, `lsY.append('%s:%.3f' % (szX, n))` would give us numbers to 3 decimal places, as shown in the attached. We can add an optional parameter in the function according to different user preferences.

Out of curiosity, Are you working on something that requires high precision of uplift calculations?

![uplift_tree](https://user-images.githubusercontent.com/4966393/105440649-c988f300-5c1b-11eb-9003-5411c79595fb.png)
