### ISSUE TITLE
Add smoothing factor to feature_selection/filters.py/_GetNodeSummary()

### ISSUE THREAD

**Issue by surajiyer** [uber/causalml#280]
We get a KeyError issue in feature_selection/filters.py L197-203 when certain (treatment, y_label) combinations do not occur naturally in the dataset, e.g., if we never see label=1 for "treatment1".

**Proposed change**
We can smooth label counts per treatment in _GetNodeSummary() by adding 1 for (treatment, label) combinations that do not occur naturally in the data. I have made a draft PR here: https://github.com/uber/causalml/pull/281 to fix this.

**Comment by paullo0106** [comment]
This was fixed in PR #281
