### ISSUE TITLE
Question: Calcluation of uplift score

### ISSUE THREAD

**Issue by Julia0207** [uber/causalml#284]
Hi,
how is the calculation for the uplift score? I thought that the uplfit score is equal to the CATE, but our visualized tree showed some cases where the predicted probability for Y=1 under the treatment group minus the predicted probabilty for Y=1 under the control group is not equal to the uplift score. 
Thank you very much for your help!
Best regards,
Julia

**Comment by paullo0106** [comment]
Thanks for reaching out, Julia. It might be related to the `n_reg` regularization parameter in [`tree_node_summary()`](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L820) function which is responsible for the underlying calculations. Let me know if this can explain the gap you spotted
