### ISSUE TITLE
Travis CI Build Failure

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#286]
**Describe the bug**
Travis CI build is failing: https://travis-ci.com/github/uber/causalml/builds/213726951

**To Reproduce**
Steps to reproduce the behavior: Start rebuilding.

**Expected behavior**
Completed without an error

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by jeongyoonlee** [comment]
Hi @paullo0106, last merge's build is failing. Could you please look into this?

**Comment by ppstacy** [comment]
Hi @jeongyoonlee and @paullo0106, I had this issue before when helping other people install causalml. It probably due to the newest version of `shap`. After I downgrade it to a lower version it can work
