### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by knail1** [uber/causalml#288]
**Describe the bug**

**To Reproduce**
I followed your instructions
1. git clone (you need to add this in your top readme)
2. pip install -r requirements...

during the install

ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.

this is an easy fix in the requirements.txt , just bringing it to your attention.
**Expected behavior**

install should complete without errors

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu] macos
 - Python Version: [e.g. 3.6, 3.7] 3.7.2
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`] whatever is in your requirements.txt (i'm installing in a venv)
 - 
**Additional context**

**Comment by ppstacy** [comment]
Hi @knail1 thanks for reporting this. I believe even with ERROR message from tensorflow we should be able to install `Causalml` right? Let me know if you have any other issues with installing. Thanks!

**Comment by knail1** [comment]
yes, i think so though I did update my requirements.txt to be strict to match the 2 versions in your error.

**Comment by knail1** [comment]
let me add that after fixing the above error, if you try to start any notebook, you get errors.
this is also an install issue with libomp, that you should document in your top level readme

example while using your notebook here"
http://localhost:8889/notebooks/examples/uplift_tree_visualization.ipynb

from causalml.dataset import make_uplift_classification
from causalml.inference.tree import UpliftTreeClassifier, UpliftRandomForestClassifier
from causalml.inference.tree import uplift_tree_string, uplift_tree_plot


---------------------------------------------------------------------------
XGBoostError                              Traceback (most recent call last)
<ipython-input-1-bfd10127fe9f> in <module>
----> 1 from causalml.dataset import make_uplift_classification
      2 from causalml.inference.tree import UpliftTreeClassifier, UpliftRandomForestClassifier
      3 from causalml.inference.tree import uplift_tree_string, uplift_tree_plot

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/dataset/__init__.py in <module>
      7 from .classification import make_uplift_classification
      8 
----> 9 from .synthetic import get_synthetic_preds, get_synthetic_preds_holdout
     10 from .synthetic import get_synthetic_summary, get_synthetic_summary_holdout
     11 from .synthetic import scatter_plot_summary, scatter_plot_summary_holdout

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/dataset/synthetic.py in <module>
      9 from sklearn.model_selection import train_test_split
     10 from sklearn.linear_model import LinearRegression
---> 11 from xgboost import XGBRegressor
     12 from scipy.stats import entropy
     13 import warnings

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/xgboost/__init__.py in <module>
      7 import os
      8 
----> 9 from .core import DMatrix, DeviceQuantileDMatrix, Booster
     10 from .training import train, cv
     11 from . import rabit  # noqa

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/xgboost/core.py in <module>
    172 
    173 # load the XGBoost library globally
--> 174 _LIB = _load_lib()
    175 
    176 

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/xgboost/core.py in _load_lib()
    163             '`brew install libomp` to install OpenMP runtime.\n' +
    164             '  * You are running 32-bit Python on a 64-bit OS\n' +
--> 165             'Error message(s): {}\n'.format(os_error_list))
    166     lib.XGBGetLastError.restype = ctypes.c_char_p
    167     lib.callback = _get_log_callback_func()

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Users/oansari/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Users/oansari/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']

**Comment by knail1** [comment]
once you fix the above, you run into another error!

you are allowing scikit learn versions which cause this error

from your requirements:
scikit-learn>=0.22.0

from scikit learn [documentation](https://scikit-learn.org/stable/auto_examples/preprocessing/plot_discretization_classification.html): the library was renamed from
sklearn.utils.testing
to
sklearn.utils._testing

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-bfd10127fe9f> in <module>
----> 1 from causalml.dataset import make_uplift_classification
      2 from causalml.inference.tree import UpliftTreeClassifier, UpliftRandomForestClassifier
      3 from causalml.inference.tree import uplift_tree_string, uplift_tree_plot

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/dataset/__init__.py in <module>
      7 from .classification import make_uplift_classification
      8 
----> 9 from .synthetic import get_synthetic_preds, get_synthetic_preds_holdout
     10 from .synthetic import get_synthetic_summary, get_synthetic_summary_holdout
     11 from .synthetic import scatter_plot_summary, scatter_plot_summary_holdout

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/dataset/synthetic.py in <module>
     14 
     15 from causalml.inference.meta import BaseXRegressor, BaseRRegressor, BaseSRegressor, BaseTRegressor
---> 16 from causalml.inference.tree import CausalTreeRegressor
     17 from causalml.propensity import ElasticNetPropensityModel
     18 from causalml.metrics import plot_gain, get_cumgain

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/inference/tree/__init__.py in <module>
----> 1 from .models import UpliftTreeClassifier, DecisionTree
      2 from .models import UpliftRandomForestClassifier
      3 from  .causaltree import CausalMSE, CausalTreeRegressor
      4 from .plot import uplift_tree_string, uplift_tree_plot
      5 from .utils import cat_group, cat_transform, cv_fold_index, cat_continuous, kpi_transform

~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/inference/tree/models.py in <module>
     19 import scipy.stats as stats
     20 import pandas as pd
---> 21 from sklearn.utils.testing import ignore_warnings
     22 from collections import defaultdict
     23 from joblib import Parallel, delayed

**ModuleNotFoundError: No module named 'sklearn.utils.testing'**

**Comment by knail1** [comment]
I had to update these two files and change to: **sklearn.utils._testing** 
and then the notebooks worked
vi ~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/inference/tree/models.py
i ~/Documents/marketing/src/causalml/venv/lib/python3.7/site-packages/causalml/inference/meta/tlearner.py

**Comment by jeongyoonlee** [comment]
The issue with the `scikit-learn==0.24` API update was addressed in #283, and will be shipped in the next release.

**Comment by knail1** [comment]
thank you. will you be updating your readme with additional instructions to avoid the install errors?

if so, i'll close this defect out. thanks for prompt response

**Comment by AlexYoung757** [comment]
does it only support tf 2.x？

**Comment by jeongyoonlee** [comment]
@knail1 At the time of new release, you should be able to install `causalml` by using `pip install causalml` in a clean environment. We may update README.md to recommend a clean `conda` environment in case of any installation issues.

@AlexYoung757 The only code that depends on `tensorflow` is `inference.nn.DragonNet`, which uses `keras` API. Therefore, I guess it would work fine with `tensorflow 1.x` as long as it is supported by `keras`.

**Comment by jeongyoonlee** [comment]
> The issue with the `scikit-learn==0.24` API update was addressed in #283, and will be shipped in the next release.

The fix was released in v0.10.0 on 2/19/2021. I will close this issue.
