### ISSUE TITLE
Treatment effect bound calculation doesn't match the provided reference

### ISSUE THREAD

**Issue by t-tte** [uber/causalml#30]
For example, the t-learner calculates the bounds for the estimated treatment effect as follows:

```
self.c_var = (y[~is_treatment] - self.model_mu_c.predict(X[~is_treatment])).var()
self.t_var = (y[is_treatment] - self.model_mu_t.predict(X[is_treatment])).var()

se = np.sqrt((
             self.t_var/prob_treatment + self.c_var/(1-prob_treatment) +
             (p * dhat_c + (1-p) * dhat_t).var()
       ) / X.shape[0])

te_lb = te - se * norm.ppf(1 - self.ate_alpha / 2)
te_ub = te + se * norm.ppf(1 - self.ate_alpha / 2)
```

However, this doesn't seem to match the referenced equation by [Woolridge and Imbens (2009)](https://www.nber.org/papers/w14251.pdf), which is:

<img width="577" alt="Screenshot 2019-08-15 at 12 41 03" src="https://user-images.githubusercontent.com/23464531/63089989-0c8c6480-bf5a-11e9-8d5a-4336c834676d.png">

The fix may be as simple as changing the reference.

**Comment by jeongyoonlee** [comment]
Per @huigangchen: 
> The reason is that the conditional variance takes the variations from the independent variables x_i away. So it is really the residual component of the variance. If we use the variance from the prediction it is really the variance from the independent variables.
