### ISSUE TITLE
Bin-based Filters for Variable Selection

### ISSUE THREAD

**Issue by soodimilanlouei** [uber/causalml#307]
My understanding is that bin-based methods for variable selection only work on continuous variables. Is that right?
When I run these methods on my data - which includes both continuous and binary variables -, the score for binary variables is always zero.

**Comment by manojbalaji1** [comment]
I think this also depends how 1's and 0's are distributed

**Comment by t-tte** [comment]
It's correct that the current implementation only works for continuous features because the method requires splitting the features into n_bins quantiles, which doesn't make sense for binary features. However, I think @zhenyuz0500 had ideas for extending the method to deal with categorical features.
