### ISSUE TITLE
Getting installation errors at numpy: ModuleNotFoundError: No module named 'numpy', RuntimeError: Python version >= 3.7 required.

### ISSUE THREAD

**Issue by troyshu** [uber/causalml#308]
**Describe the bug**
I get numpy-related errors when installing causalml with pip (`pip install causalml`), first in the stack trace (see screenshot) is a `ModuleNotFoundError: No module named 'numpy'` , then later there's a `RuntimeError: Python version >= 3.7 required.` in file `/var/folders/bm/lzyzg02n2vn5s_clvbqh826h0000gp/T/easy_install-cdnmlmyn/numpy-1.20.1/setup.py`. 

Is Python 3.6. no longer supported? I actually need causalml on some production systems that run Python 3.6, and I hadn't run into this error until the past week or so. 

**To Reproduce**
- using Python 3.6.14
- create a new Python virtual environment
- `pip install causalml`
 
I also want to pin causalml==0.6.0, the same errors above occur when installing causalml 0.6.0.

**Expected behavior**
causalml to install without any errors.

**Screenshots**

Error stack trace: 
![image](https://user-images.githubusercontent.com/1057286/109563699-234bcb00-7aae-11eb-8344-d08863c5d90a.png)
![image](https://user-images.githubusercontent.com/1057286/109563736-2cd53300-7aae-11eb-9b5d-893ea5963b30.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Python Version: 3.6.13
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): N/A, am just running `pip install causalml` in a new Python 3.6.13 virtualenv

**Comment by ppstacy** [comment]
I am currently using python 3.6 and don't have any issues. Do you mind install dependencies first by `pip install -r requirements.txt`?

**Comment by troyshu** [comment]
Ok yeah, installing the dependencies first resolved the error, I missed that. As a test I actually just did `pip install numpy==1.18.0` (to satisfy the numpy dependency version range in [requirements.txt](https://github.com/uber/causalml/blob/master/requirements.txt#L3)) because the error message had to do with numpy, and that worked too.

I'm a Python package newb, but why is installing the dependencies manually even required at all? It seems like a clunky process: 

1) clone this `causalml` repo
2) activate desired virtualenv
3) run `pip install -r causalml/requirements.txt`
4) then run `pip install causalml`

Seems like `pip install causalml` should just work, like it does for other packages.

Is the solve just adding a max version for `numpy` to [`setup.py`](https://github.com/uber/causalml/blob/master/setup.py#L53) to match the max version for numpy in [`requirements.txt`](https://github.com/uber/causalml/blob/master/requirements.txt#L3)?

**Comment by ppstacy** [comment]
Cool, glad that you are able to solve it. So I will close this issue.

For the setup.py questions, I found some discussion [here](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py) that might be helpful: 

> **setup.py** should declare the loosest possible dependency versions that are still workable. Its job is to say what a particular package can work with.
> **requirements.txt** is a deployment manifest that defines an entire installation job, and shouldn't be thought of as tied to any one package. Its job is to declare an exhaustive list of all the necessary packages to make a deployment work.
> 
> Because these two things have such different content and reasons for existing, it's not feasible to simply copy one into the other.

**Comment by troyshu** [comment]
Hi @ppstacy, thank you for that discussion, helpful. 

I know that there may be constraints to developing `causalml` that I as a package user am not aware of, but just wanted to reiterate my point that I think that the current installation process (for package _users_ not package developers) is a bit cumbersome. If I'm on Python 3.6, running `pip install causalml` should just work, especially in an empty virtualenv, like it does for all other packages like `pandas`, even `numpy` itself. The fact that one has to install the dependencies for causalml first before pip installing causalml makes it harder to use for not only analysis but also for production systems. Just pointing out the ideal installation from a user's perspective, but I don't have a solution.
