### ISSUE TITLE
R-Learner raises AttributeError.

### ISSUE THREAD

**Issue by soodimilanlouei** [uber/causalml#313]
I have a binary outcome and I am able to fit all meta-learners, except the R-Learner.

The code that I'm running:

`rlearner = BaseRClassifier(outcome_learner = RandomForestClassifier(), effect_learner  = RandomForestRegressor(),
    control_name='control')`

It raises this error:

`AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'`

I am using causalml package version 0.10.0.

**Comment by paullo0106** [comment]
@soodimilanlouei Do you mind sharing more code? Not sure that line alone would give the error as it only initialize few models. `RandomForestClassifier` object should have `estimators_ ` attribute once it's trained, but it's not used during object initialization.

![causalml_debug](https://user-images.githubusercontent.com/4966393/111852146-237fff00-88d3-11eb-9aa2-806e93a33342.png)

**Comment by paullo0106** [comment]
![Screen Shot 2021-03-19 at 5 19 38 PM](https://user-images.githubusercontent.com/4966393/111853223-50361580-88d7-11eb-8061-715b13e58c7b.png)

**Comment by GiuliaMassimetti** [comment]
Hello, I am experiencing the same problem. In my case, it is coming from these lines in the initialization of `BaseRLearner`:
```
self.model_mu = outcome_learner if outcome_learner else deepcopy(learner)
self.model_tau = effect_learner if outcome_learner else deepcopy(learner)
```
If an `outcome_learner` is specified, then `if outcome_learner` checks the length of `estimators_` and therefore it raises an error:
```
AttributeError                            Traceback (most recent call last)

<ipython-input-4-8531a7969f42> in <module>
     21 
     22 
---> 23 learner_r = BaseRClassifier(outcome_learner=RandomForestClassifier(), effect_learner=RandomForestRegressor())

~/uplift-memo/venv/lib/python3.8/site-packages/causalml/inference/meta/rlearner.py in __init__(self, outcome_learner, effect_learner, propensity_learner, ate_alpha, control_name, n_fold, random_state)
    325             random_state (int or RandomState, optional): a seed (int) or random number generator (RandomState)
    326         """
--> 327         super().__init__(
    328             learner=None,
    329             outcome_learner=outcome_learner,

~/uplift-memo/venv/lib/python3.8/site-packages/causalml/inference/meta/rlearner.py in __init__(self, learner, outcome_learner, effect_learner, propensity_learner, ate_alpha, control_name, n_fold, random_state)
     52         assert propensity_learner is not None
     53 
---> 54         self.model_mu = outcome_learner if outcome_learner else deepcopy(learner)
     55         self.model_tau = effect_learner if outcome_learner else deepcopy(learner)
     56         self.model_p = propensity_learner

~/uplift-memo/venv/lib/python3.8/site-packages/sklearn/ensemble/_base.py in __len__(self)
    162     def __len__(self):
    163         """Return the number of estimators in the ensemble."""
--> 164         return len(self.estimators_)
    165 
    166     def __getitem__(self, index):

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'
```
It could be that the issue is related to the version of scikit-learn that I'm using (0.24.1), but I'm not sure.

Maybe this could be solved by slightly modifying the lines above?
```
self.model_mu = outcome_learner if outcome_learner != None else deepcopy(learner)
self.model_tau = effect_learner if outcome_learner != None else deepcopy(learner)
```

**Comment by paullo0106** [comment]
Good catch, thanks @GiuliaMassimetti !  My testing environment was few commits behind so didn't detect this properly.
#320 is to address this issue
