### ISSUE TITLE
uplift_trees_with_synthetic_data demo error

### ISSUE THREAD

**Issue by iSawyer** [uber/causalml#322]
can not run
uplift_model.fit(df_train[x_names].values,
                 treatment=df_train['treatment_group_key'].values,
                 y=df_train['conversion'].values)

![image](https://user-images.githubusercontent.com/6329581/115139740-27d04100-a066-11eb-893f-f09affde5fda.png)

**Comment by paullo0106** [comment]
Thanks for reaching out, @iSawyer . Can you share more code including how you initiate `UpliftRandomForestClassifier()`? I'm curious because `evaluationFunction(currentNodeSummary, control_name=self.control_name)` is not supposed to be invoked  when evaluationFunction is CTS, according to the [code here](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L897)

**Comment by iSawyer** [comment]
> Thanks for reaching out, @iSawyer . Can you share more code including how you initiate `UpliftRandomForestClassifier()`? I'm curious because `evaluationFunction(currentNodeSummary, control_name=self.control_name)` is not supposed to be invoked when evaluationFunction is CTS, according to the [code here](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L897)

execute demo code step by step


import numpy as np
import pandas as pd
from causalml.dataset import make_uplift_classification
from causalml.inference.tree import UpliftRandomForestClassifier
from causalml.metrics import plot_gain
from sklearn.model_selection import train_test_split

df, x_names = make_uplift_classification()
df.head(50)
  # Look at the conversion rate and sample size in each group
df.pivot_table(values='conversion',
               index='treatment_group_key',
               aggfunc=[np.mean, np.size],
               margins=True)
df_train, df_test = train_test_split(df, test_size=0.2, random_state=111)
uplift_model = UpliftRandomForestClassifier(control_name='control')
uplift_model.fit(df_train[x_names].values,
                 treatment=df_train['treatment_group_key'].values,
                 y=df_train['conversion'].values)

![image](https://user-images.githubusercontent.com/6329581/115192750-d1bed480-a11d-11eb-8952-93b1887a7f93.png)

**Comment by paullo0106** [comment]
hmm...I can't reproduce the error, as shown in the attached. Is your version 0.10.0? Do you mind trying if you will still be getting some errors when explicitly specifying `evaluationFunction` as `KL`, `ED`, or `Chi`  ? `uplift_model = UpliftRandomForestClassifier(control_name='control', evaluationFunction='KL')`

<img width="794" alt="uplift_issue322" src="https://user-images.githubusercontent.com/4966393/115306855-447b8000-a11d-11eb-9eaa-9e25f4a7e229.png">

**Comment by iSawyer** [comment]
my version is 0.10.0
it works when specifying evaluationFunction like this
`uplift_model = UpliftRandomForestClassifier(control_name='control',evaluationFunction='KL')
`

**Comment by paullo0106** [comment]
@iSawyer hmm...good to know it at least works when you specify the evaluationFunction, I'm trying to verify the problem in a new environment on Google Colab where we can collaborate on. Let me know if you still see this issue when using just `UpliftRandomForestClassifier(control_name='control')`
Link: https://colab.research.google.com/drive/1CReURWnYzT3_vN3k54ioY_sJGhdTS7a3

**Comment by 00helloworld** [comment]
UpliftRandomForestClassifier(control_name='control') 
works, Thanks
