### ISSUE TITLE
Issue while creating a bootstrap sample when calculating ATE.

### ISSUE THREAD

**Issue by kushmp** [uber/causalml#329]
While using the function learner_t.estimate_ate its not converting the dataframe supplied in X,treatment and y into numpy.
You already have a function to convert pd to np and have used it while calculating the CATE, it will be helpful to include the line into ATE estimator as well.

**Comment by jeongyoonlee** [comment]
Thanks for reporting the issue, @kushmp. This issue has been fixed in #333 as proposed. Thanks!
