### ISSUE TITLE
ModuleNotFoundError: No module named 'causalml'

### ISSUE THREAD

**Issue by sneakybeaky18** [uber/causalml#330]
Hello! When i try to import causalml i get this error:
"ModuleNotFoundError: No module named 'causalml'"

I just go to the noteebok and trying to import this:

"
from IPython.display import Image
from causalml.inference.tree import UpliftTreeClassifier, UpliftRandomForestClassifier
from causalml.inference.tree import uplift_tree_string, uplift_tree_plot
"

Then i got this error. 

I dont know what actually wrong, because when i type:
'
import causalml
'
I dont see any error

I already try to install it like are conda env, and install from source. Everything installed fine. And i already saw this issue: (https://github.com/uber/causalml/issues/148#) and this doesnt help me :( 

I dont know what can gone wrong.. 

Screens:
https://i.imgur.com/VgQGLif.jpeg , https://i.imgur.com/J4otlOg.jpeg 

**Environment (please complete the following information):**
 - Windows 10 
 - Python Version: 3.7
 - 
 My pip packages:

absl-py                 0.12.0
astunparse              1.6.3
cachetools              4.2.2
causalml                0.10.0
certifi                 2020.12.5
chardet                 4.0.0
cycler                  0.10.0
Cython                  0.29.23
dill                    0.3.3
future                  0.18.2
gast                    0.3.3
google-auth             1.30.0
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
graphviz                0.16
grpcio                  1.37.1
h5py                    2.10.0
idna                    2.10
importlib-metadata      4.0.1
joblib                  1.0.1
Keras                   2.4.3
Keras-Preprocessing     1.1.2
kiwisolver              1.3.1
lightgbm                3.2.1
llvmlite                0.36.0
Markdown                3.3.4
matplotlib              3.4.2
numba                   0.53.1
numpy                   1.18.5
oauthlib                3.1.0
opt-einsum              3.3.0
packaging               20.9
pandas                  1.1.5
patsy                   0.5.1
Pillow                  8.2.0
pip                     21.1.1
progressbar2            3.53.1
protobuf                3.17.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pydotplus               2.0.2
pygam                   0.8.0
pyparsing               2.4.7
pyro-api                0.1.2
pyro-ppl                1.6.0
python-dateutil         2.8.1
python-utils            2.5.6
pytz                    2021.1
PyYAML                  5.4.1
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-learn            0.24.2
scikit-uplift           0.3.2
scipy                   1.4.1
seaborn                 0.11.1
setuptools              56.2.0
shap                    0.37.0
six                     1.16.0
slicer                  0.0.3
statsmodels             0.12.2
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.3.2
tensorflow-estimator    2.3.0
termcolor               1.1.0
threadpoolctl           2.1.0
torch                   1.8.1
tqdm                    4.60.0
typing-extensions       3.10.0.0
urllib3                 1.26.4
Werkzeug                2.0.0
wheel                   0.36.2
wrapt                   1.12.1
xgboost                 1.4.1
zipp                    3.4.1

Conda packages:

absl-py                   0.12.0                   pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
ca-certificates           2021.4.13            haa95532_1
cachetools                4.2.1                    pypi_0    pypi
causalml                  0.10.0                   pypi_0    pypi
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  5.5                      pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
decorator                 5.0.7                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-auth               1.29.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.37.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 5.5.3                    pypi_0    pypi
ipython                   7.22.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-console           6.4.0                    pypi_0    pypi
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lightgbm                  3.2.1                    pypi_0    pypi
llvmlite                  0.36.0                   pypi_0    pypi
lxml                      4.6.3                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.4.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
nbclient                  0.5.3                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
nest-asyncio              1.5.1                    pypi_0    pypi
notebook                  6.3.0                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.0.1           py38haa95532_0
pluggy                    0.13.1                   pypi_0    pypi
progressbar2              3.53.1                   pypi_0    pypi
prometheus-client         0.10.1                   pypi_0    pypi
prompt-toolkit            3.0.18                   pypi_0    pypi
protobuf                  3.15.8                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.10.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pydotplus                 2.0.2                    pypi_0    pypi
pygam                     0.8.0                    pypi_0    pypi
pygments                  2.8.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.6.0                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pytest                    6.2.3                    pypi_0    pypi
pytest-cov                2.11.1                   pypi_0    pypi
python                    3.8.8                hdbf39b2_5
python-dateutil           2.8.1                    pypi_0    pypi
python-graphviz           0.16                     pypi_0    pypi
python-utils              2.5.6                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pywinpty                  1.0.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
qtconsole                 5.0.3                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                52.0.0           py38haa95532_0
shap                      0.37.0                   pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
slicer                    0.0.3                    pypi_0    pypi
sqlite                    3.35.4               h2bbff1b_0
statsmodels               0.12.2                   pypi_0    pypi
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.3.2                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
torch                     1.8.1                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.60.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2                      py38_0
wrapt                     1.12.1                   pypi_0    pypi
xgboost                   1.4.1                    pypi_0    pypi

And thanks for this great lib what really help in DS, i hope it will start work for me soon :d

**Comment by sneakybeaky18** [comment]
I will try to install it from notebook, mb it will help me 
![image](https://user-images.githubusercontent.com/58666088/118105937-b924a000-b3e5-11eb-9191-0865e083c44d.png)

**Comment by sneakybeaky18** [comment]
https://i.imgur.com/ee662RA.jpg its still installing :|

**Comment by jeongyoonlee** [comment]
It sounds like your Jupyter notebook was not started from the virtual environment you installed `causalml` in.

You can manually add the virtual environment to Jupyter notebook as a "kernel" as follows:
```
conda activate causalml-py38
pip install ipykernel
python -m ipykernel install --user --name causalml-py38 --display-name "Python 3.8 (causalml)"
```

Then, on your Jupyter notebook (you may need to restart the kernel), you can choose the "Python 3.8 (causalml)" kernel from "Kernel" -> "Change kernel".

Please let me know if it works.

**Comment by sneakybeaky18** [comment]
> It sounds like your Jupyter notebook was not started from the virtual environment you installed `causalml` in.
> 
> You can manually add the virtual environment to Jupyter notebook as a "kernel" as follows:
> 
> ```
> conda activate causalml-py38
> pip install ipykernel
> python -m ipykernel install --user --name causalml-py38 --display-name "Python 3.8 (causalml)"
> ```
> 
> Then, on your Jupyter notebook (you may need to restart the kernel), you can choose the "Python 3.8 (causalml)" kernel from "Kernel" -> "Change kernel".
> 
> Please let me know if it works.

Hello! Thanks for the quick answer :) I try this, but error dissapeared after installion from notebook (it took about are hour): https://i.imgur.com/AtN7P2M.jpg

but btw i got another mistake xD https://i.imgur.com/1sbcPmY.jpeg but i guess it will be so easy to fix now. I hope this thread will help for someone who google same issue

**Comment by sneakybeaky18** [comment]
After installing shap i got this error: https://i.imgur.com/0agcLuh.jpeg

**Comment by sneakybeaky18** [comment]
After installing last two packages it clearly work now :) https://i.imgur.com/7semFqd.jpg
