### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by BenjaminVermeulen** [uber/causalml#331]
Hello,

I am replicating the documentation example on Average Treatment Effect as seen here: https://github.com/uber/causalml.

my X is defined as a single column vector (example: [0.1, 0.2, 0.6, 0.9]
treatment is defined as a single column : [0.01, 1.2, 0.9, 0.05]
Y is defined a single column from a df : [2, 1.7, 3.8, 2.2]

lr = LRSRegressor()
te, lb, ub = lr.estimate_ate(X, treatment, y)
print('Average Treatment Effect (Linear Regression): {:.2f} ({:.2f}, {:.2f})'.format(te[0], lb[0], ub[0]))

When executing the above code, i receive an "Assertion error: Control group level 0 not found in treatment vector"

Do you have any advice on how i can solve this? Thank you !!

**Comment by paullo0106** [comment]
@BenjaminVermeulen Thanks for reaching out, like other learners in CausalML, LRSRegressor's [estimate_ate()](https://causalml.readthedocs.io/en/latest/causalml.html#causalml.inference.meta.BaseSLearner) takes `X`, `treatment`, `Y` in format of *np.array*, or *pd.Dataframe* (for `X`) and *pd.Series* (for `treatment` and `Y`). Other than that, `treatment` is supposed to be a list of 0 and 1 where 0 indicates control and 1 indicates treatment group. 

You might want to check some example dataset generated from `synthetic_data()` in our examples for the data format. As a quick test, below should work for a dataset you specified with only one covariate:

```
X = np.array([0.1, 0.2, 0.6, 0.9]).reshape((-1,1))
treatment = np.array([0, 1, 0, 1])
y = np.array([2, 1.7, 3.8, 2.2])

lr.estimate_ate(X, treatment,  y)
```
