### ISSUE TITLE
Random uplift score in UpliftRandomForestClassifier and Qini coeficient

### ISSUE THREAD

**Issue by maurever** [uber/causalml#332]
Hi!

I am studying your implementation `UpliftRandomForestClassifier`.

When I am using `plot_qini`, `plot_lift`, or `plot_gain` in the resulting graph, the Random uplift is computed by averaging some random uplift distributions. 

I would like to compute Qini coeficient metric, which is: 

_Q— the more general qini measure.Although the q0 measure is a useful directanalogue of gini for binary outcomes, the more generally useful measure is the unscaled qini measure Q.  **This is defined simply as the area between the actual incremental gains curve in question and the diagonal corresponding to random targeting**.  This is scaled only to remove dependence on the population size N, dividing by N2, where necessary._ (Real-World Uplift Modelling with Significance-Based Uplift Trees, Radcliffe & Surry, https://stochasticsolutions.com/pdf/sig-based-up-trees.pdf)

However Radcliffe & Surry compute random targeting differently than your implementation. Radcliffe & Surry compute random uplift as diagonal from zero to overall gain uplift:

![uplift](https://user-images.githubusercontent.com/11465784/118486062-77636480-b719-11eb-9a3b-ec07eba36994.png)

**My questions are:**
1. From which source comes your implementation of random targeting?
2. Are you going to implement Qini coeficient or Gini coeficient metrics calculation to `UpliftRandomForestClassifier`?

Thank you!

**Comment by t-tte** [comment]
Hi @maurever

Thanks for the question. If the sample size isn't very small, the way in which we calculate random targeting (by generating random CATEs) should correspond to Radcliffe & Surry's approach of drawing the diagonal from zero to ATE. There will be some variation if you're dealing with smaller samples.

**Comment by maurever** [comment]
Thank you for your reply!
