### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by erkutaykutlug** [uber/causalml#338]
**Describe the bug**
New installation using conda env file `envs/environment-py38.yml` is giving the following error. Probably from similar causes in the [open issue 305](https://github.com/uber/causalml/issues/305#issue-813604527)

The error goes away when numpy is upgraded to 1.20, but that raises incompatibility warning with tensorflow 2.3.2.

**To Reproduce**
After clean install run `examples/uplift_tree_visualization.ipynb`

**Screenshots**
```
from causalml.dataset import synthetic_data

 1 from .models import UpliftTreeClassifier, DecisionTree
      2 from .models import UpliftRandomForestClassifier
----> 3 from  .causaltree import CausalMSE, CausalTreeRegressor
      4 from .plot import uplift_tree_string, uplift_tree_plot
      5 from .utils import cat_group, cat_transform, cv_fold_index, cat_continuous, kpi_transform

__init__.pxd in init causalml.inference.tree.causaltree()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
**Environment:**
 - OS: Ubuntu 18.04
 - Python Version: 3.8
 - Versions of Major Dependencies 
     clean conda env install using envs/environment-py38.yml 
 - 
The error 
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

**Comment by yiming-sun-stat** [comment]
I did not find tensorflow in requirements.txt but pip install causalml still automatically install tensorflow why?

**Comment by ras44** [comment]
I still get the same error, even when creating a new conda env following the instructions in the README.md :

```
$ git clone https://github.com/uber/causalml.git
$ cd causalml/envs/
$ conda env create -f environment-py38.yml	# for the virtual environment with Python 3.8 and CausalML
$ conda activate causalml-py38
(causalml-py38)
```
When I do the above, and then open the [example ](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb) in jupyter lab using the causalml-py38 kernel, I get the error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe
```
