### ISSUE TITLE
How to save an uplift model?

### ISSUE THREAD

**Issue by XiaohanYa** [uber/causalml#342]
Hi,

Thank you developing this useful tool!!

I'm a beginner in causal inference and I am curious about how to save an uplift model. I tried pickle but failed. The error message says that "TypeError: can't pickle _thread._local objects". Thus, I'm wondering if there is any other way to save a model. Many thanks.

XH

**Comment by jeongyoonlee** [comment]
You can use `joblib` to save `causalml` models. `joblib` works better with Python objects with large `numpy` arrays/matrix. Here is an example notebook: https://colab.research.google.com/drive/1ud45oYCLFo6mWLDnK_uKpdQ9M7Oy5b7i?usp=sharing
