### ISSUE TITLE
Typo Issue in the  def _obj_func_midp(self, data, treatment, outcome) Function 

### ISSUE THREAD

**Issue by aborundiya** [uber/causalml#344]
**Describe the bug**
        pr_y0_w1 : float
            The probability of no conversion **_fiven_** treatment assignment
            (1 - pr_y1_w1).

There is a typo issue , "Fiven" instead of "Given" 

**To Reproduce**
Click on Source link to see the functional code 

**Expected behavior**
        pr_y0_w1 : float
            The probability of no conversion given  treatment assignment
            (1 - pr_y1_w1).

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by jeongyoonlee** [comment]
Thanks for filing the issue, @aborundiya. Could you please specify which source code file has the typo? It'd be better if you submit PR directly. Otherwise, I can fix it as well. Thanks!

**Comment by jeongyoonlee** [comment]
Found it, and submitted PR to fix it.

**Comment by aborundiya** [comment]
@jeongyoonlee thanks for recommending and will submit PR from next time :)
