### ISSUE TITLE
Causal ML with tensorflow installation

### ISSUE THREAD

**Issue by arkadaw9** [uber/causalml#350]
Hi, 
I have been trying to install the causal ML library with the tensorflow to use the DragonNet. I followed the instructions proved below:
```$ git clone https://github.com/uber/causalml.git
$ cd causalml
$ pip install -r requirements-tf.txt
$ pip install causalml[tf]
$ pip install -U numpy
```
However, after installation I am unable to access the causalml.inference.tf module.
![image](https://user-images.githubusercontent.com/56458648/121440753-5ddec280-c93d-11eb-9b0a-67476a28af2f.png)

Thanks.

**Comment by jeongyoonlee** [comment]
It's because latest PR (#343) hasn't been published to PyPI yet. To use latest master, you can install `causalml` from the GitHub repo directly.
