### ISSUE TITLE
Clarification on UpliftTreeClassifier predict

### ISSUE THREAD

**Issue by BrianMiner** [uber/causalml#353]
I am running UpliftTreeClassifier and predicting 5 values using the full output

I cant figure out what the outputs are at index 2 and 3. The 0 and 1 index values are the max of ones below. 

For example, what do [0.026976378951772052, 0.01385651743943539] represent - are these the response rates of the treatment and control (in what order) and how do these relate to 

'test': [0.061618]
'control': [0.034642]

![image](https://user-images.githubusercontent.com/8807554/122104583-ce765b00-cde5-11eb-9cfb-5e96f9997f89.png)

**Comment by paullo0106** [comment]
One enhancement we'll need is to correct the [documentation](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L483) of `UpliftTreeClassifier's predict()` function, or to unify the return in a DataFrame format as what we have in  `UpliftRandomForestClassifier` (code [here](https://github.com/uber/causalml/blob/master/causalml/inference/tree/models.py#L1362))

**Comment by BrianMiner** [comment]
Yeah. I closed the issue because I figured out the "mystery" entries [0.026976378951772052, 0.01385651743943539] is the CATE for treatment - control and the p-value(!)
