### ISSUE TITLE
Add tree visualization for CausalTreeRegressor

### ISSUE THREAD

**Issue by glukhove** [uber/causalml#357]
I noticed that it is not possible to visualize [CausalTreeRegressor](https://github.com/uber/causalml/blob/master/causalml/inference/tree/causaltree.pyx#L202) results as we can do for UpliftTreeClassifier. For example, I'd like to use **uplift_tree_plot()** method.

Do you think it could be supported in one of the next releases?

**Comment by paullo0106** [comment]
decision tree style visualization is provided by @alexander-pv 's PR #583 - closing the issue now : )
