### ISSUE TITLE
PIP installation error on Windows

### ISSUE THREAD

**Issue by novalearn** [uber/causalml#36]
Below is the pip install error:

 C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\include" /Tccausalml/inference/tree/causaltree.c /Fobuild\temp.win-amd64-3.7\Release\causalml/inference/tree/causaltree.obj -O3
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    causaltree.c
    C:\ProgramData\Anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by novalearn** [comment]
As mentioned on that SO post, install Windows 10 SDK solved the problem for me.
More specifically, here are what I have installed: Visual Studio Build Tools 2019 with MSVC, windows 10 SDK, CMake.

**Comment by jeongyoonlee** [comment]
Thanks for reporting the result back. Glad to hear that you were able to resolve it. Please try out causalml and let us know what you think. :)
