### ISSUE TITLE
Bug in synthetic data set: mechanism 2

### ISSUE THREAD

**Issue by jroessler** [uber/causalml#361]
**Describe the bug**
As you describe correctly [here](https://causalml.readthedocs.io/en/latest/validation.html#mechanism-2), the baseline main effect b* of the randomized trial (Setup B) in Nie and Wager (2020) is the following: 

b*(X) = max{Xi1 +Xi2,Xi3,0}+max{Xi4 +Xi5,0}

However, in your implementation, you define b* as follows:
`b = np.maximum(np.repeat(0.0, n), X[:, 0] + X[:, 1] + X[:, 2]) + np.maximum(np.repeat(0.0, n), X[:, 3] + X[:, 4]) `

Thus, your implementation of b*(X) is: 
max{Xi1 +Xi2 **+ Xi3**,0} + max{Xi4 +Xi5,0} but it should be 
max{Xi1 +Xi2 **, Xi3**,0} + max{Xi4 +Xi5,0}

If that is indeed a bug, I would like to submit a merge request.

**Comment by jeongyoonlee** [comment]
Thanks, @jroessler, for filing the issue. It indeed looks like a bug. Please feel free to submit a PR.
