### ISSUE TITLE
feature importance in Uplift Tree Classifier compared to leaf nodes

### ISSUE THREAD

**Issue by ZeyuJin** [uber/causalml#362]
Hi all,

I am running the example of "one control + one treatment" for uplift classification tree. The visualization of the uplift tree is plotted as followed: 
![image](https://user-images.githubusercontent.com/8068029/126452132-8c5de289-9c2f-4d9b-91a8-5974b5233992.png)
There are totally 4 features to diverge in the tree map. 

However, when I plot the feature importance using "**uplift_model.feature_importance_**", there are 10 sorted features in the map and 6 extra features that are not shown in the tree map. 

![image](https://user-images.githubusercontent.com/8068029/126453021-8574d6a9-306f-4531-ab20-22d55e05b70a.png)

I am wondering how to understand such a big difference between "feature_importance_" function and uplift tree node results? I am more convinced by features shown in the leaf nodes instead of sorted single feature importances.

Thanks,

**Comment by paullo0106** [comment]
Thanks for reporting this, @ZeyuJin. I'm testing my fix, will submit a PR soon.

**Comment by paullo0106** [comment]
should be fixed now with PR #372!
