### ISSUE TITLE
Failure when install causal[ml] in macOS

### ISSUE THREAD

**Issue by feiwuu638** [uber/causalml#364]
I tried to install causalml[tf] by typing "pip install causalml[tf]" in Mac shell, but it failed with warning:"zsh: no matches found: causal[ml]". I feel  like something is wrong with the character "[]", but I don't know how to solve it.

**Comment by paullo0106** [comment]
#343 which has the support of making tensorflow dependencies optional is not yet on PyPI, we plan to publish it with v0.11 release by next week. I suspect that might have caused the issue if you are not installing from git. Can you try `pip install "causalml[tf] @ git+https://github.com/uber/causalml"` and let us know if it works? Thanks!

**Comment by feiwuu638** [comment]
@ paullo0106
Thank you for your help. I put "causalml[tf]" in a single requirements.txt and pip install it, then it works. But when I'm installing the causalml without [tf], TensorFlow will still be installed automatically with multiple versions. Though causalml can work, it is still strange.
Looking forward to the new version!
