### ISSUE TITLE
Can upliftTreeClassifier be used for regression?

### ISSUE THREAD

**Issue by feiwuu638** [uber/causalml#368]
I wonder whether the upliftTreeClassifier can be used for regression where the conversion/responses are continuous values? 

I replaced the column 'conversion' of the synthetic dataset uplift_classification with continuous values and used upliftTreeClassifier to fit the dataset. The model can be fitted and predictions can be output, but I'm not sure whether the results made sense.

**Comment by paullo0106** [comment]
@feiwuu638 Thanks for reaching out, for regression problem, you can use our [CausalTreeRegressor](https://github.com/uber/causalml/blob/master/causalml/inference/tree/causaltree.pyx#L202). One thing we can improve is to add a bit more documentation and maybe also example notebook for this.

could be like this to use it
```
from causalml.inference.tree import CausalTreeRegressor
causal_tree_model = CausalTreeRegressor(max_depth = 10, control_name='control', random_state=2021)
te, te_lower, te_upper = causal_tree_model.fit_predict(x, treatment, y)
```

@jeongyoonlee for any additional input on this  :)

**Comment by feiwuu638** [comment]
@paullo0106 Thanks for your kind support. I will try the CausalTreeRegressor API and see whether it can solve my problem.
