### ISSUE TITLE
Any plan for model explanation functionality?

### ISSUE THREAD

**Issue by zhiruiwang** [uber/causalml#37]
Tried this package, had to say it is marvelous! I will not hesitate to use it in my real-life work, but wonder if there is plan to add support for model explanation tool such as feature importance plot, SHAP plot or tree visualizer. It would be crucial to present the model explanation to business stakeholders. 
Thanks for open sourcing this package!

**Comment by LinyingYang** [comment]
Same question here. Would it be possible to add functions about subgroup partition?

**Comment by jeongyoonlee** [comment]
Thanks for the idea @zhiruiwang. Adding feature importances for both meta-learners and uplift trees will be straightforward, and a good next step.

@LinyingYang, could you please elaborate more on what you mean by functions about subgroup partition?

**Comment by yungmsh** [comment]
Working on adding feature importance to base meta learners here: https://github.com/uber/causalml/pull/58. We plan on exploring SHAP/LIME and other tree visualizations in future iterations.

**Comment by zhiruiwang** [comment]
@jeongyoonlee @yungmsh Thanks for all the effort to add feature importance and SHAP for meta learners, and tree visualization for uplift tree models! I wonder is there any plan to add feature importance and SHAP to `UpliftTreeClassifier` and `UpliftRandomForestClassifier`? That would be a strong add to the model explanation in addition to tree visualization.
