### ISSUE TITLE
readme wrong code

### ISSUE THREAD

**Issue by daiwk** [uber/causalml#371]
te, lb, ub = xl.estimate_ate(X, e, treatment, y)

should change to

te, lb, ub = xl.estimate_ate(X=X, p=e, treatment=treatment, y=y)

because the variable 'treatment' will be treated as 'p' in the original code

**Comment by paullo0106** [comment]
Thanks for reporting, @daiwk .

Seems like a bug, both README and [Docs](https://causalml.readthedocs.io/en/latest/examples.html#average-treatment-effect-ate-estimation) need to be updated
