### ISSUE TITLE
BaseXClassifier: Predicting probability instead of class 

### ISSUE THREAD

**Issue by shaddyab** [uber/causalml#383]
When reviewing the code for BaseXClassifier prediction method I noticed that effect models are used to predict class (i.e., .predict() is used) rather than predict probability (i.e., using .predict_proba().)

- Is this intentional or a bug?
- Does this mean that that the effect models always need to be regression models and not classification models?

lines 517 thru 520 of inference.meta.xlearner
```
dhat_cs[group] = model_tau_c.predict(X)
dhat_ts[group] = model_tau_t.predict(X)

_te = (p[group] * dhat_cs[group] + (1 - p[group]) * dhat_ts[group]).reshape(-1, 1)
```

**Comment by jeongyoonlee** [comment]
Thanks for filing the issue, @shaddyab. `model_tau_c` and `model_tau_t` are treatment effect estimators for the control and treatment groups respectively, and unlike the outcome model, which is a classification model, treatment effect models are regression models. 

Hope this helps.

**Comment by shaddyab** [comment]
This makes sense. Thank you for your help!
