### ISSUE TITLE
increasing usability 

### ISSUE THREAD

**Issue by hossein-amini67** [uber/causalml#384]
Dear Causalml developer

As you surely have seen other python ML libraries are easy to implement even for generating a fake dataset. Currently, I have a problem with how to get started with the preparation of the dataset while I am pretty sure that your library is useful for my case in comparison with Causalnex(Microsoft library). The point is that another library has at least an example of a dataset that shows how they define the coefficients and groups. In my case, I have a specific index and I want to see the effect of the samples after that index on the target value of the index and compare it with the effect of samples before the index. I have understood that the samples after the point should be taken into account ```treatment group``` and samples before the index should be ```Control group```. If so, they become wrong when I see your example since in your example the treatment group is a ```0,1``` array with a shape similar to ```XX*1```. The ```XX``` is the number of rows. How to define ```e (Propensity)```,```y```????? I tried once and I faced a problem which I shared here but I could not solve the problem.

It is probably the dumbest question that you have ever seen but regardless of my solution using your library I need to understand how to work with your library which is interesting for me So please help me out.  
Best wishes 
Truly yours
Hossein

**Comment by paullo0106** [comment]
hi @hossein-amini67 , yes, we do provide data generating functionality, you should be able to find how we use `synthetic_data()` to create a sample dataset in many eample notebooks such as [meta_learners_with_synthetic_data.ipynb](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb). 

Also, as you can see from the example, `e`, propensity of receiving treatment, will also be provided to you quite conveniently when using [synthetic_data()](https://github.com/uber/causalml/blob/master/causalml/dataset/regression.py#L9). If you are using your own dataset, feel free to take a look at [compute_propensity_score()](https://github.com/uber/causalml/blob/master/causalml/propensity.py#L200) function which can help with propensity score calculation.
