### ISSUE TITLE
Running NearestNeighborMatch parallel

### ISSUE THREAD

**Issue by manishprasadthapliyal** [uber/causalml#386]
Hi, 
Hope you are doing well!

I have been using NearestNeighborMatch to match the closest data point in treatment group to control group.
Is there a way to run the match function in parallel?

Thanks,
Manish

**Comment by paullo0106** [comment]
Thanks for the question!

@ppstacy one enhancements could be adding support for `n_jobs` when we use `sklearn.neighbors.NearestNeighbors` [here](https://github.com/uber/causalml/blob/master/causalml/match.py#L139), but there might be more changes we can work on, how do you think?
