### ISSUE TITLE
Docs are not updated to date and miss some submodules

### ISSUE THREAD

**Issue by paullo0106** [uber/causalml#392]
**Describe the bug**

In our docs page: https://causalml.readthedocs.io/en/latest/causalml.html# , it doesn't reflect the latest codebase, for example:

- Missing content in few modules: `causalml.inference.tree` and `causalml.dataset`
<img width="839" alt="Screen Shot 2021-10-05 at 6 57 57 PM" src="https://user-images.githubusercontent.com/4966393/136128695-5b65b0d6-3f02-4ab2-83b3-c47b4bf71a46.png">  

- Some latest code changes are not reflected, for example, we added `n_jobs`, a new parameter to [NearestNeighborMatch](https://causalml.readthedocs.io/en/latest/causalml.html#causalml.match.NearestNeighborMatch) last week
- New modules can be added: `causalml.feature_selection`, `causalml.inference.nn`, `causalml.inference.tf`, and etc.  

**Other note** 

Resolving this issue will improve the searchability and consistency of CausalML

**Comment by paullo0106** [comment]
some references to fix this bug might be @jeongyoonlee 's previous commit related to sphinx: 
https://github.com/uber/causalml/pull/335 
https://github.com/uber/causalml/commits/master/docs/causalml.rst

**Comment by jeongyoonlee** [comment]
Just fixed the missing API docs for `inference.tree` and `dataset`. ;)
Please check it out here: https://causalml.readthedocs.io/en/latest/causalml.html
<img width="690" alt="Screen Shot 2021-11-19 at 7 29 57 PM" src="https://user-images.githubusercontent.com/3359887/142713097-99f5a0b6-4ccf-42ad-9d01-76c6eaefd03f.png">
