### ISSUE TITLE
Add net value optimization for classifier meta-learners

### ISSUE THREAD

**Issue by t-tte** [uber/causalml#40]
As the result of PR #39, we lost the net value optimisation approach previously implemented for R- and X-learners. The reference for the approach is: https://arxiv.org/abs/1908.05372

It should also be very straightforward to extend the approach to S- and T-learners.

**Comment by t-tte** [comment]
Update on this: we're going to implement a brand new method that can be used with any learner that estimates conditional average treatment effects. Testing is currently in progress.

**Comment by aftnix** [comment]
Any update on this?

**Comment by t-tte** [comment]
Yes, I'm aiming for the next release, ie within a week or so. Follow the issue for updates.
