### ISSUE TITLE
full memory is when run auuc_score function

### ISSUE THREAD

**Issue by RainFung** [uber/causalml#411]
**Describe the bug**
My data set has 155 columns and 1 million rows. My hardware is 128g RAM and 64 cores. When I run the auc function, my machine runs out of memory quickly. And my kernel restarted.

**Screenshots**
![image](https://user-images.githubusercontent.com/23121539/140383312-e4b4e8f6-34db-4754-aac5-e6e34210905a.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.6, 3.7
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by paullo0106** [comment]
@RainFung thanks for flagging this, can you provide more context how this was resolved? (just found you closed the ticket).

**Comment by enrir** [comment]
I encountered tha same issue. The solution is to check that the treatment_col is binary (0 and 1) and not of object data type.
