### ISSUE TITLE
Issue using V

### ISSUE THREAD

**Issue by dxs8292nt** [uber/causalml#421]
I am using the BaseXClassifier and I am running into an error. The code I am using is below:

x_learner=BaseXClassifier(control_outcome_learner=CatBoostClassifier(iterations=128,l2_leaf_reg=6,random_strength=0.09453,subsample=0.80,depth=9,learning_rate=0.01987,max_leaves=512,random_state=1234565),
   treatment_outcome_learner=CatBoostClassifier(iterations=118,l2_leaf_reg=38,random_strength=0.1421,subsample=0.80,depth=1,learning_rate=0.0142,max_leaves=2,random_state =1234565),
    control_effect_learner=LinearRegression(),
    treatment_effect_learner=LinearRegression())
x_learners=x_learner.fit(X_train_t,treatment_train_t,y_train_t) 
uplift_xlearner=x_learners.predict(X_test_t,treatment_test_t,y_test_t)  

It appears that the control and treatment outcome learners are working okay but when it hits the predict statement if flags an error:
Not sure what is going on

0:	learn: 0.6740409	total: 37.1ms	remaining: 4.71s
1:	learn: 0.6556550	total: 73.4ms	remaining: 4.63s
2:	learn: 0.6382347	total: 103ms	remaining: 4.28s
3:	learn: 0.6214941	total: 130ms	remaining: 4.02s
4:	learn: 0.6056092	total: 157ms	remaining: 3.87s
5:	learn: 0.5905234	total: 186ms	remaining: 3.78s
6:	learn: 0.5759102	total: 214ms	remaining: 3.69s
7:	learn: 0.5622586	total: 241ms	remaining: 3.62s
8:	learn: 0.5495344	total: 269ms	remaining: 3.56s
9:	learn: 0.5372329	total: 297ms	remaining: 3.5s
10:	learn: 0.5255085	total: 326ms	remaining: 3.47s
11:	learn: 0.5140124	total: 356ms	remaining: 3.44s
12:	learn: 0.5034772	total: 384ms	remaining: 3.4s
13:	learn: 0.4934347	total: 412ms	remaining: 3.35s
14:	learn: 0.4835474	total: 440ms	remaining: 3.31s
15:	learn: 0.4749262	total: 467ms	remaining: 3.27s
16:	learn: 0.4664420	total: 498ms	remaining: 3.25s
17:	learn: 0.4581310	total: 525ms	remaining: 3.21s
18:	learn: 0.4505080	total: 553ms	remaining: 3.17s
19:	learn: 0.4428904	total: 580ms	remaining: 3.13s
20:	learn: 0.4352174	total: 609ms	remaining: 3.1s
21:	learn: 0.4283685	total: 637ms	remaining: 3.07s
22:	learn: 0.4217030	total: 665ms	remaining: 3.04s
23:	learn: 0.4154252	total: 694ms	remaining: 3.01s
24:	learn: 0.4096209	total: 723ms	remaining: 2.98s
25:	learn: 0.4037902	total: 752ms	remaining: 2.95s
26:	learn: 0.3985839	total: 780ms	remaining: 2.92s
27:	learn: 0.3936030	total: 808ms	remaining: 2.88s
28:	learn: 0.3885715	total: 836ms	remaining: 2.85s
29:	learn: 0.3836339	total: 865ms	remaining: 2.83s
30:	learn: 0.3791767	total: 894ms	remaining: 2.8s
31:	learn: 0.3747851	total: 920ms	remaining: 2.76s
32:	learn: 0.3706055	total: 950ms	remaining: 2.73s
33:	learn: 0.3661741	total: 977ms	remaining: 2.7s
34:	learn: 0.3627242	total: 1s	remaining: 2.67s
35:	learn: 0.3592888	total: 1.03s	remaining: 2.64s
36:	learn: 0.3557369	total: 1.06s	remaining: 2.61s
37:	learn: 0.3521767	total: 1.09s	remaining: 2.58s
38:	learn: 0.3490220	total: 1.11s	remaining: 2.54s
39:	learn: 0.3461335	total: 1.15s	remaining: 2.52s
40:	learn: 0.3428174	total: 1.17s	remaining: 2.49s
41:	learn: 0.3398725	total: 1.21s	remaining: 2.47s
42:	learn: 0.3368969	total: 1.24s	remaining: 2.44s
43:	learn: 0.3343949	total: 1.26s	remaining: 2.42s
44:	learn: 0.3319656	total: 1.29s	remaining: 2.38s
45:	learn: 0.3296479	total: 1.32s	remaining: 2.35s
46:	learn: 0.3275507	total: 1.35s	remaining: 2.33s
47:	learn: 0.3251270	total: 1.38s	remaining: 2.29s
48:	learn: 0.3233642	total: 1.4s	remaining: 2.26s
49:	learn: 0.3214360	total: 1.43s	remaining: 2.23s
50:	learn: 0.3194840	total: 1.46s	remaining: 2.2s
51:	learn: 0.3175766	total: 1.49s	remaining: 2.17s
52:	learn: 0.3156436	total: 1.52s	remaining: 2.15s
53:	learn: 0.3138491	total: 1.54s	remaining: 2.12s
54:	learn: 0.3120890	total: 1.57s	remaining: 2.09s
55:	learn: 0.3103970	total: 1.6s	remaining: 2.06s
56:	learn: 0.3088413	total: 1.63s	remaining: 2.03s
57:	learn: 0.3072700	total: 1.66s	remaining: 2s
58:	learn: 0.3057165	total: 1.69s	remaining: 1.97s
59:	learn: 0.3044673	total: 1.71s	remaining: 1.94s
60:	learn: 0.3032238	total: 1.74s	remaining: 1.91s
61:	learn: 0.3017527	total: 1.77s	remaining: 1.88s
62:	learn: 0.3002733	total: 1.8s	remaining: 1.85s
63:	learn: 0.2989206	total: 1.82s	remaining: 1.82s
64:	learn: 0.2973628	total: 1.85s	remaining: 1.79s
65:	learn: 0.2960863	total: 1.88s	remaining: 1.77s
66:	learn: 0.2948616	total: 1.91s	remaining: 1.74s
67:	learn: 0.2936397	total: 1.94s	remaining: 1.71s
68:	learn: 0.2927938	total: 1.97s	remaining: 1.68s
69:	learn: 0.2916577	total: 1.99s	remaining: 1.65s
70:	learn: 0.2904391	total: 2.02s	remaining: 1.62s
71:	learn: 0.2892578	total: 2.05s	remaining: 1.59s
72:	learn: 0.2878177	total: 2.08s	remaining: 1.57s
73:	learn: 0.2867558	total: 2.11s	remaining: 1.54s
74:	learn: 0.2860074	total: 2.14s	remaining: 1.51s
75:	learn: 0.2847300	total: 2.17s	remaining: 1.48s
76:	learn: 0.2838219	total: 2.19s	remaining: 1.45s
77:	learn: 0.2832006	total: 2.22s	remaining: 1.42s
78:	learn: 0.2821076	total: 2.25s	remaining: 1.4s
79:	learn: 0.2813833	total: 2.28s	remaining: 1.37s
80:	learn: 0.2805153	total: 2.3s	remaining: 1.34s
81:	learn: 0.2796276	total: 2.33s	remaining: 1.31s
82:	learn: 0.2787476	total: 2.36s	remaining: 1.28s
83:	learn: 0.2778411	total: 2.39s	remaining: 1.25s
84:	learn: 0.2770441	total: 2.42s	remaining: 1.22s
85:	learn: 0.2762290	total: 2.45s	remaining: 1.2s
86:	learn: 0.2753892	total: 2.48s	remaining: 1.17s
87:	learn: 0.2746593	total: 2.5s	remaining: 1.14s
88:	learn: 0.2738952	total: 2.53s	remaining: 1.11s
89:	learn: 0.2731557	total: 2.56s	remaining: 1.08s
90:	learn: 0.2724233	total: 2.59s	remaining: 1.05s
91:	learn: 0.2718843	total: 2.62s	remaining: 1.02s
92:	learn: 0.2713138	total: 2.64s	remaining: 995ms
93:	learn: 0.2707630	total: 2.67s	remaining: 966ms
94:	learn: 0.2701037	total: 2.7s	remaining: 937ms
95:	learn: 0.2691692	total: 2.73s	remaining: 910ms
96:	learn: 0.2684424	total: 2.76s	remaining: 881ms
97:	learn: 0.2676143	total: 2.79s	remaining: 853ms
98:	learn: 0.2671196	total: 2.81s	remaining: 824ms
99:	learn: 0.2665299	total: 2.84s	remaining: 795ms
100:	learn: 0.2658549	total: 2.87s	remaining: 767ms
101:	learn: 0.2648011	total: 2.9s	remaining: 739ms
102:	learn: 0.2642339	total: 2.92s	remaining: 710ms
103:	learn: 0.2637116	total: 2.95s	remaining: 681ms
104:	learn: 0.2631466	total: 2.98s	remaining: 653ms
105:	learn: 0.2627287	total: 3.01s	remaining: 624ms
106:	learn: 0.2622134	total: 3.04s	remaining: 596ms
107:	learn: 0.2617689	total: 3.06s	remaining: 567ms
108:	learn: 0.2612735	total: 3.09s	remaining: 539ms
109:	learn: 0.2607793	total: 3.12s	remaining: 511ms
110:	learn: 0.2603191	total: 3.15s	remaining: 482ms
111:	learn: 0.2598725	total: 3.18s	remaining: 455ms
112:	learn: 0.2593668	total: 3.21s	remaining: 427ms
113:	learn: 0.2587747	total: 3.24s	remaining: 398ms
114:	learn: 0.2583238	total: 3.27s	remaining: 370ms
115:	learn: 0.2577488	total: 3.3s	remaining: 341ms
116:	learn: 0.2573047	total: 3.33s	remaining: 313ms
117:	learn: 0.2565597	total: 3.36s	remaining: 284ms
118:	learn: 0.2561665	total: 3.39s	remaining: 256ms
119:	learn: 0.2555379	total: 3.42s	remaining: 228ms
120:	learn: 0.2548704	total: 3.45s	remaining: 200ms
121:	learn: 0.2544903	total: 3.48s	remaining: 171ms
122:	learn: 0.2540334	total: 3.5s	remaining: 142ms
123:	learn: 0.2535946	total: 3.53s	remaining: 114ms
124:	learn: 0.2531703	total: 3.56s	remaining: 85.4ms
125:	learn: 0.2527534	total: 3.59s	remaining: 57.1ms
126:	learn: 0.2521191	total: 3.62s	remaining: 28.5ms
127:	learn: 0.2516241	total: 3.65s	remaining: 0us
0:	learn: 0.6791084	total: 6ms	remaining: 702ms
1:	learn: 0.6655086	total: 7.71ms	remaining: 447ms
2:	learn: 0.6523796	total: 9.79ms	remaining: 375ms
3:	learn: 0.6396808	total: 11.2ms	remaining: 321ms
4:	learn: 0.6274347	total: 13.9ms	remaining: 315ms
5:	learn: 0.6156433	total: 16.3ms	remaining: 303ms
6:	learn: 0.6046031	total: 18.7ms	remaining: 297ms
7:	learn: 0.5936915	total: 21ms	remaining: 289ms
8:	learn: 0.5830901	total: 23.6ms	remaining: 286ms
9:	learn: 0.5730807	total: 27.1ms	remaining: 293ms
10:	learn: 0.5631956	total: 29.2ms	remaining: 284ms
11:	learn: 0.5537003	total: 32.7ms	remaining: 289ms
12:	learn: 0.5445198	total: 34.4ms	remaining: 278ms
13:	learn: 0.5356775	total: 37.4ms	remaining: 278ms
14:	learn: 0.5269887	total: 40.4ms	remaining: 278ms
15:	learn: 0.5187461	total: 43.2ms	remaining: 276ms
16:	learn: 0.5106421	total: 44.8ms	remaining: 266ms
17:	learn: 0.5030435	total: 46.5ms	remaining: 258ms
18:	learn: 0.4956424	total: 48.1ms	remaining: 251ms
19:	learn: 0.4885109	total: 50.9ms	remaining: 249ms
20:	learn: 0.4816584	total: 54.1ms	remaining: 250ms
21:	learn: 0.4750545	total: 56.8ms	remaining: 248ms
22:	learn: 0.4686286	total: 59.8ms	remaining: 247ms
23:	learn: 0.4625159	total: 62.9ms	remaining: 246ms
24:	learn: 0.4565444	total: 65ms	remaining: 242ms
25:	learn: 0.4507463	total: 68.2ms	remaining: 241ms
26:	learn: 0.4452357	total: 70ms	remaining: 236ms
27:	learn: 0.4399877	total: 72.6ms	remaining: 233ms
28:	learn: 0.4346855	total: 75.4ms	remaining: 231ms
29:	learn: 0.4297116	total: 77.3ms	remaining: 227ms
30:	learn: 0.4249164	total: 79.4ms	remaining: 223ms
31:	learn: 0.4203715	total: 81ms	remaining: 218ms
32:	learn: 0.4157349	total: 82.7ms	remaining: 213ms
33:	learn: 0.4114055	total: 85.6ms	remaining: 212ms
34:	learn: 0.4071701	total: 89.4ms	remaining: 212ms
35:	learn: 0.4031418	total: 92.6ms	remaining: 211ms
36:	learn: 0.3991904	total: 96.3ms	remaining: 211ms
37:	learn: 0.3953786	total: 98.7ms	remaining: 208ms
38:	learn: 0.3917548	total: 102ms	remaining: 206ms
39:	learn: 0.3882640	total: 104ms	remaining: 202ms
40:	learn: 0.3848865	total: 106ms	remaining: 200ms
41:	learn: 0.3814944	total: 111ms	remaining: 201ms
42:	learn: 0.3784902	total: 114ms	remaining: 199ms
43:	learn: 0.3754549	total: 117ms	remaining: 198ms
44:	learn: 0.3725176	total: 120ms	remaining: 194ms
45:	learn: 0.3697053	total: 121ms	remaining: 190ms
46:	learn: 0.3669138	total: 123ms	remaining: 186ms
47:	learn: 0.3641331	total: 125ms	remaining: 183ms
48:	learn: 0.3615868	total: 127ms	remaining: 179ms
49:	learn: 0.3590658	total: 129ms	remaining: 175ms
50:	learn: 0.3566106	total: 131ms	remaining: 172ms
51:	learn: 0.3539221	total: 133ms	remaining: 169ms
52:	learn: 0.3517528	total: 135ms	remaining: 166ms
53:	learn: 0.3495957	total: 137ms	remaining: 162ms
54:	learn: 0.3475287	total: 138ms	remaining: 158ms
55:	learn: 0.3453478	total: 140ms	remaining: 155ms
56:	learn: 0.3432789	total: 144ms	remaining: 154ms
57:	learn: 0.3412838	total: 146ms	remaining: 151ms
58:	learn: 0.3394823	total: 148ms	remaining: 148ms
59:	learn: 0.3377720	total: 151ms	remaining: 146ms
60:	learn: 0.3360693	total: 153ms	remaining: 143ms
61:	learn: 0.3343151	total: 156ms	remaining: 141ms
62:	learn: 0.3326879	total: 159ms	remaining: 139ms
63:	learn: 0.3309264	total: 160ms	remaining: 135ms
64:	learn: 0.3293308	total: 162ms	remaining: 132ms
65:	learn: 0.3279182	total: 164ms	remaining: 129ms
66:	learn: 0.3265302	total: 166ms	remaining: 127ms
67:	learn: 0.3249963	total: 168ms	remaining: 124ms
68:	learn: 0.3237218	total: 170ms	remaining: 121ms
69:	learn: 0.3224946	total: 173ms	remaining: 118ms
70:	learn: 0.3212446	total: 175ms	remaining: 116ms
71:	learn: 0.3199585	total: 178ms	remaining: 113ms
72:	learn: 0.3188101	total: 181ms	remaining: 111ms
73:	learn: 0.3174754	total: 183ms	remaining: 109ms
74:	learn: 0.3163561	total: 185ms	remaining: 106ms
75:	learn: 0.3153561	total: 189ms	remaining: 104ms
76:	learn: 0.3143246	total: 191ms	remaining: 102ms
77:	learn: 0.3133255	total: 194ms	remaining: 99.4ms
78:	learn: 0.3124060	total: 197ms	remaining: 97.3ms
79:	learn: 0.3114888	total: 200ms	remaining: 94.8ms
80:	learn: 0.3106259	total: 202ms	remaining: 92.1ms
81:	learn: 0.3097721	total: 204ms	remaining: 89.6ms
82:	learn: 0.3089138	total: 207ms	remaining: 87.2ms
83:	learn: 0.3080725	total: 209ms	remaining: 84.6ms
84:	learn: 0.3071888	total: 211ms	remaining: 81.8ms
85:	learn: 0.3063355	total: 213ms	remaining: 79.2ms
86:	learn: 0.3054009	total: 216ms	remaining: 77.1ms
87:	learn: 0.3046666	total: 218ms	remaining: 74.3ms
88:	learn: 0.3038781	total: 219ms	remaining: 71.5ms
89:	learn: 0.3032312	total: 221ms	remaining: 68.8ms
90:	learn: 0.3025328	total: 223ms	remaining: 66.1ms
91:	learn: 0.3018301	total: 224ms	remaining: 63.4ms
92:	learn: 0.3012028	total: 226ms	remaining: 60.7ms
93:	learn: 0.3005651	total: 228ms	remaining: 58.1ms
94:	learn: 0.3000127	total: 234ms	remaining: 56.7ms
95:	learn: 0.2994672	total: 237ms	remaining: 54.3ms
96:	learn: 0.2988360	total: 239ms	remaining: 51.7ms
97:	learn: 0.2982412	total: 241ms	remaining: 49.2ms
98:	learn: 0.2977411	total: 244ms	remaining: 46.8ms
99:	learn: 0.2972566	total: 246ms	remaining: 44.3ms
100:	learn: 0.2966551	total: 248ms	remaining: 41.7ms
101:	learn: 0.2962097	total: 250ms	remaining: 39.2ms
102:	learn: 0.2956704	total: 252ms	remaining: 36.7ms
103:	learn: 0.2952134	total: 255ms	remaining: 34.3ms
104:	learn: 0.2947700	total: 257ms	remaining: 31.9ms
105:	learn: 0.2943643	total: 260ms	remaining: 29.4ms
106:	learn: 0.2938961	total: 263ms	remaining: 27ms
107:	learn: 0.2935060	total: 265ms	remaining: 24.5ms
108:	learn: 0.2930415	total: 267ms	remaining: 22ms
109:	learn: 0.2925481	total: 269ms	remaining: 19.5ms
110:	learn: 0.2921103	total: 270ms	remaining: 17ms
111:	learn: 0.2916187	total: 272ms	remaining: 14.6ms
112:	learn: 0.2911578	total: 273ms	remaining: 12.1ms
113:	learn: 0.2907553	total: 275ms	remaining: 9.65ms
114:	learn: 0.2904439	total: 277ms	remaining: 7.21ms
115:	learn: 0.2900627	total: 278ms	remaining: 4.79ms
116:	learn: 0.2896086	total: 281ms	remaining: 2.4ms
117:	learn: 0.2893014	total: 283ms	remaining: 0us
AttributeError: 'NoneType' object has no attribute 'predict'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-2815192307450793> in <module>
      5     treatment_effect_learner=LinearRegression())
      6 x_learners=x_learner.fit(X_train_t,treatment_train_t,y_train_t)
----> 7 uplift_xlearner=x_learners.predict(X_test_t,treatment_test_t,y_test_t,None)

AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by paullo0106** [comment]
thanks for reaching out, @dxs8292nt 
`fit()` method doesn't return anything so I think you are getting None value for `x_learners`. Can you try below instead?

```
x_learner.fit(X_train_t,treatment_train_t,y_train_t)
x_learner.predict(X_test_t,treatment_test_t,y_test_t)
```

**Comment by paullo0106** [comment]
can't reproduce the issue
