### ISSUE TITLE
How does the SHAP calculation work for T-learner?

### ISSUE THREAD

**Issue by mrpega** [uber/causalml#426]
Hi guys, new to causal inference in general and have been trying to read up as much as I could. I have a question and tried looking at the docs and codes but couldn't figure it out.

Question: For T-learner implementation, I saw that 2 models are being built. So when we calculate the shapely values, which one are we using? or we are just taking the mean of both models?

Thanks!

**Comment by huigangchen** [comment]
Hi, the approach adopted in the implementation for T-learner (or any learner if no single tau model is provided) that one  is that the code builds a model on the estimated tau from which the shapely value is calculated.

**Comment by mrpega** [comment]
> Hi, the approach adopted in the implementation for T-learner (or any learner if no single tau model is provided) is that the code builds a model on the estimated tau from which the shapely value is calculated.

Thanks for your answer. If I understand correctly: when a learner(most except R) produces tau(estimated CATE at the individual level), the code builds a LGBMRegressor model(also called tau model) that fits the original X used for the learner against tau(Y). Then this model is used to calculate the shaply values.

Is this correct?

Thanks for your help!

**Comment by jeongyoonlee** [comment]
@mrpega That is correct. R-learner trains a regressor X --> tau in its final step, and `Explainer` uses the fitted regressor directly in SHAP calculation.

**Comment by mrpega** [comment]
Awesome! Thanks @jeongyoonlee @huigangchen closing this issue~
