### ISSUE TITLE
Why does S-learner return a constant value for all ITEs?

### ISSUE THREAD

**Issue by bubble-wu** [uber/causalml#428]
Hi guys,

The examples in the repository helped me a lot in understanding the usage of CausalML. But when reading example [meta_learners_with_synthetic_data](https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb), I had a question that why S-learner return a constant value for all ITEs. From the below list `cate_s`, you can see every one has the same ITE. This result is also shown in `scatter_plot_single_sim(train_preds)`. Thanks!

```python
# S Learner
learner_s = LRSRegressor()
cate_s = learner_s.fit_predict(X=X, treatment=treatment, y=y)
```

**Comment by jeongyoonlee** [comment]
S-learner estimates treatment effects as `f(Y|T=1) - f(Y|T=0)`. When linear regression is used as a base outcome estimator `f(.)`,  this becomes the coefficient of `T` and independent of `X`. Therefore, it gives the constant treatment effects across all samples.
