### ISSUE TITLE
Should we do PSM before meta-learners when estimating ATE?

### ISSUE THREAD

**Issue by bubble-wu** [uber/causalml#430]
As far as I know,  we only need to evaluate ATE for observational data(since ATE is straightforward for randomized experiment). When dealing with observational data with meta-learner to estimate ATE(`estimate_ate`), should we perform a matching first or the function `estimate_ate` would do it automatically? 

For X-learner and R-learner, propensity score is a parameter but it still can be set as None. My question is for these situation and for S-learner and T-learner. The example notebook I referenced is https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb

Thanks!

**Comment by t-tte** [comment]
Propensity score matching is not required for estimating ATEs with meta-learners so long as the covariates that you use block any back-door paths between the treatment and outcome.

Then again, if the covariates don't block all back-door paths between the treatment and outcome, the matching step will not achieve its intended goal of balancing confounders between treatment and control observations.

Consequently, using matching with meta-learners is redundant from a theoretical point of view. That said, my understanding is that some users have had good results in practice when combining matching with meta-learners.
