### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' failed with exit status 

### ISSUE THREAD

**Issue by vorsprungdurchtae** [uber/causalml#431]
Hi,

I got again error with ImportError: Building module causalml.inference.tree.causaltree failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]
I also tried env3.6,3.7, and 3.8 but none of them enabled me to resolve the error regarding gcc.
I am currently using macOS Monterey and gcc version is --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1

**Comment by xxxibntkjgn** [comment]
DistutilsExecError Traceback (most recent call last)
~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
116 try:
--> 117 self.spawn(compiler_so + cc_args + [src, '-o', obj] +
118 extra_postargs)

~/anaconda3/lib/python3.8/distutils/ccompiler.py in spawn(self, cmd)
909 def spawn(self, cmd):
--> 910 spawn(cmd, dry_run=self.dry_run)
911

~/anaconda3/lib/python3.8/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
35 if os.name == 'posix':
---> 36 _spawn_posix(cmd, search_path, dry_run=dry_run)
37 elif os.name == 'nt':

~/anaconda3/lib/python3.8/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
156 cmd = executable
--> 157 raise DistutilsExecError(
158 "command %r failed with exit status %d"

DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
213 module_name = name
--> 214 so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
215 inplace=build_inplace, language_level=language_level)

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in build_module(name, pyxfilename, pyxbuild_dir, inplace, language_level)
185 from . import pyxbuild
--> 186 so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
187 build_in_temp=build_in_temp,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyxbuild.py in pyx_to_dll(filename, ext, force_rebuild, build_in_temp, pyxbuild_dir, setup_args, reload_support, inplace)
101 obj_build_ext = dist.get_command_obj("build_ext")
--> 102 dist.run_commands()
103 so_path = obj_build_ext.get_outputs()[0]

~/anaconda3/lib/python3.8/distutils/dist.py in run_commands(self)
965 for cmd in self.commands:
--> 966 self.run_command(cmd)
967

~/anaconda3/lib/python3.8/distutils/dist.py in run_command(self, command)
984 cmd_obj.ensure_finalized()
--> 985 cmd_obj.run()
986 self.have_run[command] = 1

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in run(self)
185
--> 186 _build_ext.build_ext.run(self)
187

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in run(self)
339 # Now actually compile and link everything.
--> 340 self.build_extensions()
341

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in build_extensions(self)
194 # Call original build_extensions
--> 195 _build_ext.build_ext.build_extensions(self)
196

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extensions(self)
448 else:
--> 449 self._build_extensions_serial()
450

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in _build_extensions_serial(self)
473 with self._filter_build_errors(ext):
--> 474 self.build_extension(ext)
475

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extension(self, ext)
527
--> 528 objects = self.compiler.compile(sources,
529 output_dir=self.build_temp,

~/anaconda3/lib/python3.8/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
573 continue
--> 574 self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
575

~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
119 except DistutilsExecError as msg:
--> 120 raise CompileError(msg)
121

CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

ImportError Traceback (most recent call last)
in 
2 from data_prep import read_prep_data
3 from action_rules import actionDiscovery, interpretRules, get_unique_actions
----> 4 from uplift_tree import create_uplift_tree
5 import package.user
6 user.doSomething()

~/Desktop/RWTH/WS21:22/Seminar/CausalRulesDiscovery/src/uplift_tree.py in 
----> 1 from causalml.inference.tree import UpliftTreeClassifier
2 from causalml.inference.tree import uplift_tree_string, uplift_tree_plot
3 from sklearn.model_selection import train_test_split
4 from log_processing import filter_log, process_data
5

~/Desktop/RWTH/WS21:22/Seminar/CausalRulesDiscovery/src/causalml/inference/tree/init.py in 
1 from .models import UpliftTreeClassifier, DecisionTree
2 from .models import UpliftRandomForestClassifier
----> 3 from .causaltree import CausalMSE, CausalTreeRegressor
4 from .plot import uplift_tree_string, uplift_tree_plot
5 from .utils import cat_group, cat_transform, cv_fold_index, cat_continuous, kpi_transform

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(self, fullname)
457 else:
458 #print "MODULE", fullname
--> 459 module = load_module(fullname, self.path,
460 self.pyxbuild_dir,
461 build_inplace=self.inplace,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
229 name, traceback.format_exception_only(*sys.exc_info()[:2])))
230 if sys.version_info[0] >= 3:
--> 231 raise exc.with_traceback(tb)
232 else:
233 exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
212 else:
213 module_name = name
--> 214 so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
215 inplace=build_inplace, language_level=language_level)
216 mod = imp.load_dynamic(name, so_path)

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in build_module(name, pyxfilename, pyxbuild_dir, inplace, language_level)
184
185 from . import pyxbuild
--> 186 so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
187 build_in_temp=build_in_temp,
188 pyxbuild_dir=pyxbuild_dir,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyxbuild.py in pyx_to_dll(filename, ext, force_rebuild, build_in_temp, pyxbuild_dir, setup_args, reload_support, inplace)
100 try:
101 obj_build_ext = dist.get_command_obj("build_ext")
--> 102 dist.run_commands()
103 so_path = obj_build_ext.get_outputs()[0]
104 if obj_build_ext.inplace:

~/anaconda3/lib/python3.8/distutils/dist.py in run_commands(self)
964 """
965 for cmd in self.commands:
--> 966 self.run_command(cmd)
967
968 # -- Methods that operate on its Commands --------------------------

~/anaconda3/lib/python3.8/distutils/dist.py in run_command(self, command)
983 cmd_obj = self.get_command_obj(command)
984 cmd_obj.ensure_finalized()
--> 985 cmd_obj.run()
986 self.have_run[command] = 1
987

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in run(self)
184 optimization.disable_optimization()
185
--> 186 _build_ext.build_ext.run(self)
187
188 def build_extensions(self):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in run(self)
338
339 # Now actually compile and link everything.
--> 340 self.build_extensions()
341
342 def check_extensions_list(self, extensions):

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in build_extensions(self)
193 ext.sources = self.cython_sources(ext.sources, ext)
194 # Call original build_extensions
--> 195 _build_ext.build_ext.build_extensions(self)
196
197 def cython_sources(self, sources, extension):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extensions(self)
447 self._build_extensions_parallel()
448 else:
--> 449 self._build_extensions_serial()
450
451 def _build_extensions_parallel(self):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in _build_extensions_serial(self)
472 for ext in self.extensions:
473 with self._filter_build_errors(ext):
--> 474 self.build_extension(ext)
475
476 @contextlib.contextmanager

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extension(self, ext)
526 macros.append((undef,))
527
--> 528 objects = self.compiler.compile(sources,
529 output_dir=self.build_temp,
530 macros=macros,

~/anaconda3/lib/python3.8/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
572 except KeyError:
573 continue
--> 574 self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
575
576 # Return all object filenames, not just the ones we just built.

~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
118 extra_postargs)
119 except DistutilsExecError as msg:
--> 120 raise CompileError(msg)
121
122 def create_static_lib(self, objects, output_libname,

ImportError: Building module causalml.inference.tree.causaltree failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]
