### ISSUE TITLE
Package requires old scipy version

### ISSUE THREAD

**Issue by zeromh** [uber/causalml#441]
**Is your feature request related to a problem? Please describe.**
The latest release of this package seems to require `scipy==1.4.1`, which is 2 years old as of writing. I use features from newer versions of scipy (at least 1.5), so this causes issues for my environment and running my code.

**Describe the solution you'd like**
A new `causalml` release that allows newer versions of `scipy`.

**Describe alternatives you've considered**
N/A

**Comment by jeongyoonlee** [comment]
Fixed in #473.
