### ISSUE TITLE
UpliftRandomForestClassifier with n_jobs=-1 creates copies of data

### ISSUE THREAD

**Issue by zeromh** [uber/causalml#442]
**Describe the bug**
When fitting an `UpliftRandomForestClassifier` with `n_jobs=-1`, RAM usage increases dramatically beyond the size of the loaded data (it goes up by 12x or more). 

This is unexpected, since `UpliftRandomForestClassifier` uses `joblib` for parallelization, which by default uses the `loky` backend that allows for data *not* to be copied. For example, if I fit a `sklearn` `RandomForestClassifier` with `n_jobs=-1` on the same dataset, RAM usage is only 2-3x the loaded data size. This is on a machine with 48 cores, all of which are used.

In sum, it seems like parallelization of `UpliftRandomForestClassifier` is causing the fit data to be copied, though I don't know why this would happen given the `loky` backend.

**To Reproduce**
Fit `UpliftRandomForestClassifier` on some large dataset with `n_jobs=-1`. On a machine with many cores, RAM usage will increase many-fold.

**Expected behavior**
With `n_jobs=1`, RAM usage increases to about 3x the size of the loaded data while fitting the uplift forest. Therefore, with `n_jobs=-1` using the `loky` backend, I would expect RAM usage to also be roughly 3-4x the size of the loaded data.

**Environment (please complete the following information):**
 - OS: Linux
 - Python Version: 3.8
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): 
 - - `pandas==1.2.5`
 - - `scikit-learn==1.0.1`
 - - `cython==0.29.25`

**Comment by paullo0106** [comment]
@jeongyoonlee you would know better! but one difference I noticed is that, RandomForest in scikit-learn  `_parallel_build_trees()` ([link](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_forest.py#L185])) is fitted with the same `X` and `y`, while our `bootstrap()` filter with `bt_index` ([link](https://github.com/uber/causalml/blob/master/causalml/inference/tree/uplift.pyx#L1336)) and might unavoidably make copies of the data.

**Comment by jeongyoonlee** [comment]
Hi @zeromh, I tested if `UpliftRandomForestClassifer` copies the input data across processes during parallelization, but it seems not.

I performed the test on a Ubuntu box with 64 CPU processes. and used the input data size of 134MB (200K samples).

When I varied the number of trees between 2, 10 and 64, the peak memory usage stayed the same at 761MB. It is greater than the input data size, but, since it didn't change with the number of trees, we can conclude that it's not from the data copy across processes but from other computation within a tree.

I also tested the memory usage in `scikit-learn`'s `RandomForestClassifer` for comparison, and surprisingly, its peak memory usage increased proportionally to the number of trees, meaning that `scikit-learn`'s `RandomForestClassifier` does copy the input data across processes (cc: @paullo0106).

Here is the script I used for the test:

```python
import multiprocessing
from causalml.inference.tree import UpliftRandomForestClassifier
from causalml.dataset import make_uplift_classification


RANDOM_SEED = 42
N_SAMPLE = 200_000
N_TREE = 64

TREATMENT_COL = 'treatment'
CONTROL_NAME = 'control'
TREATMENT_NAMES = [CONTROL_NAME, 'treatment1', 'treatment2', 'treatment3']
CONVERSION = 'conversion'


def main():
    df, x_names = make_uplift_classification(n_samples=N_SAMPLE,
                                             treatment_name=TREATMENT_NAMES,
                                             y_name=CONVERSION,
                                             random_seed=RANDOM_SEED)

    print(f"Data frame size: {df.memory_usage().sum() // (1024 * 1024)} MB")
    print(f"# of CPU: {multiprocessing.cpu_count()}")
    print(f"# of trees: {N_TREE}")

    # Train the UpLift Random Forest classifier
    uplift_model = UpliftRandomForestClassifier(
        n_estimators=N_TREE,
        min_samples_leaf=50,
        control_name=TREATMENT_NAMES[0],
        random_state=RANDOM_SEED,
        n_jobs=-1
    )

    uplift_model.fit(df[x_names].values,
                     treatment=df['treatment_group_key'].values,
                     y=df[CONVERSION].values)

if __name__ == '__main__':
    main()
```

and to profile memory usage, I used [`memory-profiler`](https://github.com/pythonprofilers/memory_profiler).

Hope this helps.

**Comment by zeromh** [comment]
Hi @jeongyoonlee, thanks for the script.

Are you running memory-profiler with the `--include-children ` or `--multiprocess` option? Joblib spawns child processes when fitting that won't be tracked by memory-profiler if you don't use one of those arguments. When I run your script using `mprof run --include-children python3 -m <script_name>`, and then check memory usage via `mprof plot`, I get 70 GB at peak. This is despite the initial dataframe size of 134MB.

(The machine I'm using has 48 cores, so I can't even fully explain this memory usage as data copying! Not sure why there is such a huge increase.)

Can you confirm whether you're including child processes in your profiling?

For contrast, sklearn Random Forests prefer to use multiple *threads*, not processes, so I would guess that is why your profiling picked up on the RAM increase. But they definitely don't make a copy of the data for every core! I used your script to make 1MM samples and fit a sklearn random forest. Initial df size was 671MB, and peak memory usage was 8.2GB when using 24 cores, and 15GB when using 48 cores. So there is an increase with more cores, but it doesn't fully copy the data, otherwise I would've hit 32GB at peak. This matters *a lot* when my actual data is millions of rows.

**Comment by jeongyoonlee** [comment]
Thanks, @zeromh. With the `--include-children` option, I was able to confirm the memory copy across trees. I switched the joblib backend for `UpliftRandomForestClassifier` to threading in #468, and don't see the memory copy anymore. Thanks again for your contribution!

**Comment by zeromh** [comment]
@jeongyoonlee Great outcome! Thanks!
