### ISSUE TITLE
Logo and build status are not displayed on PyPI

### ISSUE THREAD

**Issue by paullo0106** [uber/causalml#448]
**Describe the bug**
Please see the attached screenshot, logo and build status are not displayed on [CausalML's PyPI page](https://pypi.org/project/causalml/)

**To Reproduce**
Take a look at [CausalML's PyPI page](https://pypi.org/project/causalml/)

**Expected behavior**
We should and were able to see both shown up before

**Screenshots**
![Screen Shot 2021-12-30 at 3 34 28 PM](https://user-images.githubusercontent.com/4966393/147794550-d58b92b6-7495-41ae-8188-c05c59c15b02.png)

**Environment (please complete the following information):**
unrelated to local environment

**Additional context**

**Comment by jeongyoonlee** [comment]
It seems that it's the issue in README.md in v0.11.1, which was fixed later on. You can see that the same images are broken in v0.11.1 README.md here: https://github.com/uber/causalml/tree/v0.11.1.

It will be resolved once we publish a new version.

**Comment by ppstacy** [comment]
Confirm it got resolved after the new release, so will close this one.

![image](https://user-images.githubusercontent.com/19823328/149562218-49e892c4-8be9-400c-a574-6c122992cc3b.png)
