### ISSUE TITLE
unexpected validation tree for Uplift Classification Tree

### ISSUE THREAD

**Issue by da0715** [uber/causalml#460]
Hi there, 

The latest version 0.12.0 seems to have some problems with the validation tree for UpliftTreeClassifier. As you can see in the following screenshot, which is produced by the causalml/examples/uplift_tree_visualization.ipynb, this validation tree yields 0 group_sample for the control group. This is not the case in an earlier version 0.11.1, and this seemingly-problematic tree only appears when using the `fill` method and not the `fit` method. I wonder if this is expected, or if there is something wrong with the new version?

Thanks!

<img width="1306" alt="截屏2022-01-23 下午4 28 40" src="https://user-images.githubusercontent.com/98255030/150670999-31b02105-c63e-4b85-ba57-60b06536eecf.png">

**Comment by jeongyoonlee** [comment]
Thanks for reporting the issue, @da0715. When we improved `UpliftTreeClassifier`'s training code, we forgot to update related part in `fill()` for visualization. The issue has been fixed by @paullo0106 in #462.

Until we publish the new version to PyPi, please use `master` for tree visualization.
