### ISSUE TITLE
It seems that the example `benchmark_simulation_studies.ipynb` didn't manage to reproduce the results in the original paper.

### ISSUE THREAD

**Issue by RobinSeaside** [uber/causalml#467]
According to [the paper of R-learner](https://arxiv.org/abs/1712.04912), R-learner is supposed to outperform other meta models, especially for Setup A and Setup C. Any idea why in [this notebook](https://github.com/uber/causalml/blob/master/examples/benchmark_simulation_studies.ipynb) the performance of R-learner is worst compared to other meta learners when the base regressor is XGB?

**Comment by t-tte** [comment]
As suggested in the notebook, I believe the explanation is the lack of parameter tuning for XGB in the experiments. It would be possible to check this by using the tuning parameters mentioned in the paper. However, as noted on #109, there are also differences in performance between the Python and R implementations of the relevant algorithms.
