### ISSUE TITLE
fitting UpliftRandomForestClassifier uses more RAM in causalml 0.12.1 than in 0.12.0

### ISSUE THREAD

**Issue by heiderich** [uber/causalml#475]
**Describe the bug**

When fitting an `UpliftRandomForestClassifier` with `n_jobs=32` using causalml 0.12.1 on a machine with 32 cores, RAM usage is significantly higher compared to causalml 0.12.0. Since the upgrade I experienced it several times that the python process was killed OOM killer.

At the same time the CPUs are not completely used with causalml 0.12.1, as this had been the case with causalml 0.12.0, resulting in much longer training times. I did not measure it precisely, but I would estimate fitting times to be around 5 times higher in 0.12.1 compared to 0.12.0. 

**To Reproduce**

Fit an `UpliftRandomForestClassifier` with `n_jobs` big enough on a big dataset. 

**Expected behavior**

According to the description of https://github.com/uber/causalml/pull/468 I would have expected less RAM to be used with causalml 0.12.1 compared to 0.12.1. I experience the contrary.

**Environment (please complete the following information):**
 - OS: Linux 3.10.0
 - Python Version: 3.6.8
 - Versions of Major Dependencies
     - `pandas`: 1.1.5
     - `scikit-learn`: 0.24.2
     - `cython`: 0.29.27
     - `joblib`: 1.1.0

**Comment by heiderich** [comment]
I plan to create a PR that merely specifies the *preferred* backend and allowing the user to choose it according to the particular circumstances.

**Comment by jeongyoonlee** [comment]
Thanks for reporting it and submitting PRs, @heiderich! I'm little confused because I observed the opposite behavior when I tested #442. The environment looks pretty similar except the Python version.

Let's merge your PRs #476 and #477 and make the joblib backend configurable in #477. I will test it more when I have some time later this week.

Thanks!

**Comment by jeongyoonlee** [comment]
BTW, we're planning to retire Python 3.6 support because it reached to its EOL in 12/2021 and other dependencies dropped the support for it.

I personally recommend Python 3.8+ for the best comparability with other open source packages.
