### ISSUE TITLE
`outcome` is hard-coded

### ISSUE THREAD

**Issue by saiwing-yeung** [uber/causalml#490]
**Describe the bug**

In `_fit_condprob_models()` (https://github.com/uber/causalml/blob/master/causalml/optimize/unit_selection.py#L162), the column for outcome is hard-coded as `data['outcome']`.

I can make a PR if it helps.

**Comment by t-tte** [comment]
Yeah, that seems like a clear error. Thanks for catching. Feel free to
submit a PR.

**Comment by saiwing-yeung** [comment]
Was going to check in the change today. You beat me to it :-)
