### ISSUE TITLE
 from .uplift import DecisionTree, UpliftTreeClassifier, UpliftRandomForestClassifier   File "causalml/inference/tree/uplift.pyx", line 1, in init causalml.inference.tree.uplift ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by z-008** [uber/causalml#495]
**Environment (please complete the following information):**
 - OS: Mac OS M1
 - Python Version: 3.8
 - Versions of Major Dependencies 
  absl-py 1.0.0
actionrules-lukassykora 1.1.23
astunparse 1.6.3
Bottleneck 1.3.4
cachetools 5.0.0
causalml 0.12.3
certifi 2021.10.8
charset-normalizer 2.0.12
cloudpickle 2.0.0
cycler 0.11.0
Cython 0.29.28
dill 0.3.4
flatbuffers 2.0
fonttools 4.32.0
future 0.18.2
gast 0.5.3
google-auth 2.6.3
google-auth-oauthlib 0.4.6
google-pasta 0.2.0
graphviz 0.19.1
grpcio 1.44.0
h5py 3.6.0
idna 3.3
importlib-metadata 4.11.3
joblib 1.1.0
keras 2.8.0
Keras-Preprocessing 1.1.2
kiwisolver 1.4.2
libclang 13.0.0
lightgbm 3.2.1
llvmlite 0.38.0
Markdown 3.3.6
matplotlib 3.5.1
mkl-fft 1.3.1
mkl-random 1.2.2
mkl-service 2.4.0
numba 0.55.1
numexpr 2.8.1
numpy 1.21.5
oauthlib 3.2.0
opt-einsum 3.3.0
packaging 21.3
pandas 1.4.1
patsy 0.5.2
Pillow 9.1.0
pip 21.2.4
progressbar2 4.0.0
protobuf 3.20.0
pyasn1 0.4.8
pyasn1-modules 0.2.8
pydotplus 2.0.2
pyfim 6.28
pygam 0.8.0
pyparsing 3.0.4
pyro-api 0.1.2
pyro-ppl 1.8.1
python-dateutil 2.8.2
python-utils 3.1.0
pytz 2021.3
requests 2.27.1
requests-oauthlib 1.3.1
rsa 4.8
scikit-learn 1.0.2
scipy 1.7.3
seaborn 0.11.2
setuptools 58.0.4
shap 0.40.0
six 1.16.0
slicer 0.0.7
statsmodels 0.13.2
tensorboard 2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
tensorflow 2.8.0
tensorflow-io-gcs-filesystem 0.24.0
termcolor 1.1.0
tf-estimator-nightly 2.8.0.dev2021122109
threadpoolctl 2.2.0
torch 1.11.0
tqdm 4.64.0
typing_extensions 4.1.1
urllib3 1.26.9
Werkzeug 2.1.1
wheel 0.37.1
wrapt 1.14.0
xgboost 1.5.2
zipp 3.8.0

**Comment by z-008** [comment]
Tried upgrading numpy but to no avail

**Comment by z-008** [comment]
Running it on Mac M1

**Comment by z-008** [comment]
PIP LIST


absl-py                      1.0.0
actionrules-lukassykora      1.1.23
astunparse                   1.6.3
Bottleneck                   1.3.4
cachetools                   5.0.0
causalml                     0.12.3
certifi                      2021.10.8
charset-normalizer           2.0.12
cloudpickle                  2.0.0
cycler                       0.11.0
Cython                       0.29.28
dill                         0.3.4
flatbuffers                  2.0
fonttools                    4.32.0
future                       0.18.2
gast                         0.5.3
google-auth                  2.6.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
graphviz                     0.19.1
grpcio                       1.44.0
h5py                         3.6.0
idna                         3.3
importlib-metadata           4.11.3
joblib                       1.1.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.2
libclang                     13.0.0
lightgbm                     3.2.1
llvmlite                     0.38.0
Markdown                     3.3.6
matplotlib                   3.5.1
mkl-fft                      1.3.1
mkl-random                   1.2.2
mkl-service                  2.4.0
numba                        0.55.1
numexpr                      2.8.1
numpy                        1.21.5
oauthlib                     3.2.0
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.4.1
patsy                        0.5.2
Pillow                       9.1.0
pip                          21.2.4
progressbar2                 4.0.0
protobuf                     3.20.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pydotplus                    2.0.2
pyfim                        6.28
pygam                        0.8.0
pyparsing                    3.0.4
pyro-api                     0.1.2
pyro-ppl                     1.8.1
python-dateutil              2.8.2
python-utils                 3.1.0
pytz                         2021.3
requests                     2.27.1
requests-oauthlib            1.3.1
rsa                          4.8
scikit-learn                 1.0.2
scipy                        1.7.3
seaborn                      0.11.2
setuptools                   58.0.4
shap                         0.40.0
six                          1.16.0
slicer                       0.0.7
statsmodels                  0.13.2
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.0
tensorflow-io-gcs-filesystem 0.24.0
termcolor                    1.1.0
tf-estimator-nightly         2.8.0.dev2021122109
threadpoolctl                2.2.0
torch                        1.11.0
tqdm                         4.64.0
typing_extensions            4.1.1
urllib3                      1.26.9
Werkzeug                     2.1.1
wheel                        0.37.1
wrapt                        1.14.0
xgboost                      1.5.2
zipp                         3.8.0

**Comment by helenykwang** [comment]
me too,
Apple M1 Pro
Python Version : 3.8.13

**Comment by alexander-pv** [comment]
Perhaps, in Apple Silicon chip case it is better to build the package from source for now as [here](https://github.com/uber/causalml/blob/7050c74c257254de3600f69d49bda84a3ac152e2/pyproject.toml#L6) and [here](https://github.com/uber/causalml/blob/7050c74c257254de3600f69d49bda84a3ac152e2/setup.py#L75) numpy version is not specified which may lead to such libraries headers difference.
