### ISSUE TITLE
F method for variable selection returns TypeError

### ISSUE THREAD

**Issue by soodimilanlouei** [uber/causalml#503]
Running the variable selection using  the F method returns this error:

![image](https://user-images.githubusercontent.com/12864506/166068741-bbbc302d-296a-44d0-9043-effe5c238a71.png)

Thoughts on why that might happen?

**Comment by paullo0106** [comment]
@soodimilanlouei Thanks for reporting this, I'm guessing your `statsmodels.api` version might be newer (<=11 should work fine). In previous versions, fvalue attribute from `f_test()` used to be a 2D (1x1) numpy array such as _[[15.3]]_ where our implementation `F_test.fvalue[0][0]` made sense to unpack the value (see statsmodel code change [here](https://github.com/statsmodels/statsmodels/issues/6778) for reference)

I will commit some fixes around this for our team to review
