### ISSUE TITLE
Propensity Model is not converging 

### ISSUE THREAD

**Issue by ya-stack** [uber/causalml#510]
Hi Team,

I have tried to train a propensity model using LogisticRegression Model to find calibrated probabilities, but I am facing "**max iterations reached**" warning and it's running since a long. Please find attached the snippet of screenshot for your reference.

Also, I have changed **max_iter** from **100** to **10000** in **LogisticRegressionCV**, but still facing the issue.

Thanks in advance!

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/56586780/168068284-da221d0b-e108-4738-a74a-494d1078815e.png">

**Comment by jeongyoonlee** [comment]
Hi @ya-stack, the warning just means that the distribution of the treatment variable can't be fit by logistic regression with the `max_iter` iterations. 

However, please note that `LogisticRegressoinCV` trains multiple logistic regression models with the combinations of parameters given in `Cs` and `l1_ratios` to find the best hyperparameters (ref: [sklearn's LogisticRegressionCV doc](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html)). 

Therefore, even when some combinations didn't converge, the best combination might have converged. 

You can check the performance of the resulting propensity model using classification metrics such as the AUC score. As long as it's good, you can ignore the warnings.

**Comment by vincewu51** [comment]
Close this for now. Feel free to re-open if you still have questions.
