### ISSUE TITLE
scikit learn 1.1.0 cause build fail 

### ISSUE THREAD

**Issue by vincewu51** [uber/causalml#512]
**Describe the bug**
sklearn=1.1.0 is causing build fail. 
Specfically, the error is on the causaltree.pyx
`causalml/inference/tree/causaltree.pyx:136:37: Cannot assign type 'double[::1]' to 'double *'`

**To Reproduce**
* Specific sklearn version in requirement.txt ==1.1.0
* create a new PR and run build

**Expected behavior**
build pass

**Screenshots**
![Screen Shot 2022-05-13 at 11 40 39 AM](https://user-images.githubusercontent.com/24503553/168346809-998e0c1a-1e8f-4a46-8135-26f9ac3f3382.png)

**Environment (please complete the following information):**
 - Python Version: [e.g. 3.9]
 - Versions of Major Dependencies sklearn = 1.1.0
 
**Additional context**
Downgrade sklearn to 1.0.2 solves the issue. But we need to update uplift tree code to support future version.

**Comment by paullo0106** [comment]
Fixed in #511
