### ISSUE TITLE
How can I save a "UpliftTreeClassifier" model?

### ISSUE THREAD

**Issue by helenykwang** [uber/causalml#513]
I want to save models and reuse them in other scenes.
However, when I execute "pickle.dump(model, file) ", it reports an error :

PicklingError: Can't pickle <cyfunction UpliftTreeClassifier.evaluate_KL at 0x00000210E9C5E818>: attribute lookup evaluate_KL on causalml.inference.tree.uplift failed

How can I save a "UpliftTreeClassifier" model? Thank u very much.

**Comment by helenykwang** [comment]
I found a example notebook: https://colab.research.google.com/drive/1ud45oYCLFo6mWLDnK_uKpdQ9M7Oy5b7i?usp=sharing
but it doesn't work 

my version: 0.12.1

**Comment by paullo0106** [comment]
It works for me, @helenykwang do you mind providing the errors you run into?
<img width="671" alt="Screen Shot 2022-05-20 at 10 17 58 PM" src="https://user-images.githubusercontent.com/4966393/169636767-99fd1745-51de-4f00-afc3-fd32b3a95812.png">

**Comment by helenykwang** [comment]
感谢您的回复，&nbsp;colab上是可以正常保存的，但是在本地环境上保存失败。一样的版本，一样的代码。





Sincerely
***@***.***



&nbsp;

**Comment by helenykwang** [comment]
> It works for me, @helenykwang do you mind providing the errors you run into? <img alt="Screen Shot 2022-05-20 at 10 17 58 PM" width="671" src="https://user-images.githubusercontent.com/4966393/169636767-99fd1745-51de-4f00-afc3-fd32b3a95812.png">

Thanks for your reply, it can be saved normally on colab, but it fails to save on the local environment. Same version, same code.

![image](https://user-images.githubusercontent.com/26139575/169945712-cc821c5c-b5f4-4dcf-90e8-356400bde463.png)

**Comment by helenykwang** [comment]
env： win10，python3.6.5

And it works on the mac  @^@

**Comment by helenykwang** [comment]
env： win10，python3.6.5

it works ，using causalml <= 0.11.1  ，**not works when  causalml >= 0.12.0**

I think there is some problem with cpython file @jeongyoonlee @paullo0106 :
![image](https://user-images.githubusercontent.com/26139575/172585771-7b06b147-5766-49af-82da-481f140a6bbd.png)

**Comment by jeongyoonlee** [comment]
Hi @helenykwang, it sounds like the issue related to Cython on Windows. Which version of Cython do you have? Could you update Cython to the latest version and try again? I don't have a windows system to reproduce the issue on my end.
