### ISSUE TITLE
Bug with LRSRegressor.estimate_ate()

### ISSUE THREAD

**Issue by ThEtanti** [uber/causalml#521]
**Describe the bug**
Following the example, when running the code (meta_learners_with_synthetic_data)

![1655515850495](https://user-images.githubusercontent.com/40468260/174417285-55dc9eb2-c3ed-4539-8805-8974079043fb.jpg)

I encounter error:
![1655516027969](https://user-images.githubusercontent.com/40468260/174417360-55981517-62df-4ffb-bf97-ce9aa6495258.jpg)
show   estimate_ate() got an unexpected keyword argument 'pretrain'
**Environment (please complete the following information):**
 - OS: [macOS]
 - Python Version: [3.9]
 - Versions of Major Dependencies: [. `pandas==1.4.2`, `scikit-learn==1.0.2`, `cython==0.29`,`causalml==0.12.3`]

**Comment by paullo0106** [comment]
Thanks for reaching out, @vincewu51 added _pretrain_ parameter just last month in #511, a quick workaround before upgrading causalml's version can be ignore the parameter (e.g. `estimate_ate(X=X, treatment=treatment, y=y)` ) as you might not need it

**Comment by vincewu51** [comment]
This should be fixed by updating causalml version.
