### ISSUE TITLE
auuc greater than 1 and plot confused

### ISSUE THREAD

**Issue by pangpang97** [uber/causalml#524]
hello, 
I use UpliftRandomForestClassifier to do a uplift model. I am confused about the result.
here is my result.
![image](https://user-images.githubusercontent.com/24262596/176113588-4f48c82d-679b-4a69-a152-04fc3b836e62.png)

is it  reasonable that my auuc is greater than 1  and the uplift curve is below zero.

**Comment by jeongyoonlee** [comment]
Hi @pangpang97, unlike AUC, AUUC can be greater than 1. In this case, ATE for the whole population is negative as shown by the rightmost point. Therefore, it makes sense that as we treat more people (moving from left to right in the graph), the overall gain becomes more negative.

Hope this helps.
