### ISSUE TITLE
SHAP values and treatment effect values for causal forest 

### ISSUE THREAD

**Issue by himanData** [uber/causalml#527]
Hello,
I have been following one of the examples [(here)](https://github.com/uber/causalml/blob/master/examples/feature_interpretations_example.ipynb) and I see the meta learners have a `. get_shap_values` and `plot_shap_values` methods for SHAP values. Also, I think they have a `fit_predict` method to get the individual treatment effects. But I don't see the same methods for the causal forest approach. Can I ask how we can get those for the causal forest?

**Comment by alexander-pv** [comment]
Hi, `CausalTreeRegressor` and `CausalRandomForestRegressor` in #522 could be interpreted directly via `shap` (`shap.TreeExplainer`) with minor package update.

I could open new PR for this feature and PR for causalml support in `shap` but #522 is still open. So we need some time to get it reviewed and merged.

**Comment by alexander-pv** [comment]
Hi, the related PR https://github.com/uber/causalml/pull/536 is open now.
