### ISSUE TITLE
CausalTreeRegressor with the paramters 'criterion=causal_mse' can't been traind when dataset is much larger than example's

### ISSUE THREAD

**Issue by lmaors** [uber/causalml#541]
**Describe the bug**
CausalTreeRegressor with the paramters 'criterion=causal_mse' can't been trained when dataset is much larger than example's synthetic_data (e.g. X.shape[0] > 1000000).
But CausalTreeRegressor with the paramters 'criterion=standard_mse'    works.

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Python Version: 3.7
 - `pandas==1.3.5`, `scikit-learn==1.0.2`, `cython==0.29.30`,`numpy==1.21.6`

**Additional context**
causalml package was compiled from lastest source code

**Comment by t-tte** [comment]
When you say it can't be trained, what exactly happens when you try to do it?

**Comment by lmaors** [comment]
When the rows of datasets are much more than 1 million, It would spent much time to train.

**Comment by jeongyoonlee** [comment]
@lmaors, could you try the latest version from the repository? @alexander-pv further improved `CausalTreeRegressor` in #557.

Note that `CausalTreeRegressor` uses `scikit-learn`'s tree implementation in Cython, and it's expected to be slower than XGBoost or LightGBM that are implemented in C++.

**Comment by lmaors** [comment]
@jeongyoonlee, it works, thanks.
