### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by Patiljd** [uber/causalml#549]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by jeongyoonlee** [comment]
Could you fill more information e.g. environment, error message, etc.
