### ISSUE TITLE
ATE estimation with pretrained X learner

### ISSUE THREAD

**Issue by pedroVigano** [uber/causalml#552]
**Describe the bug**
When calculating the ATE with a pretrained X learner, an error occurs at line 288 (probably because treatment is None):

```
~\Anaconda3\lib\site-packages\causalml\inference\meta\rlearner.py in estimate_ate(self, X, treatment, y, p, sample_weight, bootstrap_ci, n_bootstraps, bootstrap_size, pretrain)
    286 
    287         for i, group in enumerate(self.t_groups):
--> 288             w = (treatment == group).astype(int)
    289             prob_treatment = float(sum(w)) / X.shape[0]
    290             _ate = te[:, i].mean()

AttributeError: 'bool' object has no attribute 'astype'
```

**To Reproduce**
Calculate ATE with a pretrained X learner, without inputting treatment and Y

**Expected behavior**
It should return the ATE

**Environment (please complete the following information):**
 - OS: Windows, Ubuntu
 - Python Version: 3.9.7
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`):  `pandas==1.4.3`, `scikit-learn==1.0.2`, `cython==0.29.24`

**Additional context**

**Comment by jeongyoonlee** [comment]
The `treatment` input argument is required and shouldn't be `None`.
