### ISSUE TITLE
Doc bug in README, class not found for LGBMRegressor and RandomForestRegressor

### ISSUE THREAD

**Issue by guotong1988** [uber/causalml#554]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/4702353/190943148-fd275b9c-e1df-4729-87db-21c897447e37.png">

**Comment by guotong1988** [comment]
https://github.com/uber/causalml/blob/master/examples/feature_interpretations_example.ipynb

**Comment by fkjslee** [comment]
same issue
