### ISSUE TITLE
Question : Continuous Treatments

### ISSUE THREAD

**Issue by BrianMiner** [uber/causalml#555]
Are there any models developed here yet for a continuous treatment? Example would be a discount offer (the amount of the discount) made to prospects. If not, is the best approach to just use a standard classification or regression models?

**Comment by jeongyoonlee** [comment]
In theory, you can use [R-learner](https://arxiv.org/pdf/1712.04912.pdf), where treatment can be continuous. However, current CausalML's R-learner implementation doesn't support continuous treatments yet.

Regarding your specific case, I'd assume that the discount amount might not be truly continuous but rather discrete, (e.g. 10%, 25%, 50% etc.). In that case, you can treat it as multiple treatments, and use CausalML's implementation.

Hope it helps.

**Comment by BrianMiner** [comment]
Got it, thanks! I am interested in interpolation between treatment points as well but I guess that would be easy enough to do from the three points predicted for each observation (prospect) when treatments are treated as categorical.

**Comment by RashidBakirov** [comment]
@jeongyoonlee - sorry to resurrect an older thread, but I was wondering if there have been any updates regarding models continuous treatment since then?
