### ISSUE TITLE
how to save the meta-learner model?

### ISSUE THREAD

**Issue by yuyihe-1216** [uber/causalml#560]
How to save a meta-learner model after training?

**Comment by jeongyoonlee** [comment]
You should be able to save the model with `pickle` or `joblib` (preferred) as for any `scikit-learn` model (ref: [Scikit-Learn's model persistence doc](https://scikit-learn.org/stable/model_persistence.html):
```
from joblib import dump, load

...
# Save the trained meta-learner
dump(model, 'filename.joblib')

# Load the saved meta-learner
model = load('filename.joblib')

```

**Comment by vincewu51** [comment]
close for now. Feel free to re-open is you have further questions.
