### ISSUE TITLE
After setting up the environment, Jupyter examples don't work

### ISSUE THREAD

**Issue by FTamas77** [uber/causalml#566]
**Describe the bug**
I followed the step in the instruction, but I still cannot run the example in Jupyter. Missing external dependencies. For example pandas, matplotlib cannot be imported.

**To Reproduce**
Install following the steps.

**Expected behavior**
Running examples.

**Screenshots**
![image](https://user-images.githubusercontent.com/76584703/198860435-27b666ad-0e36-442b-9f2c-762f20f60dfa.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python Version: 3.8.13

**Additional context**
I used the environment, so there shouldn't be a missing dependency.

**Comment by vincewu51** [comment]
Hi, thanks for reporting the bug. All packages should be included in the dependencies. Unfortunately, I cannot reproduce your issue. Please consider the pip install missing packages or check the environment.
