### ISSUE TITLE
got an unexpected keyword argument 'criterion'

### ISSUE THREAD

**Issue by xulu666666** [uber/causalml#578]
**Screenshots**
![image](https://user-images.githubusercontent.com/8776507/203081496-7c0f76fc-967f-482a-8d8f-98884fdc215e.png)
![image](https://user-images.githubusercontent.com/8776507/203081559-5c46e2e2-9028-43f3-aed5-6efcf4d3aa31.png)

**Environment (please complete the following information):**
 - OS: linux version 3.10.0-957.el7.x86_64 
 - Python Version: 3.6
 - causalml:0.6.0

**Comment by alexander-pv** [comment]
Hi, your causalml package version is too old. Please, try the latest 0.13.0 or consider to install the package from source.
