### ISSUE TITLE
causalml should not depend on private sklearn code

### ISSUE THREAD

**Issue by mblondel** [uber/causalml#579]
**Describe the bug**

causalml currently depends on private sklearn code, see e.g., https://github.com/uber/causalml/blob/master/causalml/inference/tree/causal/builder.pyx#L7

This makes causalml particularly fragile and unusable with recent sklearn versions:
https://github.com/uber/causalml/blob/master/requirements.txt#L9

I would suggest either to upgrade your code to work with latest sklearn versions or to ship the private code that you need with your package.

**Comment by juanitorduz** [comment]
+1 for loosing the `sklearn` restriction if possible (https://github.com/uber/causalml/blob/master/requirements.txt#L9)

**Comment by alexander-pv** [comment]
Hi, fair point. I think it is more convenient for future releases to store this code inside the package with meaningful modifications. Actually, I've already started doing it bit by bit with several PRs. 
It would be fruitful for the package if you could leave your code suggestions in a new PR.
