### ISSUE TITLE
some problems in installing causalml

### ISSUE THREAD

**Issue by deft899** [uber/causalml#593]
When installing causalml, I used methods including pip and conda, but none of them were successfully installed. Here are the errors I installed with the pip command, I don't know how to solve it

![1](https://user-images.githubusercontent.com/78062763/210476958-207b8c08-de0f-4861-9700-26184afd16d0.png)
![2](https://user-images.githubusercontent.com/78062763/210476965-328a888b-967f-48dc-8152-6fea9ddaa814.png)

**Comment by jakirhasantalukder** [comment]
I have a similar issue: after following your suggestions, I am unable to install the causalml packages.

Error: 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting causalml
  Using cached causalml-0.13.0.tar.gz (535 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
![Capture](https://user-images.githubusercontent.com/100099780/227098473-f461bdb9-cce1-43ea-9858-4d5640fe1a58.JPG)

  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by talhaanwarch** [comment]
did you try installing from source

**Comment by jakirhasantalukder** [comment]
Hi Talha,

Yes, I did.

Is it working from your side?

Please let me know. I am in serious crisis.

Best regards
Jakir

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vincewu51** [comment]
This should be solved in [637](https://github.com/uber/causalml/pull/637)

**Comment by jakirhasantalukder** [comment]
This code will work in google colab:

!git clone https://github.com/uber/causalml
!cd causalml
!pip install -e


!pip install /content/causalml 

## Then , run: 

from causalml.inference.meta import BaseXRegressor, BaseRRegressor, BaseSRegressor, BaseTRegressor
from causalml.inference.nn import CEVAE
from causalml.propensity import ElasticNetPropensityModel
from causalml.metrics import *
from causalml.dataset import simulate_hidden_confounder

# till, if it is not workiing, then restart the run time and run again. It will work.!!!
