### ISSUE TITLE
Propensity score in R-Learner is not generated with cross validation?

### ISSUE THREAD

**Issue by ZiJiaW** [uber/causalml#602]
Recently I read the implementation of rlearner, and found that the calculation of propensity score is not cross validated:

```python
if p is None:
            self._set_propensity_models(X=X, treatment=treatment, y=y)
            p = self.propensity
        else:
            p = self._format_p(p, self.t_groups)
```
In `_set_propensity_models`, it uses full training dataset to fit a model with which it predicts them too.

Is this a mistake? Because according to causalml doc(https://causalml.readthedocs.io/en/latest/methodology.html#meta-learner-algorithms) and some online references, e(X) and m(X) should all be predicted with cross validation.

**Comment by jeongyoonlee** [comment]
Thanks for the question. `self._set_propensity_models()` uses the four-fold cross-validation by default. Please see here for the default parameters used: https://github.com/uber/causalml/blob/master/causalml/propensity.py#L80

**Comment by ZiJiaW** [comment]
If I want to predict propensity score with other models (like xgboost) instead of ElasticNet, `_set_propensity_models` will not automatically use cross-validation. So I should wrap it myself?
