### ISSUE TITLE
Upgrade Scikit Learn version requirement 

### ISSUE THREAD

**Issue by zhenlu1** [uber/causalml#628]
**Is your feature request related to a problem? Please describe.**
It is hard to use the package together with other packages, since causalml requires `scikit-learn<=1.0.2`, and it usually have conflicts with other packages.

**Describe the solution you'd like**
Can we upgrade the scikit-learn requirement if is possible?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ras44** [comment]
@zhenlu1 can you provide a reproducible example to work with?

**Comment by ras44** [comment]
@jeongyoonlee I think this might be resolved given #686

**Comment by jeongyoonlee** [comment]
Closing this as it's resolved in #686.
