### ISSUE TITLE
build issue for py39

### ISSUE THREAD

**Issue by ras44** [uber/causalml#638]
**Describe the bug**
Install issues arise when using `environment-py39.yml`.

**To Reproduce**
See build summary at: https://github.com/ras44/causalml/actions/runs/5544780649

**Comment by ras44** [comment]
Seems related to https://github.com/docker-library/python/issues/558

**Comment by ras44** [comment]
FYI @jeongyoonlee 

setuptools does not seem to support py3.9 yet, so I think this is part of what's causing the py39 build issues

https://pyreadiness.org/3.9/

In other words, although causalml supports py39, my guess is that the install fails because of other packages not supporting it

**Comment by jeongyoonlee** [comment]
Let's close this issue, as we no longer use the environment files for installation.
