### ISSUE TITLE
RLearning for Multiple Treatment in causalml

### ISSUE THREAD

**Issue by ozgurasarstat** [uber/causalml#644]
Hello, one quick question please:

Is the RLearning extension for multi treatments described in the below paper implemented somewhere in causalml, if so where?

https://arxiv.org/pdf/1908.05372.pdf

Cheers

**Comment by jeongyoonlee** [comment]
Hi @ozgurasarstat. R-learner as well as other meta learners support multiple treatments as in the paper you shared (e.g., see [here](https://github.com/uber/causalml/blob/master/causalml/inference/meta/rlearner.py#L125).
