### ISSUE TITLE
AttributeError when benchmark_simulation_studies.ipynb calls print(causalml.__version__)

### ISSUE THREAD

**Issue by ras44** [uber/causalml#650]
**Describe the bug**

```
print(causalml.__version__)
```
produces
```
AttributeError: module 'causalml' has no attribute '__version__'
```

**To Reproduce**
run `benchmark_simulation_studies.ipynb`

**Expected behavior**
no error

**Screenshots**
![image](https://github.com/uber/causalml/assets/9282281/cf2a34d2-3ea1-4774-b7ee-e0c7f4f97abb)

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version: [e.g. 3.8]

**Additional context**
Potential solutions:
- reintroduce the `__version__` attribute, previously here: https://github.com/uber/causalml/blob/2bdb0f5f30470168f6aeaa73c3bd5efb3502a146/causalml/__init__.py#L2
- remove this line from the example.

**Comment by vincewu51** [comment]
This sounds good to me. I might be missing some context because I see we deliberately removed `__version__` in some previous PR. Do you know any reason behind it? (I thought it was a human error).

**Comment by ras44** [comment]
I'm not sure why it was removed, but it was removed in this commit:

https://github.com/uber/causalml/commit/de3fb5eb79b2f051406947e72e5887bc50250257

@alexander-pv might have removed it with the goal of using the below in notebooks instead?

```
import pkg_resources
pkg_resources.get_distribution('causalml').version
```

I can understand the logic of not having to hard-code version, but pull it dynamically.  Perhaps that was his thinking.

**Comment by jeongyoonlee** [comment]
@vincewu51, @ras44 as shared in [this stackoverflow answer](https://stackoverflow.com/a/74608959), the use of `__version__` in `__init__.py` is deprecated. Let's update the notebooks instead.
