### ISSUE TITLE
InvocationException: GraphViz's executables not found in examples/uplift_tree_visualization.ipynb

### ISSUE THREAD

**Issue by ras44** [uber/causalml#651]
**Describe the bug**
Running https://github.com/uber/causalml/blob/master/examples/uplift_tree_visualization.ipynb leads to an error:

```
InvocationException: GraphViz's executables not found
```

**To Reproduce**
Run http://34.171.211.97:8888/doc/tree/examples/uplift_tree_visualization.ipynb

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/uber/causalml/assets/9282281/c5ee0ae5-5d80-4c63-9780-3509aa866e91)

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Python Version: [3.8]

**Additional context**
This looks like a missing dependency on graphviz

**Comment by vincewu51** [comment]
graphviz has a recurring issue with the env variable issue. It seems to require manual installation for it to work [Link](https://stackoverflow.com/questions/65249831/jupyter-invocationexception-graphvizs-executables-not-found)
Should we seek alternatives?
@jeongyoonlee @paullo0106 @ppstacy

**Comment by ras44** [comment]
@vincewu51 @jeongyoonlee  On a clean instance, for me, I was able to resolve with two steps:

```
conda install python-graphviz
```
after which there appears to be an issue with libxrender.  When I check the `ldd` dependency resolution, libxrender is not installed:

![image](https://github.com/uber/causalml/assets/9282281/88907ac9-930b-428a-974b-81ded8c9eda7)

After installing it with `sudo apt-get install -y libxrender-dev`, I see beautiful tree plots!

![image](https://github.com/uber/causalml/assets/9282281/c0c1494b-864e-4291-9b1f-ac8686df718c)

So it appears the solution is:

```
conda install python-graphviz
conda config --add channels conda-forge
conda install xorg-libxrender
```

I'd be happy to include a PR that incorporates the fix.

**Comment by vincewu51** [comment]
That will be great. Thank you!
