### ISSUE TITLE
How to train CEVAE with GPU?

### ISSUE THREAD

**Issue by xiaogangzhu** [uber/causalml#653]
**Is your feature request related to a problem? Please describe.**
I find that CEVAE is very useful for me, but unfortunately I found it is not training using GPU and I cannot modify the dataloader to imporove my data reading efficiency.

**Describe the solution you'd like**
Is there any way to train CEVAE with GPU and also improve the Dataloader to have multiple workers?

**Describe alternatives you've considered**

**Additional context**

**Comment by xiaogangzhu** [comment]
Any update?

**Comment by jeongyoonlee** [comment]
Hi @xiaogangzhu. Can you submit an issue to [the Pyro repo](https://github.com/pyro-ppl/pyro/issues) because CausalML's CEVAE calls [Pyro's CEVAE implementation](https://docs.pyro.ai/en/dev/contrib.cevae.html)?
