### ISSUE TITLE
Issue with dataset.regression.simulate_randomized_trial

### ISSUE THREAD

**Issue by bsaunders23** [uber/causalml#658]
**Describe the bug**
Noticed error in simulated data in `dataset.regression.simulate_randomized_trial`, intended implementation is to take the element-wise max across 3 different arrays, however the implementation of `np.maximum(np.repeat(0.0, n), X[:, 0] + X[:, 1], X[:, 2])` was actually returning `np.maximum(np.repeat(0.0,n), X[:,0] + X[:,1])` and assigning the value of this to `X[:,2]` based on the documentation (see [out](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html)).

**To Reproduce**
Simulate data w/ `dataset.regression.simulate_randomized_trial`, observe correlation between X[:,0]/X[:,1] and X[:,2] weird distribution on X[:,2].

**Expected behavior**
All features distributed normally, tau independent of X[:,2]

**Screenshots**
![image](https://github.com/uber/causalml/assets/28548757/fd5c38a8-f1e3-4511-bf7c-b7a168e35e84)

**Environment (please complete the following information):**
N/A

**Additional context**
Added PR to fix in https://github.com/uber/causalml/pull/656, thinking maybe issues get more attention so just plugging it here

**Comment by vincewu51** [comment]
Fixed by [PR](https://github.com/uber/causalml/pull/656)

**Comment by vincewu51** [comment]
Close
