### ISSUE TITLE
Add multi-armed Qini (maq)

### ISSUE THREAD

**Issue by t-tte** [uber/causalml#662]
**Is your feature request related to a problem? Please describe.**
Current methods for evaluating multiple costly treatments are somewhat hacky.

**Describe the solution you'd like**
The good folks at [grf labs](https://github.com/grf-labs/maq) came up with a generalisation of the Qini curve method for multiple costly treatments.

**Describe alternatives you've considered**
N/A

**Additional context**
@erikcs is currently working to polish the Python wrapper for maq. The idea is to incorporate this in a lightweight way to Causal ML.

**Comment by ras44** [comment]
hi @t-tte

FYI, looks like the MAQ python package is available now: https://github.com/grf-labs/maq/tree/master/python-package

with example: https://github.com/grf-labs/maq/blob/master/python-package/notebooks/introduction.ipynb

**Comment by t-tte** [comment]
Yep, @erikcs has now now polished the Python implementation.

The idea we discussed was to implement multi-qini through CausalML.metrics.multiqini or something similar. Should be doable via a lightweight wrapper. Does this seem reasonable @erikcs, @ras44 and @jeongyoonlee?

I'm currently short on time but can look into this early next year. Alternatively, if any of you have bandwidth for an initial implementation, I'll be happy to review.

**Comment by erikcs** [comment]
Thanks @t-tte, that sounds great! I too have a bit limited bandwidth now, but would be happy to provide input (and could also gladly hop on a zoom if anyone wants a quick live tour of how the multi-armed qini proposal works). And nice to see you @ras44, I remember you made some nice contributions to grf!

**Comment by jeongyoonlee** [comment]
I'm closing this issue as we merged #729.
