### ISSUE TITLE
pip install fails on pyton 3.11, command 'cl.exe' failed: None, cannot build wheels for causalml

### ISSUE THREAD

**Issue by priya-velu5** [uber/causalml#665]
**pip install fails. Please update the documentation with requirements.txt file location as casualml/docs*

**To Reproduce**
`$ git clone https://github.com/uber/causalml.git`
`$ cd causalml`
`$ pip install -r requirements.txt` 
`$ pip install causalml`

**Expected behavior**
causalml installed

**Snippet of the output**
<img width="453" alt="image" src="https://github.com/uber/causalml/assets/55476275/d529e582-a613-41ce-ac88-939c68d5d89a">

**Environment:**
 - OS: Windows 64 bit
 - Python Version: 3.11.1

**Comment by jeongyoonlee** [comment]
`requirements.txt` is deprecated, and `pyproject.toml` replaced it with #553. 

Can you try to install the latest version from the repo by following the instructions in README.md?
```
# Create a clean conda environment and install conda dependencies:
conda create -n causalml-py38 python=3.8
conda activate causalml-py38
conda install -c conda-forge cxx-compiler
conda install python-graphviz
conda install -c conda-forge xorg-libxrender

# Install CausalML from source:
git clone https://github.com/uber/causalml.git
cd causalml
pip install .
python setup.py build_ext --inplace
```

**Comment by priya-velu5** [comment]
**I followed all the steps and this is the error I encountered at** `pip install .` 

<img width="584" alt="image" src="https://github.com/uber/causalml/assets/55476275/0db46d8e-d430-4052-8e64-085f5ede6cc1">

**Fix I tried:**
updated my build tools packages using this command: `py -m pip install --upgrade pip setuptool` 
but I got the same error. 

**Error at the next step** `python setup.py build_ext --inplace` : 

<img width="717" alt="image" src="https://github.com/uber/causalml/assets/55476275/ff976d9e-3707-47dc-981c-d67ed0251c19">

**Comment by jeongyoonlee** [comment]
It seems that you don't have `cl.exe`, the Microsoft C compiler, installed on your system (ref [[1]](https://stackoverflow.com/questions/71242919/pip-install-results-in-this-error-cl-exe-failed-with-exit-code-2)). You can either install it before using `pip` install, or use `conda-forge` install:

```
conda install -c conda-forge causalml
```

**Comment by priya-velu5** [comment]
The installation succeeded after uninstalling and re-installing my:

1.  Python with Miniconda (I use miniconda since I just want the conda command prompt), and 
2. Visual Studio Build tools 2019 and 2022. (VS 2022 build tools are probably not needed). 

Important note: 

- The installation needed to be done through the Developer Command Prompt for VS **2019**. Using developer command prompt ensures that pip can find `cl.exe` file [(source)](https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed?rq=3). We cannot manually set the `PATH` environment variable. 
- The commands
 `conda install -c conda-forge cxx-compiler`
`conda install python-graphviz`
`conda install -c conda-forge xorg-libxrender`
 
needed [visual studio 2019 build tools](https://visualstudio.microsoft.com/vs/older-downloads/) to be successful. I ran into "The system cannot find the path specified." errors when I tried installing with the 2022 developer command prompt.  It was looking for files specifically inside the "2019" folder. 

Installing Build Tools for Visual Studio 2019:
- Select "Desktop Development with C++" 

Installing miniconda:
- Set conda to path since you'll need to access conda through the VS developer command prompt and not just Anaconda prompt.

**Comment by jeongyoonlee** [comment]
Thanks, @priya-velu5, for sharing this. This will help other Windows users greatly. 

@ras44, can you try this and update #678 accordingly? Thanks.
