### ISSUE TITLE
Add bootstrap confidence intervals for ATE

### ISSUE THREAD

**Issue by ppstacy** [uber/causalml#67]
It seems we are returning the percentile results instead of the CI. 
https://github.com/uber/causalml/blob/master/causalml/inference/meta/rlearner.py#L174-L175

**Comment by jeongyoonlee** [comment]
@ppstacy it looks correct to me. It's how we calculate the booststrap CI.

**Comment by jeongyoonlee** [comment]
From the offline discussion with @ppstacy: Causal ML has bootstrap CIs for ITE, but not ATE. Current CI estimates for ATE from `estimate_ate()` are often too narrow, and we may want to add bootstrap CIs for ITE as well as alternative.

I'm changing the title to reflect the discussion.

**Comment by t-tte** [comment]
+1 for bootstrapping the CIs for ATE.
