### ISSUE TITLE
Overcoming Library Dependency Challenges When Installing CausalML

### ISSUE THREAD

**Issue by shakednave-vi** [uber/causalml#679]
I need to install causalml, but it requires me to use sklearn==1.2.2 and pandas==1.3.5 in my pip virtual environment to avoid conflicts. Is there a solution to this issue caused by causalml’s outdated library dependencies?

**Comment by jeongyoonlee** [comment]
Hi @shakednave-vi.

We relaxed the pandas (and numpy) version requirement in #681, but it's not trivial for scikit-learn as our causal tree implementation depends on a specific version of scikit-learn.

cc: @alexander-pv

**Comment by shakednave-vi** [comment]
Hi @jeongyoonlee,

Can you please refer to the non-trivial parts in the package and I'll see if I can contribute?

**Comment by jeongyoonlee** [comment]
It involves removing dependencies on the Scikit-learn's tree module within `causalml.inference.tree.causal.*`. Check out #686 for more details and one proposal by @alexander-pv.

**Comment by jeongyoonlee** [comment]
I'm closing this issue as the `pandas` version requirement has been relaxed in #681, and we have #682, which is more specific for the `scikit-learn` dependency.
