### ISSUE TITLE
Support numpy 1.24.3

### ISSUE THREAD

**Issue by elgalu** [uber/causalml#680]
1. We currently need numpy 1.24.3 but latest (0.14.1) causalml requires numpy<1.24

https://github.com/uber/causalml/blob/3b3daaa3cd2ef1960028908c152cfd242b37712c/pyproject.toml#L29

2. Similarly, we need pandas 1.5.3

https://github.com/uber/causalml/blob/3b3daaa3cd2ef1960028908c152cfd242b37712c/pyproject.toml#L32

3. Cython seems stuck in a very old version <=0.29.34 , latest is 3.0.2

**Comment by jeongyoonlee** [comment]
Hi @elgalu. 

I will submit a PR to remove the constraints for numpy and pandas as causalml with the latest versions of them passed the build and all tests. 

Regarding Cython, our causal tree implementation depends on the specific versions of scikit-learn, which requires lower versions of Cython. @alexander-pv, do you have any updates on this?

**Comment by alexander-pv** [comment]
Hi, @jeongyoonlee, I recently started working on the related issue #579.
