### ISSUE TITLE
Support the latest scikit-learn

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#682]
**Is your feature request related to a problem? Please describe.**

Current causal tree implementation depends on `scikit-learn<=1.0.2`, and it raises Cython errors with the latest `scikit-learn` due to the change introduced in scikit-learn/scikit-learn#22328.

**Describe the solution you'd like**

Updating the caudal tree code with the changes in scikit-learn/scikit-learn#22328.

**Describe alternatives you've considered**

Adding scikit-learn/scikit-learn/tree as a subtree ([ref](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges#adding-a-new-repository-as-a-subtree)). This may help better sync the `causalml` and `scikit-learn`'s tree implementations while allowing the usage of the latest `scikit-learn`. 

**Additional context**
N/A

**Comment by ras44** [comment]
see also discussion in #619

**Comment by jeongyoonlee** [comment]
Resolved with #686
