### ISSUE TITLE
`python setup.py build_ext --inplace` errors on windows 

### ISSUE THREAD

**Issue by rolandrmgservices** [uber/causalml#699]
**Describe the bug**
Calling `python setup.py build_ext --inplace` errors on windows.

**To Reproduce**
Follow windows installation steps and then run the above command.  It produces an infinite/recursive loop repeating the same error.

This was installed in a conda environment running within anaconda powershell prompt, where previously the install succeeded.

**Expected behavior**
Success

**Screenshots**
![image](https://github.com/uber/causalml/assets/97845453/5e2dfdaf-08a6-46ff-95c0-c33150da76d4)

**Environment (please complete the following information):**
 - OS: [Windows]
 - Python Version: [3.8]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**
None

**Comment by shss0622** [comment]
Try changing "nthreads=0" in the setup function in the setup.py file. The reason for the error should be: the Linux system uses multiprocessing to load data, but it seems that this is not possible on Windows. So you can set "nthreads" to 0 to avoid enabling multiprocessing.
