### ISSUE TITLE
Propensity score requirement in X-learner and R-learner

### ISSUE THREAD

**Issue by nsalas24** [uber/causalml#70]
First, thanks for open-sourcing this package. I've learned a lot!

I'm wondering if there's a particular reason why the user must pass self generated propensity scores to be used in the X-learner and R-learner? While it most likely forces the user to understand how well calibrated the scores are, I would think there's validity in estimating them 'under the hood' using the `learner` or another supplied model parameterization (similar to how `BaseRLearner.outcome_learner` can be optionally specified). 

In terms of the X-learner, while Kunzel et al. state they have good experiences specifying g(x) as the propensity scores, its worth noting g(x) is simply a weighting function that is chosen to minimize the variance of the CATEs. Stating this in the documentation / naming conventions might be helpful also?

Thanks

**Comment by t-tte** [comment]
Thanks for the comment. It may be a good idea to implement some optional "under the hood" calculation of the propensity score in future versions. The package comes with the simple ElasticNetPropensityModel class for urgent needs.

As you suggest, in X/R-Learner the propensity score doesn't play the same role as it does in observational causal inference. There is a case for highlighting this in the documentation as we've found the terminology of propensity scores can cause confusion for users.

**Comment by nsalas24** [comment]
@t-tte I can take a first stab at this.

**Comment by swager** [comment]
I came across this thread serendipitously, and just wanted to add a quick comment.

The way the X-learner and the R-learner use the propensity score is very different. The X-learner in fact just uses the propensity score as a weighting function for variance minimization, and so having accurate propensity estimates is not so important.

In contrast, the R-learner relies crucially on the propensity score for accurate CATE estimation. The R-learner is motivated by an orthogonal estimating equation for the CATE, and so the propensity score plays the same role in the R-learner as it does in many other observational study methods (including the work on double machine learning from Chernozhukov & co-authors). Having reasonably accurate propensity score estimates really helps the R-learner a lot.

The upshot is that if you want an interface that doesn't require the user to prove a propensity score for the R-learner, then you need to add functionality that learns an (accurate, cross-fitted) propensity score behind the scenes.

Finally, thanks to the maintainers of this package for all your work on this!

**Comment by jeongyoonlee** [comment]
Thanks, @swager for your comment. It means a lot to the team to have kind words from you, the author of the approaches we implemented!

As suggested, we decided to simply the APIs for X and R learners to be consistent with other learners by making the propensity score input optional. If the propensity score is not provided, we will predict it under the hood.

Thanks again!

**Comment by t-tte** [comment]
That's a great clarification @swager - also discussed in an earlier issue (https://github.com/uber/causalml/issues/52).

It seems like we should consider approaching the propensity score calculation differently in the X- and the R-learner. In particular, since the propensity score plays a less important role in the X-learner, we should consider implementing a very lightweight under-the-hood propensity score estimation for that method in order to keep the computational requirements as light as possible. 

For the R-learner, in contrast, we need to consider a more sophisticated propensity score routine. As a clarification, @swager, when you mention "cross-fitted" propensity score, do you specifically refer to what [Chernozhukov et al (2014)](https://arxiv.org/pdf/1608.00060.pdf) call "cross-fitting"?

**Comment by swager** [comment]
Thanks again to all of you -- it's really cool that your work makes all these methods available to a wide audience!

@t-tte yes the notion of cross-fitting is exactly the same. For a short discussion on connections between the R-learner, what Chernozhukov et al do, and causal forests, Section 1.3 of https://arxiv.org/pdf/1902.07409.pdf may be useful.

p.s. With apologies for being off-topic (and if we want to have a longer conversation about this, we should probably start a separate thread): One thing many of us in the academic community would be very interested in is if, once this package is ready, you could try benchmarking it against simulation studies from some existing papers. For example, we have replication files for the R-learner paper at https://github.com/xnie/rlearner/tree/master/experiments_for_paper, and I'm sure the authors of the X-learner paper could also provide similar resources. Anyways, I recognize this'd be a lot of work and no worries if you don't end up doing it! But I just wanted to throw it out there as it'd be super helpful for us (for example, down the road, it might enable us to recommend this as an alternative software option for students who prefer working in python).
