### ISSUE TITLE
How to draw causal inference with Confounding Variables

### ISSUE THREAD

**Issue by zby0327** [uber/causalml#708]
I have a dataset with many variables. The independent variable is binomial. The dependent variable is continuous. I want to control some confounding variables which may influence the dependent variable but I cannot figure out how to do that. 
Are there any features in this causalML package to control the confounding variables? Thank you.

**Comment by ras44** [comment]
hi @zby0327 not sure if your confounders are observed or unobserved, but you might want to look at the function in `dataset/regression.py`  called `simulate_hidden_confounder(...)`, called through `synthetic_data(...)` (also in `dataset/regression.py`).

For an applied example, see https://github.com/uber/causalml/blob/master/docs/examples/meta_learners_with_synthetic_data.ipynb
