### ISSUE TITLE
add proportion of sample in addition to total sample size 

### ISSUE THREAD

**Issue by DSXiangLi** [uber/causalml#73]
In tree visualization, I found it helpful to add proportion of sample in addition to total sample size. Because sample size varies from train to validation, while proportion may be similar

**Comment by paullo0106** [comment]
Like this kind of proportion calcs in R? Attainable by adding a couple of lines in [tree/plot.py](https://github.com/uber/causalml/blob/master/causalml/inference/tree/plot.py)
![image](https://user-images.githubusercontent.com/4966393/68451295-0f86a200-01a3-11ea-82fc-ba339114478b.png)

**Comment by DSXiangLi** [comment]
Exactly. And also this should apply to tree_fill method too. Since validation size and train size are not comparable, displaying n_sample in the node is not very informative some times.

**Comment by paullo0106** [comment]
@zhenyuz0500 I'd be happy to help with this enhancement if you agree with the ask/ solution 😃

**Comment by paullo0106** [comment]
Sample output after the code changes
<img width="1579" alt="Screen Shot 2019-11-14 at 11 12 45 PM" src="https://user-images.githubusercontent.com/4966393/68923933-66a4ed80-0734-11ea-8ddf-c32c06ec6fb1.png">
