### ISSUE TITLE
Installation error on Databrick Cluster

### ISSUE THREAD

**Issue by MZhangNan** [uber/causalml#740]
**Describe the bug**
When I try to use pip install causalml on my personal cluster on databrick, it runs into error related to "Error compiling Cython file".  I have tried to install Cython and all the required packages listed in the document, but, still encounter the same error. 

**Screenshots**
<img width="1219" alt="image" src="https://github.com/uber/causalml/assets/43627422/bb8e3787-d63d-4da2-9881-71f3031e186b">

**Environment (please complete the following information):**
 - OS: macOS on Databricks
 - Python Version: 3.10
 - Versions of Major Dependencies: Python version: 3.10
    causalml version: 0.14.1
    Cython version: 0.29.32
    scikit-learn version: 1.1.1
    numpy version:  1.23.5
    pandas version:1.5.3

**Comment by arihant-angelone** [comment]
Hey @MZhangNan,

I was also facing error installing causalml with Databricks runtime version 14.3 LTS ML. I changed my cluster DBR to 12.2 LTS ML and it was successfully installed.

1. `%pip install causalml`
2. `dbutils.library.restartPython()`
3. `import casualml`

**Comment by MZhangNan** [comment]
Hi, @arihant-angelone 
Thanks!! I followed your suggestion and the issue is resolved!!
