### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by UranA1** [uber/causalml#742]
**Is your feature request related to a problem? Please describe.**
I am currently working on a project where I am using this library. The issue that I am facing is the old requirements around Pandas and Numpy. Some of the other libraries I am using do not allow for such old versions of Numpy and Pandas. 

**Describe the solution you'd like**
Would it be possible to update the requirements the following way?
* "numpy>=1.18.5", to "numpy>=1.25",
* "pandas>=0.24.1,<1.4.0", to "pandas>=1.4.4,<2",

I cloned the repo locally and ran all the tests and it worked as expected, thus I would not see any issue to not update the requirements to be more up to date. 

**Describe alternatives you've considered**
I do understand that it would be possible to get older versions of the external libraries, but I am not sure this would be the best approach for further development.

**Comment by ppstacy** [comment]
thanks @UranA1! Could you please submit a PR for this?

**Comment by jeongyoonlee** [comment]
#743 relaxed the `pandas` version requirement. For dependencies without upper bounds, e.g., `numpy` in your example, it should install the latest version if it's not already installed. Otherwise, you can upgrade the existing dependencies using `pip install -U -r requirements.txt`.
