### ISSUE TITLE
Installation fails with pip and from source in Python 3.7

### ISSUE THREAD

**Issue by MaximilianFranz** [uber/causalml#76]
Hey there, 

I was trying to add `causalml` as a dependency to our project. When trying `pip install causalml` this error occurred: 

```bash
Collecting causalml
  Using cached https://files.pythonhosted.org/packages/4e/92/fb9af85303fc6b54bf824c36572c30d9a503e9a70a043d1f135f9c03c1fc/causalml-0.4.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/54/4kkg30g93bn1nqsz25r0qkfw0000gq/T/pip-install-hjz2ribq/causalml/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/54/4kkg30g93bn1nqsz25r0qkfw0000gq/T/pip-install-hjz2ribq/causalml/
``` 

After install Cython and running `pip install causalml` this occurred: 

```bash
 Error compiling Cython file:
------------------------------------------------------------
...
            if sample_weight != NULL:
                # the weights of 1 and 1 + eps are used for control and treatment respectively
                is_treated = (sample_weight[i] - 1.0) * one_over_eps

            # assume that there is only one output (k = 0)
            y_ik = y[i * self.y_stride]
                            ^
------------------------------------------------------------

causalml/inference/tree/causaltree.pyx:163:29: Accessing Python attribute not allowed without gil
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    ext_modules=cythonize(extensions),
  File "/Users/MaximilianFranz/anaconda3/envs/justcause/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/Users/MaximilianFranz/anaconda3/envs/justcause/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: causalml/inference/tree/causaltree.pyx
```

I'm not familiar with the intricacies of Cython and compiling `.pyx` files, thus I can't point at any potential underlying issue. Maybe it's just me? 

Any ideas or tips how to solve this?

**Comment by jeongyoonlee** [comment]
Hi @MaximilianFranz, which platform are you using? I just tried to pip-install `causalml` in a conda environment on macOS Mojave without `Cython` and it went through without an error - It installed missing dependencies including `Cython`.

Sometimes, `Cython` causes an issue with incompatible GCC version installed in the system. If you're on macOS, upgrading X Code with command line tools might help.

Please let me know if it works.

**Comment by MaximilianFranz** [comment]
Hey, @jeongyoonlee, thanks for the fast reply. I set up an empty conda (v.4.7.12) env on MacOS 10.14.6 Mojave and tried again. Same thing happens.
`gcc --version` yields 
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
I just updated X-Code Command Line Tools, but the `gcc --version` yields the same output and `pip install causalml` still fails with missing Cython.

Can I be of help with any further information about the system? For my colleague the same happened, when he tried to pip-install.

**Comment by jeongyoonlee** [comment]
From the path, I noticed that you use Python 3.7. To isolate the issue, could you try pip-install on Python 3.6 env? Thanks!

**Comment by MaximilianFranz** [comment]
Indeed, **it works** with Python 3.6.9! 
It seems that with Python 3.7 it has problems 1) determining and fetching dependencies and 2) building .pyx files, maybe because of `PEP 538`? 

I found [this](https://github.com/numpy/numpy/issues/12977) issue when searching for the error I got installing causalml on python 3.7 (after manually installing numpy and cython). Seems to be a version conflict in numpy / cython depending on the python version used..

**Comment by MaximilianFranz** [comment]
Also, providing pre-compiled [Wheels](https://packaging.python.org/tutorials/packaging-projects/) might solve the problem..

**Comment by jeongyoonlee** [comment]
> Also, providing pre-compiled [Wheels](https://packaging.python.org/tutorials/packaging-projects/) might solve the problem..

I noted other OSS projects had similar issues reported. Providing a new wheel seems the easiest solution for macOS. I will upload one soon and keep you posted. Thanks for checking!

**Comment by jeongyoonlee** [comment]
Just uploaded a new wheel for Python 3.7 on macOS. @MaximilianFranz, could you try it again and let me know if it works?

**Comment by jeongyoonlee** [comment]
Also the error message was caused by the new `scikit-learn` version (0.21.x) due to the changes in their Cython code. When I used `scikit-learn==0.20.3`, it worked for me with Python 3.7 on macOS.

Currently, the old versions of some packages including matplotlib, scipy, etc. are needed for Python 2.x support. We will discuss if we can drop Python 2.x support.

Thanks!

**Comment by MaximilianFranz** [comment]
Hey @jeongyoonlee, the wheel for 3.7 works. Thank you very much! 
Let's hope the Cython and scikit versions are updated soon to work together again, because pinning versions might lead to conflicts in packaging later on. 
It's for you to decide to close or not!

**Comment by jeongyoonlee** [comment]
No problem. We also want to take advantage of latest versions. Please stay tuned. :)

**Comment by MaximilianFranz** [comment]
Hey @jeongyoonlee, would you be able to release a version for Python 3.7 that does not have the pinned requirements for SciPy and `matplotlib`? 
As far as i can see, these are only required for Python 2.X support. However, in our project, we need to manually pin matplotlib in the conda env in order to be able to install causalml, which leads to problems further down the road. 

As to the problem with `scikit-learn`, any idea where to go with this?

**Comment by FlorianWilhelm** [comment]
@jeongyoonlee, thanks for your replies. I don't understand why a library like CausalML would need to pin its dependencies for Python 2 support. Since libraries like matplotlib use the `python_requires>=...` option in `setup.py` or `setup.cfg`, they define which Python version a given version of the library requires at least. 

That means that if you would not pin your dependencies like matplotlib it should work just fine. If a Python 2 user would install your package then `pip` would install the latest matplotlib version which still supports Python 2. For Python 3 users it would install the latest and greatest for Python 3. 

In general, it's no good practice to have strict version pinning, i.e. `==VERSION`, in a library since this makes the library really hard to use in connection with other libraries.

**Comment by jeongyoonlee** [comment]
> That means that if you would not pin your dependencies like matplotlib it should work just fine. If a Python 2 user would install your package then `pip` would install the latest matplotlib version which still supports Python 2. For Python 3 users it would install the latest and greatest for Python 3.

Thanks for the comments, @FlorianWilhelm and I agree that it'd be ideal without pinning specific versions, but, unfortunately, it is not the case here because some packages don't follow the practice specifying `python_requires`, `install_requires` and `setup_requires` within their `setup.py`. - We have a Python 2.7 CI/CD set up at work, and without specifying those versions, installation failed. :(

As mentioned, we're in discussion of dropping Python 2 support - as soon as this month's 0.5.0 release. Personally, I can't wait to make this happen. :)

**Comment by FlorianWilhelm** [comment]
@jeongyoonlee, thanks I am looking forward to the new release! Will you also add `cython` to `setup_requires` since currently, one cannot use a `requirements.txt` file to install CausalML because of that missing dependency. One has to install `cython` separately.

**Comment by jeongyoonlee** [comment]
> @jeongyoonlee, thanks I am looking forward to the new release! Will you also add `cython` to `setup_requires` since currently, one cannot use a `requirements.txt` file to install CausalML because of that missing dependency. One has to install `cython` separately.

I see. Could you please file a separate issue for this? I will work on it. Or even better, if you submit a PR - after creating an issue, that will be great as well. ;)

Thanks again!

**Comment by xxxibntkjgn** [comment]
Hi,

I got again error with ImportError: Building module causalml.inference.tree.causaltree failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]

**Comment by xxxibntkjgn** [comment]
I include here the whole error, I wish someone helps 

---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    116         try:
--> 117             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
    118                        extra_postargs)

~/anaconda3/lib/python3.8/distutils/ccompiler.py in spawn(self, cmd)
    909     def spawn(self, cmd):
--> 910         spawn(cmd, dry_run=self.dry_run)
    911 

~/anaconda3/lib/python3.8/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

~/anaconda3/lib/python3.8/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    156                         cmd = executable
--> 157                     raise DistutilsExecError(
    158                           "command %r failed with exit status %d"

DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
    213                 module_name = name
--> 214             so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
    215                                    inplace=build_inplace, language_level=language_level)

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in build_module(name, pyxfilename, pyxbuild_dir, inplace, language_level)
    185     from . import pyxbuild
--> 186     so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
    187                                   build_in_temp=build_in_temp,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyxbuild.py in pyx_to_dll(filename, ext, force_rebuild, build_in_temp, pyxbuild_dir, setup_args, reload_support, inplace)
    101         obj_build_ext = dist.get_command_obj("build_ext")
--> 102         dist.run_commands()
    103         so_path = obj_build_ext.get_outputs()[0]

~/anaconda3/lib/python3.8/distutils/dist.py in run_commands(self)
    965         for cmd in self.commands:
--> 966             self.run_command(cmd)
    967 

~/anaconda3/lib/python3.8/distutils/dist.py in run_command(self, command)
    984         cmd_obj.ensure_finalized()
--> 985         cmd_obj.run()
    986         self.have_run[command] = 1

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in run(self)
    185 
--> 186         _build_ext.build_ext.run(self)
    187 

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in run(self)
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in build_extensions(self)
    194         # Call original build_extensions
--> 195         _build_ext.build_ext.build_extensions(self)
    196 

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extensions(self)
    448         else:
--> 449             self._build_extensions_serial()
    450 

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in _build_extensions_serial(self)
    473             with self._filter_build_errors(ext):
--> 474                 self.build_extension(ext)
    475 

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extension(self, ext)
    527 
--> 528         objects = self.compiler.compile(sources,
    529                                          output_dir=self.build_temp,

~/anaconda3/lib/python3.8/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 

~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 

CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-9827cbd2e4e6> in <module>
      2 from data_prep import read_prep_data
      3 from action_rules import actionDiscovery, interpretRules, get_unique_actions
----> 4 from uplift_tree import create_uplift_tree
      5 import package.user
      6 user.doSomething()

~/Desktop/RWTH/WS21:22/Seminar/CausalRulesDiscovery/src/uplift_tree.py in <module>
----> 1 from causalml.inference.tree import UpliftTreeClassifier
      2 from causalml.inference.tree import uplift_tree_string, uplift_tree_plot
      3 from sklearn.model_selection import train_test_split
      4 from log_processing import filter_log, process_data
      5 

~/Desktop/RWTH/WS21:22/Seminar/CausalRulesDiscovery/src/causalml/inference/tree/__init__.py in <module>
      1 from .models import UpliftTreeClassifier, DecisionTree
      2 from .models import UpliftRandomForestClassifier
----> 3 from  .causaltree import CausalMSE, CausalTreeRegressor
      4 from .plot import uplift_tree_string, uplift_tree_plot
      5 from .utils import cat_group, cat_transform, cv_fold_index, cat_continuous, kpi_transform

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(self, fullname)
    457         else:
    458             #print "MODULE", fullname
--> 459             module = load_module(fullname, self.path,
    460                                  self.pyxbuild_dir,
    461                                  build_inplace=self.inplace,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
    229                 name, traceback.format_exception_only(*sys.exc_info()[:2])))
    230             if sys.version_info[0] >= 3:
--> 231                 raise exc.with_traceback(tb)
    232             else:
    233                 exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in load_module(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)
    212             else:
    213                 module_name = name
--> 214             so_path = build_module(module_name, pyxfilename, pyxbuild_dir,
    215                                    inplace=build_inplace, language_level=language_level)
    216         mod = imp.load_dynamic(name, so_path)

~/anaconda3/lib/python3.8/site-packages/pyximport/pyximport.py in build_module(name, pyxfilename, pyxbuild_dir, inplace, language_level)
    184 
    185     from . import pyxbuild
--> 186     so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
    187                                   build_in_temp=build_in_temp,
    188                                   pyxbuild_dir=pyxbuild_dir,

~/anaconda3/lib/python3.8/site-packages/pyximport/pyxbuild.py in pyx_to_dll(filename, ext, force_rebuild, build_in_temp, pyxbuild_dir, setup_args, reload_support, inplace)
    100     try:
    101         obj_build_ext = dist.get_command_obj("build_ext")
--> 102         dist.run_commands()
    103         so_path = obj_build_ext.get_outputs()[0]
    104         if obj_build_ext.inplace:

~/anaconda3/lib/python3.8/distutils/dist.py in run_commands(self)
    964         """
    965         for cmd in self.commands:
--> 966             self.run_command(cmd)
    967 
    968     # -- Methods that operate on its Commands --------------------------

~/anaconda3/lib/python3.8/distutils/dist.py in run_command(self, command)
    983         cmd_obj = self.get_command_obj(command)
    984         cmd_obj.ensure_finalized()
--> 985         cmd_obj.run()
    986         self.have_run[command] = 1
    987 

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in run(self)
    184             optimization.disable_optimization()
    185 
--> 186         _build_ext.build_ext.run(self)
    187 
    188     def build_extensions(self):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in run(self)
    338 
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 
    342     def check_extensions_list(self, extensions):

~/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py in build_extensions(self)
    193             ext.sources = self.cython_sources(ext.sources, ext)
    194         # Call original build_extensions
--> 195         _build_ext.build_ext.build_extensions(self)
    196 
    197     def cython_sources(self, sources, extension):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extensions(self)
    447             self._build_extensions_parallel()
    448         else:
--> 449             self._build_extensions_serial()
    450 
    451     def _build_extensions_parallel(self):

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in _build_extensions_serial(self)
    472         for ext in self.extensions:
    473             with self._filter_build_errors(ext):
--> 474                 self.build_extension(ext)
    475 
    476     @contextlib.contextmanager

~/anaconda3/lib/python3.8/distutils/command/build_ext.py in build_extension(self, ext)
    526             macros.append((undef,))
    527 
--> 528         objects = self.compiler.compile(sources,
    529                                          output_dir=self.build_temp,
    530                                          macros=macros,

~/anaconda3/lib/python3.8/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

~/anaconda3/lib/python3.8/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    118                        extra_postargs)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 
    122     def create_static_lib(self, objects, output_libname,

ImportError: Building module causalml.inference.tree.causaltree failed: ["distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"]

**Comment by jeongyoonlee** [comment]
Thanks for reporting the issue, @xxxibntkjgn. The issue you're having looks different from the original issue. Could you please open a new issue with the commands you executed as well as system environment information?

**Comment by heidi-catch** [comment]
I came across a similar error when installing the package and I got this along the line "missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun." So I ended up installing the the command line tools via `xcode-select --install` in the global environment. It prompted to download and install the command line tool. After the installation (which took a while), restarted the terminal and it worked.

**Comment by vorsprungdurchtae** [comment]
This error occured because I tried it on jupyter notebook.
I resolved this problem using the conda virtual environment.
I am using macOS, navigated directory where the conda libraries are installed, I got installed again this causalml, then it worked.
