### ISSUE TITLE
build from source failing: no such file or directory <crpyt.h>

### ISSUE THREAD

**Issue by ras44** [uber/causalml#767]
[Builds from source](https://github.com/uber/causalml/actions/workflows/test-build-from-source.yml) are failing for python 3.7 and 3.8 due to a missing file <crypt.h>:

![image](https://github.com/uber/causalml/assets/9282281/5cd547d3-898e-4d45-98c6-255ce2509aa4)

**To Reproduce**
Follow build from source installation steps

**Expected behavior**
No failure.

**Environment (please complete the following information):**
See run details at: https://github.com/uber/causalml/actions/runs/8746279634

**Comment by jeongyoonlee** [comment]
This seems related to [this change in conda-forge](https://github.com/conda-forge/linux-sysroot-feedstock/issues/52#issuecomment-1946615469).

**Comment by ras44** [comment]
closing after fixes merged
