### ISSUE TITLE
Usage of setup_requires to define cython dependency

### ISSUE THREAD

**Issue by FlorianWilhelm** [uber/causalml#77]
Right now `cython` and `numpy` is needed to run `setup.py` which leads to a hen and egg problem. If I want to install CausalML in a fresh virtual environment using a `requirements.txt` file, which includes `cython` and `numpy`, the installation will fail because both aren't installed before the `setup.py` file of CausalML is read.

The is problem is also subject of following [StackOverflow issue](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip). The actual solution is described [here](https://luminousmen.com/post/resolve-cython-and-numpy-dependencies) for your case.

**Comment by FlorianWilhelm** [comment]
Have you ever considered using `setup.cfg` for most of your configurations? Take a look at [PyScaffold](https://pyscaffold.org/) for setting up projects really easily ;-)

**Comment by jeongyoonlee** [comment]
> Have you ever considered using `setup.cfg` for most of your configurations? Take a look at [PyScaffold](https://pyscaffold.org/) for setting up projects really easily ;-)

I haven't. Looks very convenient for a new project. Would you recommend that we migrate causalml to PyScaffold as shown [here](https://pyscaffold.org/en/latest/migration.html)?

I guess that for the complex issues like cython vs. numpy and other compatibility issues among dependencies still need to be addressed manually.

**Comment by jeongyoonlee** [comment]
Addressed by @FlorianWilhelm with PR #78, which will be included in 0.5.0 release.

**Comment by FlorianWilhelm** [comment]
@jeongyoonlee, thanks for merging my PR so fast. Regarding PyScaffold I think CausalML could benefit from the more declarative approach of using a `setup.cfg` instead of a manually written `setup.py` with the exception of Cython extensions and Numpy includes. Also, the `src` layout helps to overcome a common error when [tox is testing something different than what you actually expect](https://bskinn.github.io/My-How-Why-Pyproject-Src/). Another advantage is that the version information is pulled directly from git tags using the setuptools-scm library (which is used by PyScaffold). Maybe PyScaffold could be a consideration for version 0.6. 

For new projects, PyScaffold definitely is a good tool to get going really fast.
