### ISSUE TITLE
Can CausalML allows missing predictors?

### ISSUE THREAD

**Issue by aw47aw47** [uber/causalml#784]
I got errors messages indicating NAN values in my predictors in both UpliftRandomForestClassifier and CEVAE.  A little surprised since a lot of non-traditional-statistical-based ML methods allow missing values.  

Error message: Input X contains NaN

I might miss something.  But if there're solutions/additional enhancement can be done, please let me know.

**Comment by jeongyoonlee** [comment]
Not all estimators support inputs with NaN. We plan to add the support to Uplift Trees/Uplift RandomForest, but for CEVAE, we use Pyro's implementation, and it's up to the Pyro team whether to add the support or not.

Meanwhile, you can impute missing values either using scikit-learn's Imputer ([ref](https://scikit-learn.org/1.5/modules/impute.html)) or something else.
