### ISSUE TITLE
How to install casualml without torch?

### ISSUE THREAD

**Issue by roseaysina** [uber/causalml#791]
Hola!

Is it possible to bring torch as [extra](https://python-poetry.org/docs/pyproject/#extras) package in `casualml`?
So that users that do not need this package could install `casualml` without it? 

There is similar problem: https://github.com/uber/causalml/discussions/480
But the proposed solution (`pip install causalml --no-deps torch`) can't be used with poetry. It is not possible there to install a package and exclude its dependency from lock file. 

Our app image weights like 8GB because of torch :(

**Comment by jeongyoonlee** [comment]
Hi @roseaysina. It was done with #789 and is available at the master branch. We will release a new v0.15.2 version soon (#792), so `causalml` can be installed without `torch` by default.

**Comment by roseaysina** [comment]
@jeongyoonlee hi! Thanks a lot! I'm glad I'm not the only one who requested this feature.

Is there any information about the date when new version will be released?

**Comment by jeongyoonlee** [comment]
The new v0.15.2 was released yesterday. :)
