### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zju-lyx** [uber/causalml#798]
When calculating the Qini score, we use the area under the Qini curve and subtract the random value. In the code, we generate a Qini curve by assigning random scores to each sample and then use the area under this curve as the random value. However, in many cases, the random value is directly set to 0.5. There is a significant difference between these two methods of calculation. How should we understand this discrepancy?

**Comment by jeongyoonlee** [comment]
Thanks for your question, @zju-lyx. We updated the uplift/Qini curve and score calculation to use the theoretical random instead of the sampled random in #799. With the change, the normalized AUUC and Qini scores for random are always 0.5 and 0.0, respectively.
