### ISSUE TITLE
function  "plot_causal_tree"   some  KeyError: 0

### ISSUE THREAD

**Issue by superwood** [uber/causalml#801]
**Describe the bug**
from causalml.inference.tree.plot import plot_causal_tree
#### after  train  
train_res = ctree.predict(X = X_r.values, with_outcomes=True,check_input=False)
plot_causal_tree(causal_tree = ctree, precision = 3)

**but there is error about “KeyError: 0”**

~/.local/lib/python3.7/site-packages/causalml/inference/tree/plot.py in plot_causal_tree(causal_tree, max_depth, feature_names, class_names, label, filled, impurity, groups_count, treatment_groups, node_ids, proportion, rounded, precision, ax, fontsize)
    656         fontsize=fontsize,
    657     )
--> 658     exporter.export(causal_tree, ax=ax)

~/.local/lib/python3.7/site-packages/sklearn/tree/_export.py in export(self, decision_tree, ax)
    654         ax.clear()
    655         ax.set_axis_off()
--> 656         my_tree = self._make_tree(0, decision_tree.tree_, decision_tree.criterion)
    657         draw_tree = buchheim(my_tree)
    658 

~/.local/lib/python3.7/site-packages/sklearn/tree/_export.py in _make_tree(self, node_id, et, criterion, depth)
    630         # traverses _tree.Tree recursively, builds intermediate
    631         # "_reingold_tilford.Tree" object
--> 632         name = self.node_to_str(et, node_id, criterion=criterion)
    633         if et.children_left[node_id] != _tree.TREE_LEAF and (
    634             self.max_depth is None or depth <= self.max_depth

~/.local/lib/python3.7/site-packages/causalml/inference/tree/plot.py in node_to_str(self, tree, node_id, criterion)
    471             for group in self.treatment_groups:
    472                 node_string += (
--> 473                     f"Group {group} = {self.causal_tree._groups_cnt[node_id][group]} "
    474                 )
    475         node_string += characters[4]

KeyError: 0

**To Reproduce**
causalml    0.15.2
scikit-learn 1.0.2

**Comment by NancyLTY** [comment]
I have the same problem. Do you know how to solve it?
