### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#81]
This task is to drop Python 2 support and allow users to use latest versions of dependencies such as scipy, scikit-learn, matplotlib, pandas, etc. which only support Python 3 in their latest releases.

It requires updating `setup.py` and check compatibilities between `causalml` and other latest libraries. Currently latest `scikit-learn` is not compatible with `causalml` because of its change in Cython code for tree algorithms.

**Comment by hugovk** [comment]
See also "NEP 29 — Recommend Python and Numpy version support as a community policy standard":

* https://numpy.org/neps/nep-0029-deprecation_policy.html
