### ISSUE TITLE
Fix CausalTreeRegressor

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#83]
`CausalTreeRegressor`'s ATE/ITE estimates are off with synthetic data 2, 3, and 4.

**Comment by peterfoley** [comment]
@jeongyoonlee I'd be interested in helping out with this one. Do you already have tests/notebooks/gists that show the discrepancy?

**Comment by TomaszZamacinski** [comment]
@jeongyoonlee I think that it is due to the issue with the impurity computation. I have made the following pull request that fixes it: https://github.com/uber/causalml/pull/105

**Comment by jeongyoonlee** [comment]
> @jeongyoonlee I'd be interested in helping out with this one. Do you already have tests/notebooks/gists that show the discrepancy?

Here is a [gist](https://gist.github.com/jeongyoonlee/a311a847d9298802a56577a3f830beee) to test `CausalTreeRegressor` with synthetic data. It currently shows a reasonable uplift curve for the first synthetic data, but weird results for other synthetic data.

**Comment by jeongyoonlee** [comment]
> @jeongyoonlee I think that it is due to the issue with the impurity computation. I have made the following pull request that fixes it: #105

Thanks for fixing the bug @TomaszZamacinski. After the fix, it now generates correct results for the 2nd and 4th and okay result for the 1st.

Thanks for your contribution!
