### ISSUE TITLE
WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

### ISSUE THREAD

**Issue by XiaoshuiHuang** [uber/causalml#88]
There are several warnings in the example of "meta_learners_with_synthetic_data_multiple_treatment".
The warnings occur when I run the code to "learner_s.estimate_ate(X=X, treatment=treatment, y=y, return_ci=True, bootstrap_ci=True, n_bootstraps=100, bootstrap_size=5000)"

The warning is 

WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

**Comment by jeongyoonlee** [comment]
Thanks for your report, @XiaoshuiHuang!

`reg:squarederror` was introduced in XGBoost 0.90. Previous versions don't recognize it and will raise an unknown objective function error.

Since it's just a warning for 0.90+, for now, let's keep it as `reg:linear` for better compatibility.
