### ISSUE TITLE
Allow estimate_ate() for user prediction input

### ISSUE THREAD

**Issue by ppstacy** [uber/causalml#92]
It's really helpful that we have the function estimate_ate() to return the mean and confidence interval (LB, UB) of the ATE estimate. But currently it will generate the predictions under the hood with fit_prediction() function. It might be confusing if someone didn't look at the code base and use it for a validation data set . Could we consider support for user prediction input as an optional input? So we could use this function for more purposes.

**Comment by MaximilianFranz** [comment]
A note on the terminology from my perspective. 
I find it useful that one discerns between `estimate_ate()` and `predict_ite()` or (in your case) `predict()`, for the one is an estimation of a value (the ATE) inherent in a sample from a population, while the other is a prediction of a pre-fit model on some data that can also be out-of-sample with respect to the training data. A classic ATE-Estimator in my opinion is something like the [DoublyRobustEstimator](https://www4.stat.ncsu.edu/~davidian/double.pdf), that cannot and should not be used as a predictor, while the use of `estimate_ate()` is less clear for methods like the S- and T-Learner. Essentially, for these methods, the ATE ist just a mean of ITE predictions and thus `estimate_ate` might be a bit confusing. 

What I did not understand yet is what you mean by 'user prediction as input', could you elaborate on that?

**Comment by jeongyoonlee** [comment]
Thanks for the comments, @ppstacy and @MaximilianFranz.

I agree @MaximilianFranz's comment: `estimate_ate()` should be different from `predict()` e.g. One of our learners, `TMLELearner` is also not a predictor and has only `estimate_ate()` without `predict()`.

@MaximilianFranz, to answer to your question, I think what @ppstacy meant by "user prediction input" is a feature matrix, `X` for prediction.
