### ISSUE TITLE
ValueError running example notebook

### ISSUE THREAD

**Issue by SSepi** [uber/causalml#94]
Thanks for the package, great contribution!

I'm trying to run the notebook here: https://github.com/uber/causalml/blob/master/examples/meta_learners_with_synthetic_data.ipynb

Getting the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-3e036ea08429> in <module>
     13 from causalml.match import NearestNeighborMatch, MatchOptimizer, create_table_one
     14 from causalml.propensity import ElasticNetPropensityModel
---> 15 from causalml.dataset import *
     16 from causalml.metrics import *
     17 

/opt/conda/lib/python3.6/site-packages/causalml/dataset/__init__.py in <module>
      6 from .classification import make_uplift_classification
      7 
----> 8 from .synthetic import get_synthetic_preds, get_synthetic_preds_holdout
      9 from .synthetic import get_synthetic_summary, get_synthetic_summary_holdout
     10 from .synthetic import scatter_plot_summary, scatter_plot_summary_holdout

/opt/conda/lib/python3.6/site-packages/causalml/dataset/synthetic.py in <module>
     14 
     15 from causalml.inference.meta import BaseXRegressor, BaseRRegressor, BaseSRegressor, BaseTRegressor
---> 16 from causalml.inference.tree import CausalTreeRegressor
     17 from causalml.propensity import ElasticNetPropensityModel
     18 from causalml.metrics import plot_gain, get_cumgain

/opt/conda/lib/python3.6/site-packages/causalml/inference/tree/__init__.py in <module>
      1 from .models import UpliftTreeClassifier, DecisionTree
      2 from .models import UpliftRandomForestClassifier
----> 3 from  .causaltree import CausalMSE, CausalTreeRegressor
      4 from .plot import uplift_tree_string, uplift_tree_plot
      5 from .utils import cat_group, cat_transform, cv_fold_index, cat_continuous, kpi_transform

_splitter.pxd in init causalml.inference.tree.causaltree()

ValueError: sklearn.tree._splitter.Splitter size changed, may indicate binary incompatibility. Expected 368 from C header, got 360 from PyObject
```

Installed the package on 4.12.2019 using pip, running causalml version 0.5.0.

The problem seems to come from scikit.-learn version 0.22.0 which was released on 3.12.2019. If I downgrade to scikit-learn 0.21.0, everything works fine.

**Comment by jeongyoonlee** [comment]
Thanks for reporting the issue, @SSepi. As you noted, it's because of the updates in `scikit-learn`'s  Cython code, on which `CausalTreeRegressor` depends on.

There are a couple of ways to address this:
1. Update `CausalTreeRegressor`'s Cython code to be compatible with `scikit-learn>=0.23.0`
2. Fix the `scikit-learn`'s version in `requirements.txt` to 0.22.0
3. Remove the dependency on `sklearn.tree` and implement the base tree algorithm from the scratch.

We will review each option and provide updates soon. Meanwhile, please use `scikit-learn==0.22.0`.

Also I'd love to hear what others think on this. Any comments and feedbacks will be appreciated.

Thanks!

**Comment by peterfoley** [comment]
It looks like the [Travis tests already switched to 0.22](https://travis-ci.com/uber/causalml/jobs/267093625#L196) when it was released, and they're still passing, so this seems like a packaging or install order issue.

**Comment by peterfoley** [comment]
It seems to be packaging-related. I was able to recreate the error in a fresh env:
```bash
conda env remove --name cml_sk22 || true
conda create -y -n cml_sk22 python=3.7 pip
conda activate cml_sk22
pip install causalml
python -c 'from causalml.dataset import *'
# throws the binary incompatibility error message 
```

and was able to resolve it by pip-installing directly from github with either the current master or 0.5.0 branch:
```bash
pip uninstall -y causalml
pip install git+https://github.com/uber/causalml.git#egg=causalml
# or 0.5.0 at git+https://github.com/uber/causalml.git@jeong/0.5.0_release#egg=causalml
```

**Comment by jeongyoonlee** [comment]
This issue seems to be resolved. `pip` installation goes through with the same setting @peterfoley used above.
